import json
import os

chunks_dir = "./course/sfid/phase3/data/chunks"

def make_noun(gender):
    return {
        "word_type": "noun",
        "noun_gender": gender,
        "is_regular_verb": None,
        "verb_imperativ": None,
        "verb_presens": None,
        "verb_preteritum": None,
        "verb_supinum": None,
        "verb_perfekt_particip": None,
        "adj_en": None,
        "adj_ett": None,
        "adj_plural": None,
        "adj_komparativ": None,
        "adj_superlativ": None
    }

def make_verb(is_regular, imp, pres, pret, sup, part=None):
    return {
        "word_type": "verb",
        "noun_gender": None,
        "is_regular_verb": is_regular,
        "verb_imperativ": imp,
        "verb_presens": pres,
        "verb_preteritum": pret,
        "verb_supinum": sup,
        "verb_perfekt_particip": part,
        "adj_en": None,
        "adj_ett": null_if_none(None),
        "adj_plural": None,
        "adj_komparativ": None,
        "adj_superlativ": None
    }

def null_if_none(val):
    return val

def make_adj(en, ett, pl, komp, sup):
    return {
        "word_type": "adjective",
        "noun_gender": None,
        "is_regular_verb": None,
        "verb_imperativ": None,
        "verb_presens": None,
        "verb_preteritum": None,
        "verb_supinum": None,
        "verb_perfekt_particip": None,
        "adj_en": en,
        "adj_ett": ett,
        "adj_plural": pl,
        "adj_komparativ": komp,
        "adj_superlativ": sup
    }

meta_38 = {
    "identitet": make_noun("en"),
    "turistnäring": make_noun("en"),
    "självstyrande": make_adj("självstyrande", "självstyrande", "självstyrande", "mer självstyrande", "mest självstyrande"),
    "landskapsblomma": make_noun("en"),
    "landskapsdjur": make_noun("ett"),
    "kaprifol": make_noun("en"),
    "inofficiell": make_adj("inofficiell", "inofficiellt", "inofficiella", "mer inofficiell", "mest inofficiell"),
    "stjärna": make_noun("en"),
    "turisinformation": make_noun("en"),
    "thailändsk": make_adj("thailändsk", "thailändskt", "thailändska", "mer thailändsk", "mest thailändsk"),
    "paviljong": make_noun("en"),
    "få lust": make_verb(False, "få lust", "får lust", "fick lust", "fått lust", None),
    "salta bad": make_noun("ett"),
    "klippig": make_adj("klippig", "klippigt", "klippiga", "klippigare", "klippigast"),
    "nyfångad": make_adj("nyfångad", "nyfångat", "nyfångade", "mer nyfångad", "mest nyfångad"),
    "skaldjur": make_noun("ett"),
    "västra": make_adj("västra", "västra", "västra", "mer västra", "mest västra"),
    "sträcka": make_noun("en"),
    "norska gränsen": make_noun("en"),
    "cirka": make_adj("cirka", "cirka", "cirka", "cirka", "cirka"),
    "tredje största": make_adj("tredje största", "tredje största", "tredje största", "mer tredje största", "mest tredje största"),
    "natur": make_noun("en"),
    "glida fram": make_verb(False, "glid fram", "glider fram", "gled fram", "glidit fram", "gliden fram"),
    "kajak": make_noun("en"),
    "campa": make_verb(True, "campa", "campar", "campade", "campat", "campad"),
    "öde": make_adj("öde", "öde", "öde", "mer öde", "mest öde"),
    "midnattsol": make_noun("en"),
    "säl": make_noun("en"),
    "uppfyllas": make_verb(True, "uppfylls", "uppfylls", "uppfylldes", "uppfyllts", "uppfylld"),
    "själ": make_noun("en"),
    "sakna": make_verb(True, "sakna", "saknar", "saknade", "saknat", "saknad"),
    "tevebolag": make_noun("ett"),
    "placera": make_verb(True, "placera", "placerar", "placerade", "placerat", "placerad"),
    "sjunde plats": make_noun("en"),
    "vildmarksområde": make_noun("ett"),
    "syster": make_noun("en"),
    "vars": make_adj("vars", "vars", "vars", "vars", "vars"),
    "gifta om sig": make_verb(True, "gift dig om", "gifter om sig", "gifte om sig", "gift om sig", "gift om sig"),
    "elak": make_adj("elak", "elakt", "elaka", "elakare", "elakast"),
    "lyckligt slut": make_noun("ett"),
    "julfest": make_noun("en"),
    "konst": make_noun("en"),
    "ett och samma": make_adj("ett och samma", "ett och samma", "ett och samma", "mer ett och samma", "mest ett och samma"),
    "brist": make_noun("en"),
    "kommunikation": make_noun("en"),
    "varm": make_adj("varm", "varmt", "varma", "varmare", "varmast"),
    "välkomnande": make_adj("välkomnande", "välkomnande", "välkomnande", "mer välkomnande", "mest välkomnande"),
    "tvärtom": make_adj("tvärtom", "tvärtom", "tvärtom", "tvärtom", "tvärtom"),
    "grym": make_adj("grym", "grymt", "grymma", "grymmare", "grymmast"),
    "oförstående": make_adj("oförstående", "oförstående", "oförstående", "mer oförstående", "mest oförstående")
}

meta_39 = {
    "tystnad": make_noun("en"),
    "söka kontakt": make_verb(True, "sök kontakt", "söker kontakt", "sökte kontakt", "sökt kontakt", "sökt kontakt"),
    "parasit": make_noun("en"),
    "leva på andra": make_verb(True, "lev på andra", "lever på andra", "levde på andra", "levt på andra", None),
    "leva för": make_verb(True, "lev för", "lever för", "levde för", "levt för", None),
    "ö": make_noun("en"),
    "norr": make_noun("en"),
    "landskap": make_noun("ett"),
    "fascinera": make_verb(True, "fascinera", "fascinerar", "fascinerade", "fascinerat", "fascinerad"),
    "sista": make_adj("sista", "sista", "sista", "sista", "sista"),
    "begravd": make_adj("begravd", "begravt", "begravda", "mer begravd", "mest begravd"),
    "dröm": make_noun("en"),
    "nära samarbete": make_noun("ett"),
    "favorit": make_noun("en"),
    "regelbunden": make_adj("regelbunden", "regelbundet", "regelbundna", "mer regelbunden", "mest regelbunden"),
    "actionfilm": make_noun("en"),
    "kärleksfilm": make_noun("en"),
    "dokumentär": make_noun("en"),
    "snyftare": make_noun("en"),
    "komedi": make_noun("en"),
    "deckare": make_noun("en"),
    "skräckfilm": make_noun("en"),
    "favoritfilm": make_noun("en"),
    "Vad handlar den om?": make_verb(True, "handla om", "handlar om", "handlade om", "handlat om", None),
    "gripande": make_adj("gripande", "gripande", "gripande", "mer gripande", "mest gripande"),
    "sann": make_adj("sann", "sant", "sanna", "sannare", "sannast"),
    "urkul": make_adj("urkul", "urkul", "urkul", "mer urkul", "mest urkul"),
    "naturlig": make_adj("naturlig", "naturligt", "naturliga", "naturligare", "naturligast"),
    "samlingsplats": make_noun("en"),
    "stora och små": make_adj("stora och små", "stora och små", "stora och små", "mer stora och små", "mest stora och små"),
    "brygga": make_noun("en"),
    "fiska krabba": make_verb(True, "fiska krabba", "fiskar krabba", "fiskade krabba", "fiskat krabba", None),
    "ta något att äta eller dricka": make_verb(False, "ta något", "tar något", "tog något", "tagit något", None),
    "servera": make_verb(True, "servera", "serverar", "serverade", "serverat", "serverad"),
    "bryggdans": make_noun("en"),
    "milsvid": make_adj("milsvid", "milsvitt", "milsvida", "mer milsvid", "mest milsvid"),
    "näst störst": make_adj("näst störst", "näst störst", "näst största", "mer näst störst", "mest näst störst"),
    "bonderepublik": make_noun("en"),
    "imponera": make_verb(True, "imponera", "imponerar", "imponerade", "imponerat", "imponerad"),
    "älv": make_noun("en"),
    "kristallklar": make_adj("kristallklar", "kristallklart", "kristallklara", "mer kristallklar", "mest kristallklar"),
    "uppleva": make_verb(True, "upplev", "upplever", "upplevde", "upplevt", "upplevd"),
    "hjortron": make_noun("ett"),
    "fiska": make_verb(True, "fiska", "fiskar", "fiskade", "fiskat", "fiskad"),
    "åka skidor": make_verb(True, "åk skidor", "åker skidor", "åkte skidor", "åkt skidor", None),
    "världsartist": make_noun("en"),
    "musikfestival": make_noun("en"),
    "mystisk": make_adj("mystisk", "mystiskt", "mystiska", "mystiskare", "mystiskast"),
    "odjur": make_noun("ett"),
    "pussa på": make_verb(True, "pussa på", "pussar på", "pussade på", "pussat på", "pussad på")
}

meta_40 = {
    "tam": make_adj("tam", "tamt", "tama", "tamare", "tamast"),
    "same": make_noun("en"),
    "finnas": make_verb(False, "finnas", "finns", "fanns", "funnits", None),
    "sameby": make_noun("en"),
    "välkomna": make_verb(True, "välkomna", "välkomnar", "välkomnade", "välkomnat", "välkomnad"),
    "livlig": make_adj("livlig", "livligt", "livliga", "livligare", "livligast"),
    "nöjesliv": make_noun("ett"),
    "lata dagar": make_noun("en"),
    "fyllda av": make_adj("fylld av", "fyllt av", "fyllda av", "mer fylld av", "mest fylld av"),
    "fysisk aktivitet": make_noun("en"),
    "turistort": make_noun("en"),
    "komma ut": make_verb(False, "kom ut", "kommer ut", "kom ut", "kommit ut", "kommen ut"),
    "vandra i fjällen": make_verb(True, "vandra i fjällen", "vandrar i fjällen", "vandrade i fjällen", "vandrat i fjällen", None),
    "äventyr": make_noun("ett"),
    "mountainbike": make_noun("en"),
    "tain": make_noun("en"),
    "vintertid": make_noun("en"),
    "skidåkning": make_noun("en"),
    "intensiv": make_adj("intensiv", "intensivt", "intensiva", "intensivare", "intensivast"),
    "lokalproducerad": make_adj("lokalproducerad", "lokalproducerat", "lokalproducerade", "mer lokalproducerad", "mest lokalproducerad"),
    "kunglighet": make_noun("en"),
    "havsbad": make_noun("ett"),
    "roa sig": make_verb(True, "roa dig", "roar sig", "roade sig", "roat sig", "road"),
    "societetshus": make_noun("ett"),
    "festa": make_verb(True, "festa", "festar", "festade", "festat", "festad"),
    "kappsegling": make_noun("en"),
    "boka boende": make_verb(True, "boka boende", "bokar boende", "bokade boende", "bokat boende", None),
    "fästning": make_noun("en"),
    "fånge": make_noun("en"),
    "tjuv": make_noun("en"),
    "mördare": make_noun("en"),
    "kriminell": make_adj("kriminell", "kriminellt", "kriminella", "mer kriminell", "mest kriminell"),
    "släpa": make_verb(True, "släpa", "släpar", "släpade", "släpat", "släpad"),
    "bygge": make_noun("ett"),
    "rymma": make_verb(True, "rymd", "rymmer", "rymde", "rymt", "rymd"),
    "järnkula": make_noun("en"),
    "fotled": make_noun("en"),
    "fungera som": make_verb(True, "fungera som", "fungerar som", "fungerade som", "fungerat som", None),
    "följa med": make_verb(True, "följ med", "följer med", "följde med", "följt med", "följd med"),
    "guida": make_verb(True, "guida", "guidar", "guidade", "guidat", "guidad"),
    "guidad tur": make_noun("en"),
    "suck": make_noun("en"),
    "galgbacke": make_noun("en"),
    "havsband": make_noun("ett"),
    "bred": make_adj("bred", "brett", "breda", "bredare", "bredast"),
    "hundra": make_adj("hundra", "hundra", "hundra", "mer hundra", "mest hundra"),
    "ta sig runt": make_verb(False, "ta dig runt", "tar sig runt", "tog sig runt", "tagit sig runt", None),
    "sommarmånad": make_noun("en"),
    "gäst": make_noun("en"),
    "förälskad": make_adj("förälskad", "förälskat", "förälskade", "mer förälskad", "mest förälskad")
}

meta_41 = {
    "hit": make_adj("hit", "hit", "hit", "hit", "hit"),
    "luft": make_noun("en"),
    "söka": make_verb(True, "sök", "söker", "sökte", "sökt", "sökt"),
    "promenera": make_verb(True, "promenera", "promenerar", "promenerade", "promenerat", "promenerad"),
    "trähus": make_noun("ett"),
    "ligga": make_verb(False, "ligg", "ligger", "låg", "legat", "legen"),
    "sydsida": make_noun("en"),
    "dam- och herrbad": make_noun("ett"),
    "hamn": make_noun("en"),
    "klimatdebatt": make_noun("en"),
    "närproducerad": make_adj("närproducerad", "närproducerat", "närproducerade", "mer närproducerad", "mest närproducerad"),
    "ekologisk": make_adj("ekologisk", "ekologiskt", "ekologiska", "mer ekologisk", "mest ekologisk"),
    "maträtt": make_noun("en"),
    "palt": make_noun("en"),
    "kokt": make_adj("kokt", "kokt", "kokta", "mer kokt", "mest kokt"),
    "riven": make_adj("riven", "rivet", "rivna", "mer riven", "mest riven"),
    "rå": make_adj("rå", "rått", "råa", "råare", "råast"),
    "potatis": make_noun("en"),
    "vetemjöl": make_noun("ett"),
    "fylld med": make_adj("fylld med", "fyllt med", "fyllda med", "mer fylld med", "mest fylld med"),
    "tärnad": make_adj("tärnad", "tärnat", "tärnade", "mer tärnad", "mest tärnad"),
    "fläsk": make_noun("ett"),
    "klick": make_noun("en"),
    "smör": make_noun("ett"),
    "smälta": make_verb(True, "smält", "smälter", "smälte", "smält", "smält"),
    "grop": make_noun("en"),
    "lingonsylt": make_noun("en"),
    "tillbehör": make_noun("ett"),
    "övrig": make_adj("övrig", "övrigt", "övriga", "mer övrig", "mest övrig"),
    "Norrland": make_noun("ett"),
    "paltkoma": make_noun("en"),
    "enorm": make_adj("enorm", "enormt", "enorma", "enormare", "enormast"),
    "trötthet": make_noun("en"),
    "paltbröd": make_noun("ett"),
    "blanda ihop": make_verb(True, "blanda ihop", "blandar ihop", "blandade ihop", "blandat ihop", "blandad ihop"),
    "bröd": make_noun("ett"),
    "saffranspannkaka": make_noun("en"),
    "ugnsgräddad": make_adj("ugnsgräddad", "ugnsgräddat", "ugnsgräddade", "mer ugnsgräddad", "mest ugnsgräddad"),
    "pannkaka": make_noun("en"),
    "ris": make_noun("ett"),
    "saffran": make_noun("en"),
    "russin": make_noun("ett"),
    "vispad": make_adj("vispad", "vispat", "vispade", "mer vispad", "mest vispad"),
    "salmbär": make_noun("ett"),
    "björnbär": make_noun("ett"),
    "ingrediens": make_noun("en"),
    "medeltiden": make_noun("en"),
    "handelscentrum": make_noun("ett"),
    "krydda": make_noun("en"),
    "lyxvara": make_noun("en")
}

meta_42 = {
    "toppklass": make_noun("en"),
    "diskotek": make_noun("ett"),
    "partysugen": make_adj("partysugen", "partysuget", "partysugna", "partysugnare", "partysugnast"),
    "fika": make_noun("en"),
    "björkskog": make_noun("en"),
    "dal": make_noun("en"),
    "vänskapsgåva": make_noun("en"),
    "glittrande": make_adj("glittrande", "glittrande", "glittrande", "mer glittrande", "mest glittrande"),
    "vit": make_adj("vit", "vitt", "vita", "vitare", "vitast"),
    "guld": make_noun("ett"),
    "minnesbyggnad": make_noun("en"),
    "inbjudan": make_noun("en"),
    "konst- och industriutställning": make_noun("en"),
    "stry": make_noun("ett"),
    "döpa": make_verb(True, "döp", "döper", "döpte", "döpt", "döpt"),
    "fira": make_verb(True, "fira", "firar", "firade", "firat", "firad"),
    "bronsstaty": make_noun("en"),
    "utsmyckning": make_noun("en"),
    "rofylld": make_adj("rofylld", "rofyllt", "rofyllda", "rofylldare", "rofylldast"),
    "blomma": make_noun("en"),
    "roddbåt": make_noun("en"),
    "näckrosdamm": make_noun("en"),
    "marknad": make_noun("en"),
    "thaimat": make_noun("en"),
    "föreläsning": make_noun("en"),
    "sälsafari": make_noun("en"),
    "nationalpark": make_noun("en"),
    "äggost": make_noun("en"),
    "hällristning": make_noun("en"),
    "kretslopp": make_noun("ett"),
    "taggmoln": make_noun("ett"),
    "karta": make_noun("en"),
    "husmanskost": make_noun("en"),
    "matkultur": make_noun("en"),
    "samlingsnamn": make_noun("ett"),
    "hemlagad": make_adj("hemlagad", "hemlagat", "hemlagade", "mer hemlagad", "mest hemlagad"),
    "vardagsmat": make_noun("en"),
    "ursprungligen": make_adj("ursprungligen", "ursprungligen", "ursprungligen", "ursprungligen", "ursprungligen"),
    "rustik": make_adj("rustik", "rustikt", "rustika", "rustikare", "rustikast"),
    "bondgård": make_noun("en"),
    "råvara": make_noun("en"),
    "fet": make_adj("fet", "fett", "feta", "fetare", "fetast"),
    "kroppsarbete": make_noun("ett"),
    "hästkött": make_noun("ett"),
    "köttbulle": make_noun("en"),
    "kåldolme": make_noun("en"),
    "1700-talet": make_noun("ett"),
    "punkt": make_noun("en"),
    "huvudperson": make_noun("en"),
    "spela": make_verb(True, "spela", "spelar", "spelade", "spelat", "spelad")
}

meta_43 = {
    "handling": make_noun("en"),
    "skriva om": make_verb(False, "skriv om", "skriver om", "skrev om", "skrivit om", "skriven om"),
    "årtionde": make_noun("ett"),
    "höra hemma": make_verb(True, "hör hemma", "hör hemma", "hörde hemma", "hört hemma", None),
    "framtidstro": make_noun("en"),
    "gå över till": make_verb(False, "gå över till", "går över till", "gick över till", "gått över till", None),
    "högertrafik": make_noun("en"),
    "decennium": make_noun("ett"),
    "drog": make_noun("en"),
    "fri sex": make_noun("ett"),
    "p-piller": make_noun("ett"),
    "godkänd": make_adj("godkänd", "godkänt", "godkända", "mer godkänd", "mest godkänd"),
    "efternamn": make_noun("ett"),
    "myndig": make_adj("myndig", "myndigt", "myndiga", "myndigare", "myndigast"),
    "äga rum": make_verb(True, "äg rum", "äger rum", "ägde rum", "ägt rum", None),
    "registrerad": make_adj("registrerad", "registrerat", "registrerade", "mer registrerad", "mest registrerad"),
    "biograf": make_noun("en"),
    "genomföra": make_verb(True, "genomför", "genomför", "genomförde", "genomfört", "genomförd"),
    "avrättning": make_noun("en"),
    "kvinnlig": make_adj("kvinnlig", "kvinnligt", "kvinnliga", "mer kvinnlig", "mest kvinnlig"),
    "ledamot": make_noun("en"),
    "Svenska akademien": make_noun("en"),
    "gås": make_noun("en"),
    "middag": make_noun("en"),
    "festmåltid": make_noun("en"),
    "klassisk": make_adj("klassisk", "klassiskt", "klassiska", "mer klassisk", "mest klassisk"),
    "timme": make_noun("en"),
    "måltid": make_noun("en"),
    "vara rädd för": make_verb(False, "var rädd för", "är rädd för", "var rädd för", "varit rädd för", None),
    "kaloririk": make_adj("kaloririk", "kaloririkt", "kaloririka", "kaloririkare", "kaloririkast"),
    "bestå av": make_verb(False, "bestå av", "består av", "bestod av", "bestått av", None),
    "ugnstekt": make_adj("ugnstekt", "ugnstekt", "ugnstekta", "mer ugnstekt", "mest ugnstekt"),
    "äppelkaka": make_noun("en"),
    "vaniljsås": make_noun("en"),
    "kryddad med": make_adj("kryddad med", "kryddat med", "kryddade med", "mer kryddad med", "mest kryddad med"),
    "ingefära": make_noun("en"),
    "kryddpeppar": make_noun("en"),
    "nejlika": make_noun("en"),
    "konjak": make_noun("en"),
    "soppa": make_noun("en"),
    "krås": make_noun("ett"),
    "hals": make_noun("en"),
    "mage": make_noun("en"),
    "hjärta": make_noun("ett"),
    "vinge": make_noun("en"),
    "katrinplommon": make_noun("ett"),
    "gräddsås": make_noun("en"),
    "äppelklyfta": make_noun("en"),
    "fylld": make_adj("fylld", "fyllt", "fyllda", "mer fylld", "mest fylld"),
    "perfekt particip": make_noun("ett")
}

meta_44 = {
    "böja": make_verb(True, "böj", "böjer", "böjde", "böjt", "böjd"),
    "varm choklad": make_noun("en"),
    "blanda i": make_verb(True, "blanda i", "blandar i", "blandade i", "blandat i", "blandad i"),
    "äggvita": make_noun("en"),
    "smet": make_noun("en"),
    "paprika": make_noun("en"),
    "tomat": make_noun("en"),
    "persika": make_noun("en"),
    "vitlök": make_noun("en"),
    "parmesan": make_noun("en"),
    "lax": make_noun("en"),
    "skinka": make_noun("en"),
    "korv": make_noun("en"),
    "ikväll": make_adj("ikväll", "ikväll", "ikväll", "ikväll", "ikväll"),
    "smörgås": make_noun("en"),
    "ta med": make_verb(False, "ta med", "tar med", "tog med", "tagit med", "tagen med"),
    "flinga": make_noun("en"),
    "havre": make_noun("en"),
    "typisk": make_adj("typisk", "typiskt", "typiska", "mer typisk", "mest typisk"),
    "recept": make_noun("ett"),
    "kryssa över": make_verb(True, "kryssa över", "kryssar över", "kryssade över", "kryssat över", "kryssad över"),
    "mintgrön": make_adj("mintgrön", "mintgrönt", "mintgröna", "mer mintgrön", "mest mintgrön"),
    "högkonjunktur": make_noun("en"),
    "oerhörd": make_adj("oerhörd", "oerhört", "oerhörda", "mer oerhörd", "mest oerhörd"),
    "fabrik": make_noun("en"),
    "stänga": make_verb(True, "stäng", "stänger", "stängde", "stängt", "stängd"),
    "cd-skiva": make_noun("en"),
    "konkurrera": make_verb(True, "konkurrera", "konkurrerar", "konkurrerade", "konkurrerat", "konkurrerad"),
    "vinylskiva": make_noun("en"),
    "allvarlig": make_adj("allvarlig", "allvarligt", "allvarliga", "allvarligare", "allvarligast"),
    "kärnkraftsolycka": make_noun("en"),
    "inträffa": make_verb(True, "inträffa", "inträffar", "inträffade", "inträffat", "inträffad"),
    "stadsminister": make_noun("en"),
    "skjuten": make_adj("skjuten", "skjutet", "skjutna", "mer skjuten", "mest skjuten"),
    "uppmana": make_verb(True, "uppmana", "uppmanar", "uppmanade", "uppmanat", "uppmanad"),
    "arbetarfamilj": make_noun("en"),
    "avlopp": make_noun("ett"),
    "elektricitet": make_noun("en"),
    "demonstration": make_noun("en"),
    "skjuta ihjäl": make_verb(False, "skjut ihjäl", "skjuter ihjäl", "sköt ihjäl", "skjutit ihjäl", "skjuten ihjäl"),
    "arbetare": make_noun("en"),
    "arbetsgivare": make_noun("en"),
    "fack": make_noun("ett"),
    "arbetsvillkor": make_noun("ett"),
    "avtal": make_noun("ett"),
    "preventivmedel": make_noun("ett"),
    "avskeda": make_verb(True, "avskeda", "avskedar", "avskedade", "avskedat", "avskedad"),
    "grannland": make_noun("ett"),
    "berättelse": make_noun("en"),
    "Pippi Långstrump": make_noun("en")
}

meta_45 = {
    "jättestark": make_adj("jättestark", "jättestarkt", "jättestarka", "jättestarkare", "jättestarkast"),
    "rik som ett troll": make_adj("rik som ett troll", "rikt som ett troll", "rika som ett troll", "rikare som ett troll", "rikast som ett troll"),
    "livmedelsföretag": make_noun("ett"),
    "radiosändning": make_noun("en"),
    "förbund": make_noun("ett"),
    "ordförande": make_noun("en"),
    "varning": make_noun("en"),
    "infektionssjukdom": make_noun("en"),
    "kust": make_noun("en"),
    "spritförbud": make_noun("ett"),
    "omröstning": make_noun("en"),
    "riksdagsledamot": make_noun("en"),
    "högvarv": make_noun("ett"),
    "vardagsrum": make_noun("ett"),
    "nyhetsprogram": make_noun("ett"),
    "aktuell": make_adj("aktuell", "aktuellt", "aktuella", "mer aktuell", "mest aktuell"),
    "globalisering": make_noun("en"),
    "resmål": make_noun("ett"),
    "längre bort": make_adj("längre bort", "längre bort", "längre bort", "mer längre bort", "mest längre bort"),
    "kaffe latte": make_noun("en"),
    "giantisk": make_adj("gigantisk", "gigantiskt", "gigantiska", "mer gigantisk", "mest gigantisk"),
    "kön": make_noun("en"),
    "ingå partnerskap": make_verb(False, "ingå partnerskap", "ingår partnerskap", "ingick partnerskap", "ingått partnerskap", None),
    "diskriminering": make_noun("en"),
    "arbetsliv": make_noun("ett"),
    "sexuell läggning": make_noun("en"),
    "passagerarfärja": make_noun("en"),
    "drunkna": make_verb(True, "drunkna", "druknar", "druknade", "druknat", "druknad"),
    "få problem": make_verb(False, "få problem", "får problem", "fick problem", "fått problem", None),
    "oljekris": make_noun("en"),
    "kommuism": make_noun("en"),
    "miljörörelse": make_noun("en"),
    "gröna vågen": make_noun("en"),
    "demonstrera": make_verb(True, "demonstrera", "demonstrerar", "demonstrerade", "demonstrerat", "demonstrerad"),
    "samhälle": make_noun("ett"),
    "popgrupp": make_noun("en"),
    "slå igenom": make_verb(False, "slå igenom", "slår igenom", "slog igenom", "slagit igenom", None),
    "punkmusik": make_noun("en"),
    "Socialstyrelsen": make_noun("en"),
    "klassa": make_verb(True, "klassa", "klassars", "klassade", "klassat", "klassad"),
    "tronföljd": make_noun("en"),
    "abort": make_noun("en"),
    "miljö- och klimatdebatt": make_noun("en"),
    "ta fart": make_verb(False, "ta fart", "tar fart", "tog fart", "tagit fart", None),
    "producerad": make_adj("producerad", "producerat", "producerade", "mer producerad", "mest producerad"),
    "närodlad": make_adj("närodlad", "närodlat", "närodlade", "mer närodlad", "mest närodlad"),
    "matlagning": make_noun("en"),
    "bygga ut": make_verb(True, "bygg ut", "bygger ut", "byggde ut", "byggt ut", "byggd ut"),
    "bredband": make_noun("ett"),
    "blogga": make_verb(True, "blogga", "bloggar", "bloggade", "bloggat", "bloggad")
}

meta_46 = {
    "smart mobil": make_noun("en"),
    "samkönad": make_adj("samkönad", "samkönat", "samkönade", "mer samkönad", "mest samkönad"),
    "förbud": make_noun("ett"),
    "hets mot folkgrupp": make_noun("en"),
    "folkomröstning": make_noun("en"),
    "knivmördad": make_adj("knivmördad", "knivmördat", "knivmördade", "mer knivmördad", "mest knivmördad"),
    "varuhus": make_noun("ett"),
    "artist": make_noun("en"),
    "framgångsrik": make_adj("framgångsrik", "framgångsrikt", "framgångsrika", "framgångsrikare", "framgångsrikast"),
    "stå i centrum": make_verb(False, "stå i centrum", "står i centrum", "stod i centrum", "stått i centrum", None),
    "trendig": make_adj("trendig", "trendigt", "trendiga", "trendigare", "trendigast"),
    "nyans": make_noun("en"),
    "chockrosa": make_adj("chockrosa", "chockrosa", "chockrosa", "mer chockrosa", "mest chockrosa"),
    "bli slagen": make_verb(False, "bli slagen", "blir slagen", "blev slagen", "blivit slagen", None),
    "mor": make_noun("en"),
    "drabba": make_verb(True, "drabba", "drabbar", "drabbade", "drabbat", "drabbad"),
    "trygga sin framtid": make_verb(True, "trygga din framtid", "tryggar sin framtid", "tryggade sin framtid", "tryggat sin framtid", None),
    "tron": make_noun("en"),
    "adoptera": make_verb(True, "adoptera", "adopterar", "adopterade", "adopterat", "adopterad"),
    "systerdotter": make_noun("en"),
    "byta namn": make_verb(True, "byt namn", "byter namn", "bytte namn", "bytt namn", None),
    "kröna": make_verb(True, "krön", "kröner", "krönte", "krönt", "krönt"),
    "hinna med": make_verb(False, "hinn med", "hinner med", "hann med", "hunnit med", "hunnen med"),
    "hjärtlös": make_adj("hjärtlös", "hjärtlöst", "hjärtlösa", "hjärtlösare", "hjärtlösast"),
    "byxlös": make_adj("byxlös", "byxlöst", "byxlösa", "byxlösare", "byxlösast"),
    "nordisk": make_adj("nordisk", "nordiskt", "nordiska", "mer nordisk", "mest nordisk"),
    "ändra": make_verb(True, "ändra", "ändrar", "ändrade", "ändrat", "ändrad"),
    "trosinriktning": make_noun("en"),
    "lära": make_noun("en"),
    "hårig": make_adj("hårig", "hårigt", "håriga", "hårigare", "hårigast"),
    "besviken": make_adj("besviken", "besviket", "besvikna", "mer besviken", "mest besviken"),
    "deprimerad": make_adj("deprimerad", "deprimerat", "deprimerade", "mer deprimerad", "mest deprimerad"),
    "festlighet": make_noun("en"),
    "vagn": make_noun("en"),
    "dragen av sex hästar": make_adj("dragen av sex hästar", "draget av sex hästar", "dragna av sex hästar", "mer dragen av sex hästar", "mest dragen av sex hästar"),
    "slott": make_noun("ett"),
    "bjuda in": make_verb(False, "bjud in", "bjuder in", "bjöd in", "bjudit in", "bjuden in"),
    "vetenskapsman": make_noun("en"),
    "lunginflammation": make_noun("en"),
    "ta kontakt med": make_verb(False, "ta kontakt med", "tar kontakt med", "tog kontakt med", "tagit kontakt med", None),
    "katolik": make_noun("en"),
    "gömma": make_verb(True, "göm", "gömmer", "gömde", "gömt", "gömd"),
    "abdikation": make_noun("en"),
    "söderut": make_adj("söderut", "söderut", "söderut", "söderut", "söderut"),
    "officiell": make_adj("officiell", "officiellt", "officiella", "mer officiell", "mest officiell"),
    "mottagande": make_noun("ett"),
    "påve": make_noun("en"),
    "kardinal": make_noun("en"),
    "ankomst": make_noun("en"),
    "sångare": make_noun("en")
}

meta_47 = {
    "trivas": make_verb(True, "trivs", "trivs", "trivdes", "trivts", None),
    "apelsinträd": make_noun("ett"),
    "påfågel": make_noun("en"),
    "titta ut över": make_verb(True, "titta ut över", "tittar ut över", "tittade ut över", "tittat ut över", None),
    "kulle": make_noun("en"),
    "vara borta": make_verb(False, "var borta", "är borta", "var borta", "varit borta", None),
    "sorg": make_noun("en"),
    "meddela": make_verb(True, "meddela", "meddelar", "meddelade", "meddelat", "meddelad"),
    "ungdomskultur": make_noun("en"),
    "charterresenär": make_noun("en"),
    "landa": make_verb(True, "landa", "landar", "landade", "landat", "landad"),
    "mellanlandning": make_noun("en"),
    "snabbkurs": make_noun("en"),
    "serie": make_noun("en"),
    "kriga": make_verb(True, "kriga", "krigar", "krigade", "krigat", "krigad"),
    "grunda": make_verb(True, "grunda", "grundar", "grundade", "grundat", "grundad"),
    "födas": make_verb(True, "föds", "föds", "föddes", "fötts", "född"),
    "lutheransk": make_adj("lutheransk", "lutheranskt", "lutheranska", "mer lutheransk", "mest lutheransk"),
    "abdikera": make_verb(True, "abdikera", "abdikerar", "abdikerade", "abdikerat", "abdikerad"),
    "rista": make_verb(True, "rista", "ristar", "ristade", "ristat", "ristad"),
    "skepp": make_noun("ett"),
    "stenhäll": make_noun("en"),
    "verktyg": make_noun("ett"),
    "brons": make_noun("en"),
    "långbåt": make_noun("en"),
    "kristendom": make_noun("en"),
    "is": make_noun("en"),
    "föregående": make_adj("föregående", "föregående", "föregående", "mer föregående", "mest föregående"),
    "århundrade": make_noun("ett"),
    "sekel": make_noun("ett"),
    "regerande": make_adj("regerande", "regerande", "regerande", "mer regerande", "mest regerande"),
    "känna igen": make_verb(True, "känn igen", "känner igen", "kände igen", "känt igen", "känd igen"),
    "lämna över": make_verb(True, "lämna över", "lämnar över", "lämnade över", "lämnat över", "lämnad över"),
    "vara duktig på": make_verb(False, "var duktig på", "är duktig på", "var duktig på", "varit duktig på", None),
    "matematik": make_noun("en"),
    "astronomi": make_noun("en"),
    "uppfostras": make_verb(True, "uppfostras", "uppfostras", "uppfostrades", "uppfostrats", "uppfostrad"),
    "vara smittad av": make_verb(False, "var smittad av", "är smittad av", "var smittad av", "varit smittad av", None),
    "pesten": make_noun("en"),
    "tänka tillbaka": make_verb(True, "tänk tillbaka", "tänker tillbaka", "tänkte tillbaka", "tänkt tillbaka", None),
    "far": make_noun("en"),
    "uppfostra": make_verb(True, "uppfostra", "uppfostrar", "uppfostrade", "uppfostrat", "uppfostrad"),
    "dotter": make_noun("en"),
    "helig": make_adj("helig", "heligt", "heliga", "heligare", "heligast"),
    "tänkt": make_adj("tänkt", "tänkt", "tänkta", "mer tänkt", "mest tänkt"),
    "tempus": make_noun("ett"),
    "förändras": make_verb(True, "förändras", "förändras", "förändrades", "förändrats", None),
    "ha planer": make_verb(False, "ha planer", "har planer", "hade planer", "haft planer", None),
    "filosofera": make_verb(True, "filosofera", "filosoferar", "filosoferade", "filosoferat", "filosoferad"),
    "tidsschema": make_noun("ett")
}

meta_48 = {
    "ringa på": make_verb(True, "ring på", "ringer på", "ringde på", "ringt på", None),
    "telefon": make_noun("en"),
    "sätta på datorn": make_verb(False, "sätt på datorn", "sätter på datorn", "satte på datorn", "satt på datorn", None),
    "kusin": make_noun("en"),
    "Norden": make_noun("ett"),
    "nordbo": make_noun("en"),
    "bosätta sig": make_verb(False, "bosätt dig", "bosätter sig", "bosatte sig", "bosatt sig", "bosatt"),
    "språkfamilj": make_noun("en"),
    "kulturella band": make_noun("ett"),
    "frid och fröjd": make_noun("en"),
    "maktkamp": make_noun("en"),
    "uppbrott": make_noun("ett"),
    "rysk": make_adj("rysk", "ryskt", "ryska", "mer rysk", "mest rysk"),
    "fortsatt": make_adj("fortsatt", "fortsatt", "fortsatta", "mer fortsatt", "mest fortsatt"),
    "passfrihet": make_noun("en"),
    "språkkonvention": make_noun("en"),
    "modersmål": make_noun("ett"),
    "färöiska": make_noun("en"),
    "isländska": make_noun("en"),
    "germanska": make_noun("en"),
    "indoeuropeiska": make_noun("en"),
    "utveckla": make_verb(True, "utveckla", "utvecklar", "utvecklade", "utvecklat", "utvecklad"),
    "urnordiska": make_noun("en"),
    "samiska": make_noun("en"),
    "finsk-ugriska": make_noun("en"),
    "ungerska": make_noun("en"),
    "estniska": make_noun("en"),
    "grönländska": make_noun("en"),
    "nära släkt": make_adj("nära släkt", "nära släkt", "nära släkt", "mer nära släkt", "mest nära släkt"),
    "inuitspråk": make_noun("ett"),
    "anse": make_verb(False, "ansedd", "anser", "ansåg", "ansett", "ansedd"),
    "arv": make_noun("ett"),
    "skriva under": make_verb(False, "skriv under", "skriver under", "skrev under", "skrivit under", "skriven under"),
    "dokument": make_noun("ett"),
    "underteckna": make_verb(True, "underteckna", "undertecknar", "undertecknade", "undertecknat", "undertecknad"),
    "frihetstiden": make_noun("en"),
    "välgörenhet": make_noun("en"),
    "praktisera": make_verb(True, "praktisera", "praktiserar", "praktiserade", "praktiserat", "praktiserad"),
    "utrikesdepartement": make_noun("ett"),
    "handikapp": make_noun("ett"),
    "funktionshindrad": make_adj("funktionshindrad", "funktionshindrat", "funktionshindrade", "mer funktionshindrad", "mest funktionshindrad"),
    "idrotta": make_verb(True, "idrotta", "idrottar", "idrottade", "idrottat", "idrottad"),
    "vara tillsammans": make_verb(False, "var tillsammans", "är tillsammans", "var tillsammans", "varit tillsammans", None),
    "personlig tränare": make_noun("en"),
    "sätta i": make_verb(False, "sätt i", "sätter i", "satte i", "satt i", "satt i"),
    "förskola": make_noun("en"),
    "golfspelare": make_noun("en"),
    "ligga i släkten": make_verb(False, "ligg i släkten", "ligger i släkten", "låg i släkten", "legat i släkten", None),
    "farbror": make_noun("en"),
    "utbildad inom": make_adj("utbildad inom", "utbildat inom", "utbildade inom", "mer utbildad inom", "mest utbildad inom")
}

meta_49 = {
    "grafisk formgivning": make_noun("en"),
    "motorsport": make_noun("en"),
    "rally": make_noun("ett"),
    "juridik": make_noun("en"),
    "engagera sig i": make_verb(True, "engagera dig i", "engagerar sig i", "engagerade sig i", "engagerat sig i", "engagerad"),
    "valspråk": make_noun("ett"),
    "vishet": make_noun("en"),
    "rike": make_noun("ett"),
    "stöd": make_noun("ett"),
    "hopp": make_noun("ett"),
    "förekomma": make_verb(False, "förekom", "förekommer", "förekom", "förekommit", "förekommen"),
    "skvallertidning": make_noun("en"),
    "skvallra": make_verb(True, "skvallra", "skvallrar", "skvallrade", "skvallrat", "skvallrad"),
    "ge respons": make_verb(False, "ge respons", "ger respons", "gav respons", "givit respons", None),
    "väcka intresse": make_verb(True, "väck intresse", "väcker intresse", "väckte intresse", "väckt intresse", "väckt intresse"),
    "faktoid": make_noun("en"),
    "skröna": make_noun("en"),
    "faktum": make_noun("ett"),
    "osanning": make_noun("en"),
    "halvsanning": make_noun("en"),
    "missuppfattning": make_noun("en"),
    "bevisa": make_verb(True, "bevisa", "bevisar", "bevisade", "bevisat", "bevisad"),
    "felaktig": make_adj("felaktig", "felaktigt", "felaktiga", "mer felaktig", "mest felaktig"),
    "sprida": make_verb(False, "sprid", "sprider", "spred", "spritt", "spridd"),
    "massmedium": make_noun("ett"),
    "guldfisk": make_noun("en"),
    "kramp": make_noun("en"),
    "tidningsartikel": make_noun("en"),
    "springa runt": make_verb(False, "spring runt", "springer runt", "sprang runt", "sprungit runt", "sprungen runt"),
    "toppen": make_noun("en"),
    "erfarenhet": make_noun("en"),
    "värdering": make_noun("en"),
    "reinkarnation": make_noun("en"),
    "vandringshistoria": make_noun("en"),
    "påminna om": make_verb(True, "påminn om", "påminner om", "påminde om", "påmint om", "påmind om"),
    "folksaga": make_noun("en"),
    "bestämd": make_adj("bestämd", "bestämt", "bestämda", "bestämdare", "bestämdast"),
    "hävda": make_verb(True, "hävda", "hävdar", "hävdade", "hävdat", "hävdad"),
    "leva vidare": make_verb(True, "lev vidare", "lever vidare", "levde vidare", "levt vidare", None),
    "underhållande": make_adj("underhållande", "underhållande", "underhållande", "mer underhållande", "mest underhållande"),
    "vardaglig": make_adj("vardaglig", "vardagligt", "vardagliga", "vardagligare", "vardagligast"),
    "underlig": make_adj("underlig", "underligt", "underliga", "underligare", "underligast"),
    "aspekt": make_noun("en"),
    "varna för": make_verb(True, "varna för", "varnar för", "varnade för", "varnat för", "varnad för"),
    "pudel": make_noun("en"),
    "mikro": make_noun("en"),
    "råka": make_verb(True, "råka", "råkar", "råkade", "råkat", "råkad"),
    "explodera": make_verb(True, "explodera", "exploderar", "exploderade", "exploderat", "exploderad"),
    "sätta på": make_verb(False, "sätt på", "sätter på", "satte på", "satt på", "satt på"),
    "dam": make_noun("en")
}

meta_50 = {
    "lift": make_noun("en"),
    "yxa": make_noun("en"),
    "minoritet": make_noun("en"),
    "finlandssvensk": make_noun("en"),
    "tvinga": make_verb(True, "tvinga", "tvingar", "tvingade", "tvingat", "tvingad"),
    "norrman": make_noun("en"),
    "ligga nära varandra": make_verb(False, "ligg nära varandra", "ligger nära varandra", "låg nära varandra", "legat nära varandra", None),
    "by": make_noun("en"),
    "anledning": make_noun("en"),
    "datakurs": make_noun("en"),
    "folkhögskola": make_noun("en"),
    "beställa tid": make_verb(True, "beställ tid", "beställer tid", "beställde tid", "beställt tid", None),
    "återbesök": make_noun("ett"),
    "laga": make_verb(True, "laga", "lagar", "lagade", "lagat", "lagad"),
    "bortrest": make_adj("bortrest", "bortrest", "bortresta", "mer bortrest", "mest bortrest"),
    "nästnästa": make_adj("nästnästa", "nästnästa", "nästnästa", "mer nästnästa", "mest nästnästa"),
    "skicka in": make_verb(True, "skicka in", "skickar in", "skickade in", "skickat in", "skickad in"),
    "deklaration": make_noun("en"),
    "deklarera": make_verb(True, "deklarera", "deklarerar", "deklarerade", "deklarerat", "deklarerad"),
    "påminna": make_verb(True, "påminn", "påminner", "påminde", "påmint", "påmind"),
    "fascinerande": make_adj("fascinerande", "fascinerande", "fascinerande", "mer fascinerande", "mest fascinerande"),
    "bortglömd": make_adj("bortglömd", "bortglömt", "bortglömda", "mer bortglömd", "mest bortglömd"),
    "uppfinna": make_verb(False, "uppfinn", "uppfinner", "uppfann", "uppfunnit", "uppfunnen"),
    "klocka": make_noun("en"),
    "prisnivå": make_noun("en"),
    "reducera": make_verb(True, "reducera", "reducerar", "reducerade", "reducerat", "reducerad"),
    "lögn": make_noun("en"),
    "snöboll": make_noun("en"),
    "rulla": make_verb(True, "rulla", "rullar", "rullade", "rullat", "rullad"),
    "bör": make_verb(False, "bör", "bör", "borde", "bort", None),
    "lögnare": make_noun("en"),
    "tala sanning": make_verb(True, "tala sanning", "talar sanning", "talade sanning", "talat sanning", None),
    "lita på": make_verb(True, "lita på", "litar på", "litade på", "litat på", "litad på"),
    "minne": make_noun("ett"),
    "acceptabel": make_adj("acceptabel", "acceptabelt", "acceptabla", "mer acceptabel", "mest acceptabel"),
    "gå fri": make_verb(False, "gå fri", "går fri", "gick fri", "gått fri", None),
    "gå på restaurang": make_verb(False, "gå på restaurang", "går på restaurang", "gick på restaurang", "gått på restaurang", None),
    "göra något dumt": make_verb(False, "gör något dumt", "gör något dumt", "gjorde något dumt", "gjort något dumt", None),
    "söka jobb": make_verb(True, "sök jobb", "söker jobb", "sökte jobb", "sökt jobb", None),
    "full med": make_adj("full med", "fullt med", "fulla med", "fullare med", "fullast med"),
    "hundrakronorssedel": make_noun("en"),
    "cirkus": make_noun("en"),
    "anställd": make_adj("anställd", "anställt", "anställda", "mer anställd", "mest anställd"),
    "kontormaterial": make_noun("ett"),
    "realisation": make_noun("en"),
    "plånbok": make_noun("en"),
    "lillebror": make_noun("en"),
    "låta bli": make_verb(False, "låt bli", "låter bli", "lät bli", "låtit bli", None),
    "extrapris": make_noun("ett"),
    "förvånansvärd": make_adj("förvånansvärd", "förvånansvärt", "förvånansvärda", "mer förvånansvärd", "mest förvånansvärd")
}

meta_51 = {
    "omedveten": make_adj("omedveten", "omedvetet", "omedvetna", "mer omedveten", "mest omedveten"),
    "oskyldig": make_adj("oskyldig", "oskyldigt", "oskyldiga", "oskyldigare", "oskyldigast"),
    "dölja": make_verb(False, "dölj", "döljer", "dolde", "dolt", "dold"),
    "belöning": make_noun("en"),
    "har inte något emot": make_verb(False, "ha inte något emot", "har inte något emot", "hade inte något emot", "haft inte något emot", None),
    "straff": make_noun("ett"),
    "avslöja": make_verb(True, "avslöja", "avslöjar", "avslöjade", "avslöjat", "avslöjad"),
    "känna skuld": make_verb(True, "känn skuld", "känner skuld", "kände skuld", "känt skuld", None),
    "luras": make_verb(True, "luras", "luras", "lurades", "lurats", None),
    "svimma": make_verb(True, "svimma", "svimmar", "svimmade", "svimmat", "svimmad"),
    "snatta": make_verb(True, "snatta", "snattar", "snattade", "snattat", "snattad"),
    "kyckling": make_noun("en"),
    "fatta": make_verb(True, "fatta", "fattar", "fattade", "fattat", "fattad"),
    "hjärna": make_noun("en"),
    "förvåning": make_noun("en"),
    "skepsis": make_noun("en"),
    "lös": make_adj("lös", "löst", "lösa", "lösare", "lösast"),
    "springa lös": make_verb(False, "spring lös", "springer lös", "sprang lös", "sprungit lös", None),
    "bur": make_noun("en"),
    "skrämd": make_adj("skrämd", "skrämt", "skrämda", "mer skrämd", "mest skrämd"),
    "hålla reda på": make_verb(False, "håll reda på", "håller reda på", "höll reda på", "hållit reda på", "hållen reda på"),
    "nyinflyttad": make_adj("nyinflyttad", "nyinflyttat", "nyinflyttade", "mer nyinflyttad", "mest nyinflyttad"),
    "koppla": make_verb(True, "koppla", "kopplar", "kopplade", "kopplat", "kopplad"),
    "hålla kopplad": make_verb(False, "håll kopplad", "håller kopplad", "höll kopplad", "hållit kopplad", "hållen kopplad"),
    "jordig": make_adj("jordig", "jordigt", "jordiga", "jordigare", "jordigast"),
    "göra fin": make_verb(False, "gör fin", "gör fin", "gjorde fin", "gjort fin", "gjord fin"),
    "blåsa torr": make_verb(True, "blås torr", "blåser torr", "blåste torr", "blåst torr", "blåst torr"),
    "hårtork": make_noun("en"),
    "smyga": make_verb(False, "smyg", "smyger", "smög", "smugit", "smugen"),
    "stendöd": make_adj("stendöd", "stendött", "stendöda", "mer stendöd", "mest stendöd"),
    "undvika": make_verb(False, "undvik", "undviker", "undvek", "undvikit", "undviken"),
    "älskad": make_adj("älskad", "älskat", "älskade", "mer älskad", "mest älskad"),
    "begrava": make_verb(False, "begrav", "begraver", "begravde", "begravt", "begravd"),
    "skinande": make_adj("skinande", "skinande", "skinande", "mer skinande", "mest skinande"),
    "fräsig": make_adj("fräsig", "fräsigt", "fräsiga", "fräsigare", "fräsigast"),
    "sportbil": make_noun("en"),
    "saknas": make_verb(True, "saknas", "saknas", "saknades", "saknats", None),
    "nolla": make_noun("en"),
    "skick": make_noun("ett"),
    "äktenskap": make_noun("ett"),
    "sticka iväg": make_verb(False, "stick iväg", "sticker iväg", "stack iväg", "stuckit iväg", None),
    "sekreterare": make_noun("en"),
    "knäppt": make_adj("knäppt", "knäppt", "knäppta", "mer knäppt", "mest knäppt"),
    "möta blicken": make_verb(True, "möt blicken", "möter blicken", "mötte blicken", "mött blicken", None),
    "tendens": make_noun("en"),
    "ljusare": make_adj("ljus", "ljust", "ljusa", "ljusare", "ljusast"),
    "kortfattad": make_adj("kortfattad", "kortfattat", "kortfattade", "mer kortfattad", "mest kortfattad"),
    "detalj": make_noun("en"),
    "synas": make_verb(True, "syns", "syns", "syntes", "synts", None),
    "strömma": make_verb(True, "strömma", "strömmar", "strömmade", "strömmat", "strömmad")
}

meta_52 = {
    "näsa": make_noun("en"),
    "leda till att": make_verb(True, "led till att", "leder till att", "ledde till att", "lett till att", None),
    "röd": make_adj("röd", "rött", "röda", "rödare", "rödast"),
    "klia": make_verb(True, "klia", "kliar", "kliade", "kliat", "kliad"),
    "kroppsspråk": make_noun("ett"),
    "knep": make_noun("ett"),
    "upprepa": make_verb(True, "upprepa", "upprepar", "upprepade", "upprepat", "upprepad"),
    "pupill": make_noun("en"),
    "flyta på": make_verb(False, "flyt på", "flyter på", "flöt på", "flutit på", None),
    "komma överens": make_verb(False, "kom överens", "kommer överens", "kom överens", "kommit överens", None),
    "lägst": make_adj("låg", "lågt", "låga", "lägre", "lägst"),
    "temperatur": make_noun("en"),
    "uppmäta": make_verb(True, "uppmät", "uppmäter", "uppmätte", "uppmätt", "uppmätt"),
    "grad": make_noun("en"),
    "byggnadsprojekt": make_noun("ett"),
    "sluss": make_noun("en"),
    "spanske": make_adj("spansk", "spanskt", "spanska", "mer spansk", "mest spansk"),
    "kvadratkilometer": make_noun("en"),
    "längst": make_adj("lång", "långt", "långa", "längre", "längst"),
    "folkmängd": make_noun("en"),
    "nöjespark": make_noun("en"),
    "berg -och dalbana": make_noun("en"),
    "trä": make_noun("ett"),
    "backe": make_noun("en"),
    "fallvinkel": make_noun("en"),
    "däggdjur": make_noun("ett"),
    "sedd": make_adj("sedd", "sett", "sedda", "mer sedd", "mest sedd"),
    "verka vara": make_verb(True, "verka vara", "verkar vara", "verkade vara", "verkat vara", None),
    "skam": make_noun("en"),
    "vit lögn": make_noun("en"),
    "nödvändig": make_adj("nödvändig", "nödvändigt", "nödvändiga", "mer nödvändig", "mest nödvändig"),
    "otrevlig": make_adj("otrevlig", "otrevligt", "otrevliga", "otrevligare", "otrevligast"),
    "smaka illa": make_verb(True, "smaka illa", "smakar illa", "smakade illa", "smakat illa", None),
    "frisyr": make_noun("en"),
    "skämt": make_noun("ett"),
    "snabbtänkt": make_adj("snabbtänkt", "snabbtänkt", "snabbtänkta", "mer snabbtänkt", "mest snabbtänkt"),
    "psykopat": make_noun("en"),
    "kontrollerad": make_adj("kontrollerad", "kontrollerat", "kontrollerade", "mer kontrollerad", "mest kontrollerad"),
    "aprilskämt": make_noun("ett"),
    "seriös": make_adj("seriös", "seriöst", "seriösa", "seriösare", "seriösast"),
    "dagstidning": make_noun("en"),
    "publicera": make_verb(True, "publicera", "publicerar", "publicerade", "publicerat", "publicerad"),
    "färgteve": make_noun("en"),
    "sönder": make_adj("sönder", "sönder", "sönder", "mer sönder", "mest sönder"),
    "strumpa": make_noun("en"),
    "prova": make_verb(True, "prova", "provar", "provade", "provat", "provad"),
    "medveten": make_adj("medveten", "medvetet", "medvetna", "mer medveten", "mest medveten"),
    "ta till en lögn": make_verb(False, "ta till en lögn", "tar till en lögn", "tog till en lögn", "tagit till en lögn", None),
    "begå": make_verb(False, "begå", "begår", "begick", "begått", "begången"),
    "beundra": make_verb(True, "beundra", "beundrar", "beundrade", "beundrat", "beundrad")
}

meta_53 = {
    "idrottsstjärna": make_noun("en"),
    "mytoman": make_noun("en"),
    "osannolik": make_adj("osannolik", "osannolikt", "osannolika", "mer osannolik", "mest osannolik"),
    "kanonkula": make_noun("en"),
    "armé": make_noun("en"),
    "strida": make_verb(True, "strid", "strider", "stridde", "stridit", "stridd"),
    "orsak": make_noun("en"),
    "syndrom": make_noun("ett"),
    "simulera": make_verb(True, "simulera", "simulerar", "simulerade", "simulerat", "simulerad"),
    "omhändertagen": make_adj("omhändertagen", "omhändertaget", "omhändertagna", "mer omhändertagen", "mest omhändertagen"),
    "få vård": make_verb(False, "få vård", "får vård", "fick vård", "fått vård", None),
    "flacka med blicken": make_verb(True, "flacka med blicken", "flackar med blicken", "flackade med blicken", "flackat med blicken", None),
    "domare": make_noun("en"),
    "försöksperson": make_noun("en"),
    "forkning": make_noun("en"),
    "proffs": make_noun("ett"),
    "van vid": make_adj("van vid", "vant vid", "vana vid", "vanare vid", "vanast vid"),
    "skruva på sig": make_verb(True, "skruva dig på", "skruvar på sig", "skruvade på sig", "skruvat på sig", None),
    "blick": make_noun("en"),
    "hålla": make_verb(False, "håll", "håller", "höll", "hållit", "hållen"),
    "beteende": make_noun("ett"),
    "hyra": make_noun("en"),
    "stuga": make_noun("en"),
    "lockad": make_adj("lockad", "lockat", "lockade", "mer lockad", "mest lockad"),
    "symbolisera": make_verb(True, "symbolisera", "symboliserar", "symboliserade", "symboliserat", "symboliserad"),
    "orörd": make_adj("orörd", "orört", "orörda", "mer orörd", "mest orörd"),
    "hantverk": make_noun("ett"),
    "fiol": make_noun("en"),
    "japan": make_noun("en"),
    "engelsman": make_noun("en"),
    "resenär": make_noun("en"),
    "hektisk": make_adj("hektisk", "hektiskt", "hektiska", "mer hektisk", "mest hektisk"),
    "logga ut": make_verb(True, "logga ut", "loggar ut", "loggade ut", "loggat ut", "loggad ut"),
    "avkoppling": make_noun("en"),
    "flyta med": make_verb(False, "flyt med", "flyter med", "flöt med", "flutit med", None),
    "flod": make_noun("en"),
    "utlänning": make_noun("en"),
    "hjälte": make_noun("en"),
    "dra": make_verb(False, "dra", "drar", "drog", "dragit", "dragen"),
    "kommissarie": make_noun("en"),
    "sovrum": make_noun("ett"),
    "vattenyta": make_noun("en"),
    "arkitektur": make_noun("en"),
    "sevärdhet": make_noun("en"),
    "ha gott om": make_verb(False, "ha gott om", "har gott om", "hade gott om", "haft gott om", None),
    "guldkant": make_noun("en"),
    "sätta guldkant på": make_verb(False, "sätt guldkant på", "sätter guldkant på", "satte guldkant på", "satt guldkant på", None),
    "vistelse": make_noun("en"),
    "exklusiv": make_adj("exklusiv", "exklusivt", "exklusiva", "exklusivare", "exklusivast"),
    "beräkna": make_verb(True, "beräkna", "beräknar", "beräknade", "beräknat", "beräknad")
}

meta_54 = {
    "spendera": make_verb(True, "spendera", "spenderar", "spenderade", "spenderat", "spenderad"),
    "miljard": make_noun("en"),
    "följd": make_noun("en"),
    "utsläpp": make_noun("ett"),
    "transport": make_noun("en"),
    "reningsverk": make_noun("ett"),
    "överbelastad": make_adj("överbelastad", "överbelastat", "överbelastade", "mer överbelastad", "mest överbelastad"),
    "miljömedveten": make_adj("miljömedveten", "miljömedvetet", "miljömedvetna", "mer miljömedveten", "mest miljömedveten"),
    "miljövänlig": make_adj("miljövänlig", "miljövänligt", "miljövänliga", "miljövänligare", "miljövänligast"),
    "trädkoja": make_noun("en"),
    "hotellägare": make_noun("en"),
    "inse": make_verb(False, "inse", "inser", "insåg", "insett", "insedd"),
    "hållbarhet": make_noun("en"),
    "miljöcertifierad": make_adj("miljöcertifierad", "miljöcertifierat", "miljöcertifierade", "mer miljöcertifierad", "mest miljöcertifierad"),
    "användbar": make_adj("användbar", "användbart", "användbara", "mer användbar", "mest användbar"),
    "sammansatt": make_adj("sammansatt", "sammansatt", "sammansatta", "mer sammansatt", "mest sammansatt"),
    "kursiverad": make_adj("kursiverad", "kursiverat", "kursiverade", "mer kursiverad", "mest kursiverad"),
    "kant": make_noun("en"),
    "dektektiv": make_noun("en"),
    "trafikera": make_verb(True, "trafikera", "trafikerar", "trafikerade", "trafikerat", "trafikerad"),
    "passera": make_verb(True, "passera", "passerar", "passerade", "passerat", "passerad"),
    "fordon": make_noun("ett"),
    "superlativ": make_noun("ett"),
    "yngst": make_adj("ung", "ungt", "unga", "yngre", "yngst"),
    "sömnproblem": make_noun("ett"),
    "stressa": make_verb(True, "stressa", "stressar", "stressade", "stressat", "stressad"),
    "uppkopplad": make_adj("uppkopplad", "uppkopplat", "uppkopplade", "mer uppkopplad", "mest uppkopplad")
}

all_metas = {
    38: meta_38, 39: meta_39, 40: meta_40, 41: meta_41, 42: meta_42,
    43: meta_43, 44: meta_44, 45: meta_45, 46: meta_46, 47: meta_47,
    48: meta_48, 49: meta_49, 50: meta_50, 51: meta_51, 52: meta_52,
    53: meta_53, 54: meta_54
}

for c in range(38, 55):
    path = os.path.join(chunks_dir, f"deep_chunk_{c}.json")
    with open(path, "r", encoding="utf-8") as f:
        words = json.load(f)
    meta = all_metas[c]
    missing = [w for w in words if w not in meta]
    extra = [w for w in meta if w not in words]
    print(f"Chunk {c}: words={len(words)}, meta={len(meta)}, missing={len(missing)}, extra={len(extra)}")
    if missing or extra:
        print(f"  Missing: {missing}")
        print(f"  Extra: {extra}")

