import json
import os

chunks_dir = "./course/sfid/phase3/data/chunks"

# Builder helper functions
def make_noun(gender):
    return {
        "word_type": "noun",
        "noun_gender": gender,
        "is_regular_verb": None,
        "verb_imperativ": None,
        "verb_presens": None,
        "verb_preteritum": None,
        "verb_supinum": None,
        "verb_perfekt_particip": None,
        "adj_en": None,
        "adj_ett": None,
        "adj_plural": None,
        "adj_komparativ": None,
        "adj_superlativ": None
    }

def make_verb(is_regular, imp, pres, pret, sup, part=None):
    return {
        "word_type": "verb",
        "noun_gender": None,
        "is_regular_verb": is_regular,
        "verb_imperativ": imp,
        "verb_presens": pres,
        "verb_preteritum": pret,
        "verb_supinum": sup,
        "verb_perfekt_particip": part,
        "adj_en": None,
        "adj_ett": None,
        "adj_plural": None,
        "adj_komparativ": None,
        "adj_superlativ": None
    }

def make_adj(en, ett, pl, komp, sup):
    return {
        "word_type": "adjective",
        "noun_gender": None,
        "is_regular_verb": None,
        "verb_imperativ": None,
        "verb_presens": None,
        "verb_preteritum": None,
        "verb_supinum": None,
        "verb_perfekt_particip": None,
        "adj_en": en,
        "adj_ett": ett,
        "adj_plural": pl,
        "adj_komparativ": komp,
        "adj_superlativ": sup
    }

meta_28 = {
    "peta sig i näsan": make_verb(True, "peta dig i näsan", "petar sig i näsan", "petade sig i näsan", "petat sig i näsan", None),
    "beroende": make_adj("beroende", "beroende", "beroende", "mer beroende", "mest beroende"),
    "sockerberoende": make_noun("ett"),
    "spelberoende": make_noun("ett"),
    "narkotikaberoende": make_noun("ett"),
    "överdriva": make_verb(False, "överdriv", "överdriver", "överdrev", "överdrivit", "överdriven"),
    "teveserie": make_noun("en"),
    "hudkräm": make_noun("en"),
    "missbruka": make_verb(True, "missbruka", "missbrukar", "missbrukade", "missbrukat", "missbrukad"),
    "narkoman": make_noun("en"),
    "sammanhang": make_noun("ett"),
    "arbetsnarkoman": make_noun("en"),
    "träningsnarkoman": make_noun("en"),
    "sugen": make_adj("sugen", "suget", "sugna", "sugnare", "sugnast"),
    "röksugen": make_adj("röksugen", "röksuget", "röksugna", "mer röksugen", "mest röksugen"),
    "fikasugen": make_adj("fikasugen", "fikasuget", "fikasugna", "mer fikasugen", "mest fikasugen"),
    "ressugen": make_adj("ressugen", "ressuget", "ressugna", "mer ressugen", "mest ressugen"),
    "irriterande": make_adj("irriterande", "irriterande", "irriterande", "mer irriterande", "mest irriterande"),
    "ge råd": make_verb(False, "ge råd", "ger råd", "gav råd", "givit råd", None),
    "lantis": make_noun("en"),
    "bästis": make_noun("en"),
    "kåda": make_noun("en"),
    "bortplockad": make_adj("bortplockad", "bortplockat", "bortplockade", "mer bortplockad", "mest bortplockad"),
    "bokstav": make_noun("en"),
    "salt": make_noun("ett"),
    "sill": make_noun("en"),
    "stekt": make_adj("stekt", "stekt", "stekta", "mer stekt", "mest stekt"),
    "mormor": make_noun("en"),
    "ferraribil": make_noun("en"),
    "seg": make_adj("seg", "segt", "sega", "segare", "segast"),
    "delfin": make_noun("en"),
    "familjemiddag": make_noun("en"),
    "hotellfrukost": make_noun("en"),
    "produktchef": make_noun("en"),
    "kiosk": make_noun("en"),
    "lucka": make_noun("en"),
    "krona": make_noun("en"),
    "peka på": make_verb(True, "peka på", "pekar på", "pekade på", "pekat på", "pekad på"),
    "burk": make_noun("en"),
    "plocka ihop": make_verb(True, "plocka ihop", "plockar ihop", "plockade ihop", "plockat ihop", "plockad ihop"),
    "plockgodis": make_noun("ett"),
    "lösvikt": make_noun("en"),
    "mataffär": make_noun("en"),
    "kund": make_noun("en"),
    "tom": make_adj("tom", "tomt", "tomma", "tommare", "tommast"),
    "succé": make_noun("en"),
    "mängd": make_noun("en"),
    "kassa": make_noun("en"),
    "godissort": make_noun("en"),
    "matvarukedja": make_noun("en")
}

meta_29 = {
    "internationell": make_adj("internationell", "internationellt", "internationella", "mer internationell", "mest internationell"),
    "möbelvaruhus": make_noun("ett"),
    "geléfisk": make_noun("en"),
    "fruktsmak": make_noun("en"),
    "välkänd": make_adj("välkänd", "välkänt", "välkända", "mer välkänd", "mest välkänd"),
    "oväntad": make_adj("oväntad", "oväntat", "oväntade", "mer oväntad", "mest oväntad"),
    "texmexprodukt": make_noun("en"),
    "ärta": make_noun("en"),
    "fryst": make_adj("fryst", "fryst", "frysta", "mer fryst", "mest fryst"),
    "tårta": make_noun("en"),
    "skorpa": make_noun("en"),
    "pepparkaka": make_noun("en"),
    "målare": make_noun("en"),
    "kanderad": make_adj("kanderad", "kanderat", "kanderade", "mer kanderad", "mest kanderad"),
    "viol": make_noun("en"),
    "syren": make_noun("en"),
    "bränd": make_adj("bränd", "bränt", "brända", "mer bränd", "mest bränd"),
    "mandel": make_noun("en"),
    "import": make_noun("en"),
    "med tiden": make_noun("en"),
    "styra": make_verb(True, "styr", "styr", "styrde", "styrt", "styrd"),
    "minska": make_verb(True, "minska", "minskar", "minskade", "minskat", "minskad"),
    "valuta": make_noun("en"),
    "sockerbeta": make_noun("en"),
    "odling": make_noun("en"),
    "starta": make_verb(True, "starta", "startar", "startade", "startat", "startad"),
    "startpunkt": make_noun("en"),
    "masstillverkning": make_noun("en"),
    "chokladfabrik": make_noun("en"),
    "karamellkokning": make_noun("en"),
    "torg": make_noun("ett"),
    "änka": make_noun("en"),
    "röd- och vitrandig": make_adj("röd- och vitrandig", "röd- och vitrandigt", "röd- och vitrandiga", "mer röd- och vitrandig", "mest röd- och vitrandig"),
    "förmögen": make_adj("förmögen", "förmöget", "förmögna", "förmögnare", "förmögnast"),
    "källare": make_noun("en"),
    "källarfabrik": make_noun("en"),
    "gatuförsäljare": make_noun("en"),
    "gumma": make_noun("en"),
    "pappersstrut": make_noun("en"),
    "söndagspromenad": make_noun("en"),
    "godisbutik": make_noun("en"),
    "konsumtion": make_noun("en"),
    "tablettask": make_noun("en"),
    "chokladkaka": make_noun("en"),
    "genombrott": make_noun("ett"),
    "försäljning": make_noun("en"),
    "järnvägsstation": make_noun("en"),
    "få tag på": make_verb(False, "få tag på", "får tag på", "fick tag på", "fått tag på", None),
    "lansera": make_verb(True, "lansera", "lanserar", "lanserade", "lanserat", "lanserad"),
    "pralin": make_noun("en")
}

meta_30 = {
    "pralinask": make_noun("en"),
    "storsäljare": make_noun("en"),
    "storhelg": make_noun("en"),
    "påsk": make_noun("en"),
    "karies": make_noun("en"),
    "faktor": make_noun("en"),
    "tandhälsa": make_noun("en"),
    "skadlig": make_adj("skadlig", "skadligt", "skadliga", "skadligare", "skadligast"),
    "kampanj": make_noun("en"),
    "polkagris": make_noun("en"),
    "turist": make_noun("en"),
    "handla": make_verb(True, "handla", "handlar", "handlade", "handlat", "handlad"),
    "tand": make_noun("en"),
    "lördagsgodis": make_noun("ett"),
    "sprida sig": make_verb(False, "sprid dig", "sprider sig", "spred sig", "spritt sig", "spridd"),
    "leva kvar": make_verb(True, "lev kvar", "lever kvar", "levde kvar", "levt kvar", "levd"),
    "karamell": make_noun("en"),
    "medicinsk": make_adj("medicinsk", "medicinskt", "medicinska", "mer medicinsk", "mest medicinsk"),
    "hålla ren": make_verb(False, "håll ren", "håller ren", "höll ren", "hållit ren", "hållen"),
    "dyr": make_adj("dyr", "dyrt", "dyra", "dyrare", "dyrast"),
    "produkt": make_noun("en"),
    "sötsak": make_noun("en"),
    "gräddkola": make_noun("en"),
    "kokosboll": make_noun("en"),
    "arrangemang": make_noun("ett"),
    "konfekt": make_noun("en"),
    "marsipantårta": make_noun("en"),
    "tugga": make_verb(True, "tugga", "tuggar", "tuggade", "tuggat", "tuggad"),
    "söt": make_adj("söt", "sött", "söta", "sötare", "sötast"),
    "länge sedan": make_adj("länge sedan", "länge sedan", "länge sedan", "mer länge sedan", "mest länge sedan"),
    "honung": make_noun("en"),
    "frukt": make_noun("en"),
    "nöt": make_noun("en"),
    "bit": make_noun("en"),
    "björk": make_noun("en"),
    "tuggmärke": make_noun("ett"),
    "visa sig": make_verb(True, "visa dig", "visar sig", "visade sig", "visat sig", "visad"),
    "tuggummi": make_noun("ett"),
    "tillverka": make_verb(True, "tillverka", "tillverkar", "tillverkade", "tillverkat", "tillverkad"),
    "handel": make_noun("en"),
    "apotekare": make_noun("en"),
    "skillnad": make_noun("en"),
    "krig": make_noun("ett"),
    "militär": make_noun("en"),
    "återvända": make_verb(True, "återvänd", "återvänder", "återvände", "återvänt", "återvänd"),
    "tysk": make_adj("tysk", "tyskt", "tyska", "mer tysk", "mest tysk"),
    "schweizisk": make_adj("schweizisk", "schweiziskt", "schweiziska", "mer schweizisk", "mest schweizisk"),
    "sockerbagare": make_noun("en"),
    "adelsfamilj": make_noun("en"),
    "anställa": make_verb(True, "anställ", "anställer", "anstälde", "anställt", "anställd")
}

meta_31 = {
    "barnbarn": make_noun("ett"),
    "prins": make_noun("en"),
    "prinsessa": make_noun("en"),
    "titel": make_noun("en"),
    "tiderna förändras": make_verb(True, "förändras", "förändras", "förändrades", "förändrats", None),
    "be om lov": make_verb(False, "be om lov", "ber om lov", "bad om lov", "bett om lov", None),
    "statsminister": make_noun("en"),
    "lutherskt kristen": make_adj("lutherskt kristen", "lutherskt kristet", "lutherskt kristna", "mer lutherskt kristen", "mest lutherskt kristen"),
    "vara beredd": make_verb(False, "var beredd", "är beredd", "var beredd", "varit beredd", None),
    "konvertera": make_verb(True, "konvertera", "konverterar", "konverterade", "konverterat", "konverterad"),
    "parlamentarisk": make_adj("parlamentarisk", "parlamentariskt", "parlamentariska", "mer parlamentarisk", "mest parlamentarisk"),
    "demokrati": make_noun("en"),
    "statschef": make_noun("en"),
    "representant": make_noun("en"),
    "makt": make_noun("en"),
    "monarki": make_noun("en"),
    "konstitutionell": make_adj("konstitutionell", "konstitutionellt", "konstitutionella", "mer konstitutionell", "mest konstitutionell"),
    "kungamakt": make_noun("en"),
    "gå i arv": make_verb(False, "gå i arv", "går i arv", "gick i arv", "gått i arv", None),
    "kronprinsessa": make_noun("en"),
    "efterträda": make_verb(True, "efterträd", "efterträder", "efterträdde", "efterträtt", "efterträdd"),
    "behålla": make_verb(False, "behåll", "behåller", "behöll", "behållit", "behållen"),
    "införa": make_verb(True, "inför", "inför", "införde", "infört", "införd"),
    "republik": make_noun("en"),
    "premiärminister": make_noun("en"),
    "kejsardöme": make_noun("ett"),
    "kejsare": make_noun("en"),
    "kejsarinna": make_noun("en"),
    "diktator": make_noun("en"),
    "parlament": make_noun("ett"),
    "parlamentsledamot": make_noun("en"),
    "revisor": make_noun("en"),
    "motor": make_noun("en"),
    "agera": make_verb(True, "agera", "agerar", "agerade", "agerat", "agerad"),
    "stjäla": make_verb(False, "stjäl", "stjäl", "stal", "stulit", "stulen"),
    "ljuga": make_verb(False, "ljug", "ljuger", "ljög", "ljugit", "ljugen"),
    "nära vän": make_noun("en"),
    "slå": make_verb(False, "slå", "slår", "slog", "slagit", "slagen"),
    "summa": make_noun("en"),
    "jättehungrig": make_adj("jättehungrig", "jättehungrigt", "jättehungriga", "jättehungrigare", "jättehungrigast"),
    "övningsbok": make_noun("en"),
    "parti": make_noun("ett"),
    "regering": make_noun("en"),
    "stanna upp": make_verb(True, "stanna upp", "stannar upp", "stannade upp", "stannat upp", "stannad upp"),
    "berättande": make_noun("ett"),
    "händelse": make_noun("en"),
    "utveckling": make_noun("en"),
    "över tid": make_noun("en"),
    "ämne": make_noun("ett"),
    "barndomsminne": make_noun("ett")
}

meta_32 = {
    "farföräldrar": make_noun("en"),
    "morföräldrar": make_noun("en"),
    "pryl": make_noun("en"),
    "i början av …": make_noun("en"),
    "kung": make_noun("en"),
    "kung för en dag": make_noun("en"),
    "sommarjobbare": make_noun("en"),
    "chilla": make_verb(True, "chilla", "chillar", "chillade", "chillat", "chillad"),
    "polare": make_noun("en"),
    "astronom": make_noun("en"),
    "himla": make_verb(True, "himla", "himlar", "himlade", "himlat", "himlad"),
    "kul": make_adj("kul", "kul", "kul", "mer kul", "mest kul"),
    "utlramodern": make_adj("ultramodern", "ultramodernt", "ultramoderna", "mer ultramodern", "mest ultramodern"),
    "teleskop": make_noun("ett"),
    "skolelev": make_noun("en"),
    "konditionalis": make_noun("en"),
    "så många som möjligt": make_adj("så många som möjligt", "så många som möjligt", "så många som möjligt", "mer så många som möjligt", "mest så många som möjligt"),
    "nedan": make_adj("nedan", "nedan", "nedan", "mer nedan", "mest nedan"),
    "osynlig": make_adj("osynlig", "osynligt", "osynliga", "osynligare", "osynligast"),
    "finansminister": make_noun("en"),
    "surströmming": make_noun("en"),
    "köra på": make_verb(True, "kör på", "kör på", "körde på", "kört på", "körd på"),
    "parkering": make_noun("en"),
    "få en chans": make_verb(False, "få en chans", "får en chans", "fick en chans", "fått en chans", None),
    "måne": make_noun("en"),
    "redovisa": make_verb(True, "redovisa", "redovisar", "redovisade", "redovisat", "redovisad"),
    "kungafamilj": make_noun("en"),
    "statsskick": make_noun("ett"),
    "papper": make_noun("ett"),
    "tillhöra": make_verb(True, "tillhör", "tillhör", "tillhörde", "tillhört", "tillhörd"),
    "1800-talet": make_noun("ett"),
    "bli vald": make_verb(False, "bli vald", "blir vald", "blev vald", "blivit vald", None),
    "kronprins": make_noun("en"),
    "nuvarande": make_adj("nuvarande", "nuvarande", "nuvarande", "mer nuvarande", "mest nuvarande"),
    "gift med": make_adj("gift med", "gift med", "gifta med", "mer gift med", "mest gift med"),
    "undantag": make_noun("ett"),
    "koalition": make_noun("en"),
    "allians": make_noun("en"),
    "valmanifest": make_noun("ett"),
    "nationalistisk": make_adj("nationalistisk", "nationalistiskt", "nationalistiska", "mer nationalistisk", "mest nationalistisk"),
    "ha rötterna i": make_verb(False, "ha rötterna i", "har rötterna i", "hade rötterna i", "haft rötterna i", None),
    "högerextremism": make_noun("en"),
    "dyka upp": make_verb(False, "dyk upp", "dyker upp", "dök upp", "dykt upp", None),
    "enfrågeparti": make_noun("ett"),
    "halvera": make_verb(True, "halvera", "halverar", "halverade", "halverat", "halverad"),
    "sprit": make_noun("en"),
    "hälsovård": make_noun("en"),
    "sjukvård": make_noun("en"),
    "huvudfråga": make_noun("en"),
    "republikansk": make_adj("republikansk", "republikanskt", "republikanska", "mer republikansk", "mest republikansk")
}

# Verify all chunks match exact key set in deep_chunk_X.json
all_metas = {28: meta_28, 29: meta_29, 30: meta_30, 31: meta_31, 32: meta_32}

for c in range(28, 33):
    path = os.path.join(chunks_dir, f"deep_chunk_{c}.json")
    with open(path, "r", encoding="utf-8") as f:
        words = json.load(f)
    meta = all_metas[c]
    missing = [w for w in words if w not in meta]
    extra = [w for w in meta if w not in words]
    print(f"Chunk {c}: words={len(words)}, meta={len(meta)}, missing={len(missing)}, extra={len(extra)}")
    if missing or extra:
        print(f"  Missing: {missing}")
        print(f"  Extra: {extra}")

