import json
import os

chunks_dir = "./course/sfid/phase3/data/chunks"

def make_noun(gender):
    return {
        "word_type": "noun",
        "noun_gender": gender,
        "is_regular_verb": None,
        "verb_imperativ": None,
        "verb_presens": None,
        "verb_preteritum": None,
        "verb_supinum": None,
        "verb_perfekt_particip": None,
        "adj_en": None,
        "adj_ett": None,
        "adj_plural": None,
        "adj_komparativ": None,
        "adj_superlativ": None
    }

def make_verb(is_regular, imp, pres, pret, sup, part=None):
    return {
        "word_type": "verb",
        "noun_gender": None,
        "is_regular_verb": is_regular,
        "verb_imperativ": imp,
        "verb_presens": pres,
        "verb_preteritum": pret,
        "verb_supinum": sup,
        "verb_perfekt_particip": part,
        "adj_en": None,
        "adj_ett": None,
        "adj_plural": None,
        "adj_komparativ": None,
        "adj_superlativ": None
    }

def make_adj(en, ett, pl, komp, sup):
    return {
        "word_type": "adjective",
        "noun_gender": None,
        "is_regular_verb": None,
        "verb_imperativ": None,
        "verb_presens": None,
        "verb_preteritum": None,
        "verb_supinum": None,
        "verb_perfekt_particip": None,
        "adj_en": en,
        "adj_ett": ett,
        "adj_plural": pl,
        "adj_komparativ": komp,
        "adj_superlativ": sup
    }

meta_33 = {
    "avskaffa": make_verb(True, "avskaffa", "avskaffar", "avskaffade", "avskaffat", "avskaffad"),
    "intervjua": make_verb(True, "intervjua", "intervjuar", "intervjuade", "intervjuat", "intervjuad"),
    "partiledare": make_noun("en"),
    "rädda": make_verb(True, "rädda", "räddar", "räddade", "räddat", "räddad"),
    "utfiskad": make_adj("utfiskad", "utfiskat", "utfiskade", "mer utfiskad", "mest utfiskad"),
    "släppa ut": make_verb(True, "släpp ut", "släpper ut", "släppte ut", "släppt ut", "släppt ut"),
    "förorening": make_noun("en"),
    "skräp": make_noun("ett"),
    "dö ut": make_verb(False, "dö ut", "dör ut", "dog ut", "dött ut", None),
    "röst": make_noun("en"),
    "annonsera": make_verb(True, "annonsera", "annonserar", "annonserade", "annonserat", "annonserad"),
    "tidning": make_noun("en"),
    "informera": make_verb(True, "informera", "informerar", "informerade", "informerat", "informerad"),
    "sätta upp": make_verb(False, "sätt upp", "sätter upp", "satte upp", "satt upp", "satt upp"),
    "affisch": make_noun("en"),
    "ställa sig": make_verb(True, "ställ dig", "ställer sig", "ställde sig", "ställt sig", "ställd"),
    "köpcentrum": make_noun("ett"),
    "flygblad": make_noun("ett"),
    "klimat": make_noun("ett"),
    "rök": make_noun("en"),
    "futurum": make_noun("ett"),
    "streck": make_noun("ett"),
    "dra streck": make_verb(False, "dra streck", "drar streck", "drog streck", "dragit streck", None),
    "framtid": make_noun("en"),
    "detsamma som": make_adj("detsamma som", "detsamma som", "detsamma som", "mer detsamma som", "mest detsamma som"),
    "beslut": make_noun("ett"),
    "andrahand": make_noun("en"),
    "andrahandsinformation": make_noun("en"),
    "logisk": make_adj("logisk", "logiskt", "logiska", "mer logisk", "mest logisk"),
    "konsekvens": make_noun("en"),
    "prognos": make_noun("en"),
    "konditional": make_adj("konditional", "konditionalt", "konditionala", "mer konditional", "mest konditional"),
    "farfar": make_noun("en"),
    "stabil": make_adj("stabil", "stabilt", "stabila", "stabilare", "stabilast"),
    "socialistisk": make_adj("socialistisk", "socialistiskt", "socialistiska", "mer socialistisk", "mest socialistisk"),
    "socialdemokratisk": make_adj("socialdemokratisk", "socialdemokratiskt", "socialdemokratiska", "mer socialdemokratisk", "mest socialdemokratisk"),
    "folkhem": make_noun("ett"),
    "ersätta": make_verb(False, "ersätt", "ersätter", "ersatte", "ersatt", "ersatt"),
    "klassamhälle": make_noun("ett"),
    "jämlikhet": make_noun("en"),
    "samförstånd": make_noun("ett"),
    "medborgare": make_noun("en"),
    "låg": make_adj("låg", "lågt", "låga", "lägre", "lägst"),
    "välfärd": make_noun("en"),
    "välfärdststat": make_noun("en"),
    "allmän": make_adj("allmän", "allmänt", "allmänna", "mer allmän", "mest allmän"),
    "barnbidrag": make_noun("ett"),
    "obligatorisk": make_adj("obligatorisk", "obligatoriskt", "obligatoriska", "mer obligatorisk", "mest obligatorisk"),
    "tilläggspension": make_noun("en"),
    "ökad": make_adj("ökad", "ökat", "ökade", "mer ökad", "mest ökad")
}

meta_34 = {
    "bidrag": make_noun("ett"),
    "komma in i": make_verb(False, "kom in i", "kommer in i", "kom in i", "kommit in i", "kommen in i"),
    "tillkomma": make_verb(False, "tillkom", "tillkommer", "tillkom", "tillkommit", "tillkommen"),
    "ytterligare": make_adj("ytterligare", "ytterligare", "ytterligare", "mer ytterligare", "mest ytterligare"),
    "åka ur": make_verb(True, "åk ur", "åker ur", "åkte ur", "åkt ur", None),
    "högt tryck": make_noun("ett"),
    "skattetryck": make_noun("ett"),
    "progressiv": make_adj("progressiv", "progressivt", "progressiva", "progressivare", "progressivast"),
    "skala": make_noun("en"),
    "ekonomi": make_noun("en"),
    "svag": make_adj("svag", "svagt", "svaga", "svagare", "svagast"),
    "offentlig": make_adj("offentlig", "offentligt", "offentliga", "mer offentlig", "mest offentlig"),
    "utgift": make_noun("en"),
    "kärnkraft": make_noun("en"),
    "åsikt": make_noun("en"),
    "samarbete": make_noun("ett"),
    "statskupp": make_noun("en"),
    "mördad": make_adj("mördad", "mördat", "mördade", "mer mördad", "mest mördad"),
    "skjuta": make_verb(False, "skjut", "skjuter", "sköt", "skjutit", "skjuten"),
    "mandatperiod": make_noun("en"),
    "styre": make_noun("ett"),
    "sitta vid makten": make_verb(False, "sitt vid makten", "sitter vid makten", "satt vid makten", "suttit vid makten", None),
    "utan avbrott": make_adj("utan avbrott", "utan avbrott", "utan avbrott", "mer utan avbrott", "mest utan avbrott"),
    "månad": make_noun("en"),
    "interimsregering": make_noun("en"),
    "Moder Svea": make_noun("en"),
    "på öppen gata": make_adj("på öppen gata", "på öppen gata", "på öppen gata", "mer på öppen gata", "mest på öppen gata"),
    "ta över": make_verb(False, "ta över", "tar över", "tog över", "tagit över", "tagen över"),
    "post": make_noun("en"),
    "riksdagsman": make_noun("en"),
    "myndighet": make_noun("en"),
    "block": make_noun("ett"),
    "statsråd": make_noun("ett"),
    "utrikesminister": make_noun("en"),
    "utbildningsminister": make_noun("en"),
    "kulturminister": make_noun("en"),
    "försvarsminister": make_noun("en"),
    "miljöminister": make_noun("en"),
    "departement": make_noun("ett"),
    "föreslå": make_verb(False, "föreslå", "föreslår", "föreslog", "föreslagit", "föreslagen"),
    "bli verklighet": make_verb(False, "bli verklighet", "blir verklighet", "blev verklighet", "blivit verklighet", None),
    "socialbidrag": make_noun("ett"),
    "se till att": make_verb(False, "se till att", "ser till att", "såg till att", "sett till att", None),
    "betala ut": make_verb(True, "betala ut", "betalar ut", "betalade ut", "betalat ut", "betald ut"),
    "lägga sig i": make_verb(False, "lägg dig i", "lägger sig i", "lade sig i", "lagt sig i", None),
    "i detalj": make_adj("i detalj", "i detalj", "i detalj", "mer i detalj", "mest i detalj"),
    "län": make_noun("ett"),
    "indelat": make_adj("indelad", "indelat", "indelade", "mer indelat", "mest indelat"),
    "länsstyrelse": make_noun("en"),
    "samhällsplanering": make_noun("en")
}

meta_35 = {
    "samarbeta": make_verb(True, "samarbeta", "samarbetar", "samarbetade", "samarbetat", "samarbetad"),
    "motsvara": make_verb(True, "motsvara", "motsvarar", "motsvarade", "motsvarat", "motsvarad"),
    "tandvård": make_noun("en"),
    "kollektivtrafik": make_noun("en"),
    "invånare": make_noun("en"),
    "kommunal": make_adj("kommunal", "kommunalt", "kommunala", "mer kommunal", "mest kommunal"),
    "självstyre": make_noun("ett"),
    "barnomsorg": make_noun("en"),
    "åldringsvård": make_noun("en"),
    "erbjuda": make_verb(False, "erbjud", "erbjuder", "erbjöd", "erbjudit", "erbjuden"),
    "socialtjänst": make_noun("en"),
    "svenska för invandrare": make_noun("en"),
    "funktionshinder": make_noun("ett"),
    "statistik": make_noun("en"),
    "återkomma": make_verb(False, "återkom", "återkommer", "återkom", "återkommit", "återkommen"),
    "krånglig": make_adj("krånglig", "krångligt", "krångliga", "krångligare", "krångligast"),
    "andel": make_noun("en"),
    "två tredjedelar": make_noun("en"),
    "hälft": make_noun("en"),
    "smultronställe": make_noun("ett"),
    "vilsam": make_adj("vilsam", "vilsamt", "vilsamma", "vilsammare", "vilsammast"),
    "barnhem": make_noun("ett"),
    "snusa": make_verb(True, "snusa", "snusar", "snusade", "snusat", "snusad"),
    "trång": make_adj("trång", "trångt", "trånga", "trängre", "trängst"),
    "cykelbana": make_noun("en"),
    "nervös": make_adj("nervös", "nervöst", "nervösa", "nervösare", "nervösast"),
    "prov": make_noun("ett"),
    "tablett": make_noun("en"),
    "hålla på med": make_verb(False, "håll på med", "håller på med", "höll på med", "hållit på med", "hållen på med"),
    "ointresserad": make_adj("ointresserad", "ointresserat", "ointresserade", "mer ointresserad", "mest ointresserad"),
    "protestera": make_verb(True, "protestera", "protesterar", "protesterade", "protesterat", "protesterad"),
    "politiskt aktiv": make_adj("politiskt aktiv", "politiskt aktivt", "politiskt aktiva", "mer politiskt aktiv", "mest politiskt aktiv"),
    "lärare": make_noun("en"),
    "klasskompis": make_noun("en"),
    "skolpersonal": make_noun("en"),
    "skolmat": make_noun("en"),
    "mycket bättre": make_adj("mycket bättre", "mycket bättre", "mycket bättre", "ännu bättre", "allra bäst"),
    "ungdomsförbund": make_noun("ett"),
    "hata": make_verb(True, "hata", "hatar", "hatade", "hatat", "hatad"),
    "grundlag": make_noun("en"),
    "regeringsformen": make_noun("en"),
    "successionsordningen": make_noun("en"),
    "tryckfrihetsförordningen": make_noun("en"),
    "yttrandefrihetsgrundlagen": make_noun("en"),
    "rättighet": make_noun("en"),
    "stå över": make_verb(False, "stå över", "står över", "stod över", "stått över", None),
    "plats": make_noun("en"),
    "landsting": make_noun("ett"),
    "ministerpost": make_noun("en"),
    "kommun": make_noun("en")
}

meta_36 = {
    "befolkning": make_noun("en"),
    "rösta": make_verb(True, "rösta", "röstar", "röstade", "röstat", "röstad"),
    "ha hand om": make_verb(False, "ha hand om", "har hand om", "hade hand om", "haft hand om", None),
    "vart fjärde år": make_noun("ett"),
    "nivå": make_noun("en"),
    "lokal": make_adj("lokal", "lokalt", "lokala", "mer lokal", "mest lokal"),
    "tre år i rad": make_adj("tre år i rad", "tre år i rad", "tre år i rad", "mer tre år i rad", "mest tre år i rad"),
    "rösträtt": make_noun("en"),
    "lagförslag": make_noun("ett"),
    "proposition": make_noun("en"),
    "vara för sig själv": make_verb(False, "var för dig själv", "är för sig själv", "var för sig själv", "varit för sig själv", None),
    "stödord": make_noun("ett"),
    "Hur ser det ut?": make_verb(False, "se ut", "ser ut", "såg ut", "sett ut", None),
    "Vad gör du där?": make_verb(False, "gör", "gör", "gjorde", "gjort", "gjord"),
    "berömd": make_adj("berömd", "berömt", "berömda", "mer berömd", "mest berömd"),
    "så här": make_adj("så här", "så här", "så här", "mer så här", "mest så här"),
    "bergmansk": make_adj("bergmansk", "bergmanskt", "bergmanska", "mer bergmansk", "mest bergmansk"),
    "ångest": make_noun("en"),
    "teatertradition": make_noun("en"),
    "basker": make_noun("en"),
    "regissör": make_noun("en"),
    "filmmanus": make_noun("ett"),
    "teaterpjäs": make_noun("en"),
    "1900-talet": make_noun("ett"),
    "folklig": make_adj("folklig", "folkligt", "folkliga", "folkligare", "folkligast"),
    "pjäs": make_noun("en"),
    "svartvit": make_adj("svartvit", "svartvitt", "svartvita", "mer svartvit", "mest svartvit"),
    "rad": make_noun("en"),
    "ung": make_adj("ung", "ungt", "unga", "yngre", "yngst"),
    "romantisk": make_adj("romantisk", "romantiskt", "romantiska", "mer romantisk", "mest romantisk"),
    "höst": make_noun("en"),
    "gravid": make_adj("gravid", "gravid", "gravida", "mer gravid", "mest gravid"),
    "gå dåligt för": make_verb(False, "gå dåligt för", "går dåligt för", "gick dåligt för", "gått dåligt för", None),
    "andra länder": make_noun("ett"),
    "på många ställen": make_noun("ett"),
    "myt": make_noun("en"),
    "synd": make_noun("en"),
    "scen": make_noun("en"),
    "riddare": make_noun("en"),
    "leva": make_verb(True, "lev", "lever", "levde", "levt", "levd"),
    "lite till": make_adj("lite till", "lite till", "lite till", "mer lite till", "mest lite till"),
    "bila": make_verb(True, "bila", "bilar", "bilade", "bilat", "bilad"),
    "svärdotter": make_noun("en"),
    "paus": make_noun("en"),
    "ungdom": make_noun("en"),
    "dagdrömma": make_verb(True, "dagdröm", "dagdrömmer", "dagdrömde", "dagdrömt", "dagdrömd"),
    "skådespelerska": make_noun("en"),
    "sommarställe": make_noun("ett"),
    "släktkrönika": make_noun("en"),
    "exotisk": make_adj("exotisk", "exotiskt", "exotiska", "mer exotisk", "mest exotisk")
}

meta_37 = {
    "spännande": make_adj("spännande", "spännande", "spännande", "mer spännande", "mest spännande"),
    "läskig": make_adj("läskig", "läskigt", "läskiga", "läskigare", "läskigast"),
    "smultron": make_noun("ett"),
    "sol": make_noun("en"),
    "grässtrå": make_noun("ett"),
    "trä upp": make_verb(True, "trä upp", "trär upp", "trädde upp", "trätt upp", "trädd upp"),
    "färsk": make_adj("färsk", "färskt", "färska", "färskare", "färskast"),
    "grädde": make_noun("en"),
    "glass": make_noun("en"),
    "mjölk": make_noun("en"),
    "sylt": make_noun("en"),
    "saft": make_noun("en"),
    "jordgubbe": make_noun("en"),
    "medicin": make_noun("en"),
    "trubadur": make_noun("en"),
    "vin": make_noun("ett"),
    "hålla hemlig": make_verb(False, "håll hemlig", "håller hemlig", "höll hemlig", "hållit hemlig", "hållen hemlig"),
    "botaniker": make_noun("en"),
    "geolog": make_noun("en"),
    "pedagog": make_noun("en"),
    "zoolog": make_noun("en"),
    "systematisera": make_verb(True, "systematisera", "systematiserar", "systematiserade", "systematiserat", "systematiserad"),
    "växtnamn": make_noun("ett"),
    "kallas för": make_verb(True, "kallas för", "kallas för", "kallades för", "kallats för", "kallad för"),
    "nationalskald": make_noun("en"),
    "dikt": make_noun("en"),
    "hedersman": make_noun("en"),
    "gå ur": make_verb(False, "gå ur", "går ur", "gick ur", "gått ur", "gången ur"),
    "plantera": make_verb(True, "plantera", "planterar", "planterade", "planterat", "planterad"),
    "slå upp": make_verb(False, "slå upp", "slår upp", "slog upp", "slagit upp", "slagen upp"),
    "stig": make_noun("en"),
    "gå vilse": make_verb(False, "gå vilse", "går vilse", "gick vilse", "gått vilse", None),
    "tät": make_adj("tät", "tätt", "täta", "tätare", "tätast"),
    "brant": make_adj("brant", "brant", "branta", "brantare", "brantast"),
    "klippa": make_noun("en"),
    "ta ett dopp": make_verb(False, "ta ett dopp", "tar ett dopp", "tog ett dopp", "tagit ett dopp", None),
    "macka": make_noun("en"),
    "råd": make_noun("ett"),
    "titta in": make_verb(True, "titta in", "tittar in", "tittade in", "tittat in", "tittad in"),
    "stämning": make_noun("en"),
    "komma fram": make_verb(False, "kom fram", "kommer fram", "kom fram", "kommit fram", "kommen fram"),
    "fik": make_noun("ett"),
    "minnas": make_verb(True, "minns", "minns", "mindes", "mints", None),
    "rekonstruera": make_verb(True, "rekonstruera", "rekonstruerar", "rekonstruerade", "rekonstruerat", "rekonstruerad"),
    "referera": make_verb(True, "referera", "refererar", "refererade", "refererat", "refererad"),
    "rörelse": make_noun("en"),
    "sats": make_noun("en"),
    "genetivform": make_noun("en"),
    "uppdelad": make_adj("uppdelad", "uppdelat", "uppdelade", "mer uppdelad", "mest uppdelad"),
    "född": make_adj("född", "fött", "födda", "mer född", "mest född")
}

all_metas = {33: meta_33, 34: meta_34, 35: meta_35, 36: meta_36, 37: meta_37}

for c in range(33, 38):
    path = os.path.join(chunks_dir, f"deep_chunk_{c}.json")
    with open(path, "r", encoding="utf-8") as f:
        words = json.load(f)
    meta = all_metas[c]
    missing = [w for w in words if w not in meta]
    extra = [w for w in meta if w not in words]
    print(f"Chunk {c}: words={len(words)}, meta={len(meta)}, missing={len(missing)}, extra={len(extra)}")
    if missing or extra:
        print(f"  Missing: {missing}")
        print(f"  Extra: {extra}")

