import json
import re

with open("sfid_phase2_articles.json", "r", encoding="utf-8") as f:
    data = json.load(f)

articles = []
for stage in data.get('stages', []):
    for art in stage.get('articles', []):
        articles.append(art)

with open("all_translations_raw.json", "r", encoding="utf-8") as f:
    translations = json.load(f)

# Sort articles by id
def get_num(art_id):
    m = re.search(r'\d+', art_id)
    return int(m.group()) if m else 0

articles_sorted = sorted(articles, key=lambda x: get_num(x['article_id']))

batch_size = 10
batches = [articles_sorted[i:i + batch_size] for i in range(0, len(articles_sorted), batch_size)]

for batch_idx, batch in enumerate(batches):
    prompt_file = f"teacher_prompt_{batch_idx}.txt"
    with open(prompt_file, "w", encoding="utf-8") as f:
        f.write("You are an expert SFI (Swedish for Immigrants) language teacher and native Swedish & English speaker.\n")
        f.write("Below are Swedish sentences and their corresponding English translations generated by a translator. Your task is to validate and, if necessary, CORRECT the English translations to ensure they are accurate, natural, and accurately reflect the Swedish original.\n")
        f.write("Return a JSON dictionary mapping the `sentence_id` to the CORRECTED English translation. If the original translation is already perfect, just return the same English translation.\n\n")
        
        for art in batch:
            art_id = art['article_id']
            f.write(f"--- Article {art_id} ---\n")
            for sent in art.get('sentences', []):
                s_id = sent['sentence_id']
                sv_text = sent['sv']
                en_trans = translations.get(s_id, "")
                f.write(f"[{s_id}]\n")
                f.write(f"Swedish: {sv_text}\n")
                f.write(f"English: {en_trans}\n\n")

print(f"Created {len(batches)} teacher prompt files.")
