import json

data = {
  "art_10_s001": "My course mate and I decided to go to a library to revise for a big test.",
  "art_10_s002": "\"Would you like to...?\" she asked, and wanted to suggest that we should study on a bridge day.",
  "art_10_s003": "\"What do you say?\"",
  "art_10_s004": "I thought it sounded good, so we could get as many hours as possible to read.",
  "art_10_s005": "We chose to discuss Swedish grammar.",
  "art_10_s006": "Our assignment would consist of a written part and an oral presentation.",
  "art_10_s007": "An advantage was that we had a long glossary to practice on.",
  "art_10_s008": "We received a piece of paper where each box contained a statement.",
  "art_10_s009": "Every sentence had an important concept.",
  "art_10_s010": "We were tasked with underlining every keyword and then summarizing everything.",
  "art_10_s011": "We started with a vocabulary exercise.",
  "art_10_s012": "We practiced vocabulary by looking at a vowel, a consonant and every syllable.",
  "art_10_s013": "It was fun.",
  "art_10_s014": "\"You are skillful,\" she pointed out.",
  "art_10_s015": "We also talked about sound changes, like weak reduction and assimilation.",
  "art_10_s016": "We wanted to prove what we had learned.",
  "art_10_s017": "Then we went through different parts of speech and parts of a sentence.",
  "art_10_s018": "We learned to find a subject.",
  "art_10_s019": "We compared definite form with indefinite form, and practiced the comparative of the adjective.",
  "art_10_s020": "We looked at reflexive pronouns, and learned when to use the supine and imperative.",
  "art_10_s021": "We also tried to emphasize correctly.",
  "art_10_s022": "We practiced building sentences.",
  "art_10_s023": "A sentence can begin with a main clause and be followed by a subordinate clause.",
  "art_10_s024": "We saw how a conjunction, a subjunction or a preposition can change everything.",
  "art_10_s025": "We learned to write direct speech.",
  "art_10_s026": "A disadvantage of grammar is that there are so many rules to remember.",
  "art_10_s027": "My cousin who works at a famous academy gave me a good tip.",
  "art_10_s028": "He said that language is a heritage, almost like a newly caught fish that you have to mix in a pot.",
  "art_10_s029": "The English word 'other' can be translated to \"andra\".",
  "art_10_s030": "The only rule is to have a lively ending and a clear conclusion.",
  "art_10_s031": "The number is up to a hundred rules, but I felt that I began to understand them.",
  "art_10_s032": "\"I would prefer to take a break now and pay for some fika,\" I said.",
  "art_11_s001": "I am studying a new subject at an exciting folk high school in the city.",
  "art_11_s002": "Every day we have a lecture about different historical languages, and last week we learned a lot about the Indo-European language family.",
  "art_11_s003": "In that family it is well known that Germanic languages such as Proto-Norse, Icelandic and Faroese are included.",
  "art_11_s004": "Even though they are related, and have similar grammar, they often sound very different when spoken.",
  "art_11_s005": "Other famous languages in Europe like Estonian, Sami and Hungarian actually belong to the Finno-Ugric family.",
  "art_11_s006": "In addition we talked about Inuit languages in Greenland and how a Russian dialect can affect an entire group of people in border areas.",
  "art_11_s007": "\"Do you remember?\" an older lady in my class asked when we discussed.",
  "art_11_s008": "\"The teacher said that there is a gigantic sum of languages in the world, over six thousand in total!\"",
  "art_11_s009": "We were then given the task of writing an article about grammar.",
  "art_11_s010": "The teacher said we should choose a red headline and write a good introduction to attract the reader.",
  "art_11_s011": "Besides that, we had to follow an italicized language convention for all example words.",
  "art_11_s012": "A piece of advice was to \"Say something out loud\" when writing.",
  "art_11_s013": "We were namely to present all of this in writing to the whole class.",
  "art_11_s014": "To make it clearer: you can for example... put a compound word in parentheses to explain its meaning.",
  "art_11_s015": "\"Have you tried/attempted to...?\" the teacher asked when I seemed unsure.",
  "art_11_s016": "She gave me a lot of support.",
  "art_11_s017": "In our text we were primarily to show that we understand basic grammar.",
  "art_11_s018": "We carefully filled a column in the book with verbs in the infinitive, present and preterite.",
  "art_11_s019": "We also learned to conjugate each verb group in the correct tense, such as the conditional, which can be quite difficult for many.",
  "art_11_s020": "A complete verb phrase is important, just like using good linking words and understanding how direct and indirect speech works in dialogues.",
  "art_11_s021": "We also learned the difference between what is a short syllable and a long syllable when speaking.",
  "art_11_s022": "We were tasked with notifying each other immediately if we saw an incorrect genitive form or an adjective in the superlative.",
  "art_11_s023": "Finally, the teacher talked about how current and contemporary rules have constantly evolved over the years.",
  "art_11_s024": "The Swedish Academy works very actively to meet new needs in society.",
  "art_11_s025": "A political decision or a negative debate against certain changes also affects how the language grows.",
  "art_11_s026": "New words can constantly be born out of everyday life, while others can fall away, almost in the same way as old clothes are sold at a discount.",
  "art_11_s027": "It felt incredibly good when the text was finally completely finished after all the hard work.",
  "art_12_s001": "I love food.",
  "art_12_s002": "For many years I have liked to bake and cook good dishes.",
  "art_12_s003": "My friend, who is a famous playwright, loves a lot of drama in the kitchen.",
  "art_12_s004": "After working all day he was hungry as a wolf.",
  "art_12_s005": "He usually says that he likes to eat like a horse when his stomach is empty.",
  "art_12_s006": "I thought about suggesting that we could go out and eat.",
  "art_12_s007": "For a while I thought we should buy takeout.",
  "art_12_s008": "But the hallway was cramped and I felt mentally tired after work.",
  "art_12_s009": "We chose to stay home.",
  "art_12_s010": "Instead of... going to a restaurant, we started making easy finger food and slicing up every vegetable as well as fruit like apple and banana.",
  "art_12_s011": "\"It is not true!\" my friend shouted suddenly.",
  "art_12_s012": "A bloodthirsty mosquito had given him a wasp sting.",
  "art_12_s013": "\"One more comment,\" he said, \"and I'll die.",
  "art_12_s014": "I feel uncomfortable and need more carbohydrate.",
  "art_12_s015": "I don't want to be critical, but I have to eat.\"",
  "art_12_s016": "I asked him to taste a little salami sausage.",
  "art_12_s017": "\"You must eat properly so as not to lack food,\" I said.",
  "art_12_s018": "To avoid a failure, I served the dish at a high level.",
  "art_12_s019": "The scent of garlic began to spread.",
  "art_12_s020": "Everyone got a plate.",
  "art_12_s021": "We wanted to drink something good.",
  "art_12_s022": "I drank cold soda while he had a light beer.",
  "art_12_s023": "Sometimes he mixes a drink, maybe a large umbrella drink, but now we drank without much sugar.",
  "art_12_s024": "Water is otherwise best, because if you drink seawater you only get thirstier.",
  "art_12_s025": "I could be sure that my friend was satisfied.",
  "art_12_s026": "After dinner I wondered: \"Should we have a fika?\"",
  "art_12_s027": "I would rather bake a cake than eat store-bought candy or loose candy.",
  "art_12_s028": "We had chocolate at home.",
  "art_12_s029": "My friend however just wanted a bowl of low-fat yogurt.",
  "art_12_s030": "He thought that my food for the day was a little too dramatic.",
  "art_12_s031": "We talked about growing berries and how people used to make jam and juice in the past, or similar things.",
  "art_12_s032": "I hope we can meet again the week after next, before all the joy has time to disappear.",
  "art_13_s001": "I am a real sweet tooth.",
  "art_13_s002": "Ten years ago I often heard from my teacher that I had a sugar addiction.",
  "art_13_s003": "At that time we often had bad school food and there was always a lack of good food and drink.",
  "art_13_s004": "Therefore I was always really hungry and craving a fika when the school day was over.",
  "art_13_s005": "Today I live far out in the country, where our local climate is good for growing sugar beets.",
  "art_13_s006": "I know that the farmer is proud of his sugar beet.",
  "art_13_s007": "Sometimes I have to get in touch with the farmers.",
  "art_13_s008": "My friend, who was a famous confectioner, said that old traditions must live on.",
  "art_13_s009": "He used to make a lot of nice things, like a marzipan cake or a small gingerbread full of sweet caramel.",
  "art_13_s010": "I know from secondhand information that he once worked at a famous chocolate factory.",
  "art_13_s011": "It sounded like a strange but fantastic place!",
  "art_13_s012": "One day I felt that I had to take a break from work.",
  "art_13_s013": "I decided to get something good for our family dinner.",
  "art_13_s014": "I went to my favorite hidden spot, a cozy candy store.",
  "art_13_s015": "It looked different, almost like a large supermarket from a modern grocery chain.",
  "art_13_s016": "\"Why don't you sit down for a while,\" the owner said.",
  "art_13_s017": "It felt good.",
  "art_13_s018": "I walked around among the shelves while thinking about what to choose.",
  "art_13_s019": "I wanted something more than just fruit.",
  "art_13_s020": "I found a new kind of candy, which was a small jelly fish with a lovely fruit flavor.",
  "art_13_s021": "I also found a nice praline, a large chocolate bar and a bag of peppermint stick.",
  "art_13_s022": "In addition, I bought Saturday candy, some pick-and-mix candy and a fun box of pastilles for the children.",
  "art_13_s023": "There was even a sweet like a chocolate-covered marshmallow treat and a good cake.",
  "art_13_s024": "All this was as far from a Tex-Mex product as you can get.",
  "art_13_s025": "The morning after, I enjoyed it all like a luxurious hotel breakfast.",
  "art_13_s026": "Say what you want, I know it might make me look foolish, but I am so happy about my goodies.",
  "art_13_s027": "One has to sort out what is important in life, otherwise it gets boring.",
  "art_13_s028": "Sometimes it is more fun to just chew on something good.",
  "art_14_s001": "In Sweden, a meal can have a special theme.",
  "art_14_s002": "First and foremost we have fika.",
  "art_14_s003": "Having a fika can be as simple as drinking a glass of juice and eating a sandwich at a small café.",
  "art_14_s004": "Some prefer cold milk, while others have a glass of wine with a late dinner.",
  "art_14_s005": "\"That's nice?\" asked a friend from abroad when she saw my home-cooked food.",
  "art_14_s006": "A typical Swedish everyday food is boiled potatoes and a meatball.",
  "art_14_s007": "You can add some spice, for example allspice.",
  "art_14_s008": "\"But you don't eat horse meat, do you?\" she wondered.",
  "art_14_s009": "\"Yes, it is true!\" I said.",
  "art_14_s010": "In the past there was no ban on it, even if you had to eat what was available, especially during a historical oil crisis.",
  "art_14_s011": "But she didn't have to be afraid of it now.",
  "art_14_s012": "She did not want to criticize, but thought the idea was a bit crazy.",
  "art_14_s013": "I also cooked palt, an old dish baked with wheat flour and potatoes.",
  "art_14_s014": "It is served with lots of butter and lingonberry jam.",
  "art_14_s015": "\"On the one hand... on the other hand,\" my friend began, \"it is delicious, but you get a food coma.\"",
  "art_14_s016": "So that she wouldn't be overcome by fatigue, we decided to go out.",
  "art_14_s017": "We took a dip.",
  "art_14_s018": "After several salty baths we got new energy.",
  "art_14_s019": "We celebrated the warm month of June by eating more.",
  "art_14_s020": "The sun's low angle of incidence over the sea was beautiful.",
  "art_14_s021": "We watched an old movie, a real tearjerker, while we ate dessert.",
  "art_14_s022": "I had made an oven-baked pancake with a dollop of egg cheese.",
  "art_14_s023": "We also had an apple cake spiced with cinnamon and adorned with at least one apple wedge.",
  "art_14_s024": "In addition, there was fresh strawberry and some blackberries that seemed to be buried under the cream.",
  "art_14_s025": "\"This dish should belong to an official menu,\" she said.",
  "art_14_s026": "\"Thanks, but next time maybe I'll cook spicy Thai food with bell pepper and some grated parmesan on top, even if it requires a long explanation of a difficult recipe step by step,\" I laughed.",
  "art_15_s001": "In the past, it was important to be able to make jam and preserve food to have food throughout the winter.",
  "art_15_s002": "\"I had no idea about that,\" said my friend from Spain.",
  "art_15_s003": "To impress him, I decided to teach him about Swedish food.",
  "art_15_s004": "There were many large food projects before we even started eating, like caramel making.",
  "art_15_s005": "Everything happened in the kitchen and I almost wanted to educate him in our culture.",
  "art_15_s006": "Last winter we used to bake a bun with yeast and eat marmalade with an orange flavor.",
  "art_15_s007": "It was a light and fresh breakfast.",
  "art_15_s008": "But he would rather go to a restaurant to eat a good salad with chicken and egg.",
  "art_15_s009": "\"Okay then\", I said, and we ate out instead.",
  "art_15_s010": "I wanted to show that Swedish food culture can also change and be progressive.",
  "art_15_s011": "\"Come on!\" I shouted.",
  "art_15_s012": "We went to a market.",
  "art_15_s013": "The country's reigning snack manufacturer sold a wonderful mixture of roasted nut and candied violet or lilac.",
  "art_15_s014": "After a while we chose to buy a soft and chewy cream toffee.",
  "art_15_s015": "We also bought some salted herring and a can of fermented herring.",
  "art_15_s016": "For a long time, people used to stop in the evening to eat something good.",
  "art_15_s017": "You could mix some mushrooms and salt thoroughly.",
  "art_15_s018": "You saved everything in your pantry.",
  "art_15_s019": "Today food is often produced abroad, and trucks ply the roads to and from the stores to give us ready-made goods.",
  "art_15_s020": "It is much easier now than in the past.",
  "art_15_s021": "After dinner I offered frozen ice cream with some cream, honey and a little jam on top.",
  "art_15_s022": "He loved it.",
  "art_15_s023": "Swedish food is fantastic.",
  "art_15_s024": "\"Are you with me?\" I asked.",
  "art_15_s025": "He nodded in agreement and wanted me to repeat the recipe, because different types of food fascinated him.",
  "art_15_s026": "One of the country's biggest challenges is to preserve the old, but this went well.",
  "art_15_s027": "Greetings ...",
  "art_16_s001": "\"What's up?\" asked my neighbor when he decided to drop by on a cold evening in March.",
  "art_16_s002": "\"Do you think that...?\" he began, but stopped.",
  "art_16_s003": "I understood what he meant.",
  "art_16_s004": "He was very hungry.",
  "art_16_s005": "I had an idea to make a warming soup.",
  "art_16_s006": "\"We should eat something good,\" I said.",
  "art_16_s007": "I started cooking in front of a sparkling fire.",
  "art_16_s008": "A fact is that I love locally produced and locally grown food.",
  "art_16_s009": "I wanted to find out if he liked classic Swedish home cooking, so that he got to experience real tradition.",
  "art_16_s010": "First I served yellow pea soup with fried pork.",
  "art_16_s011": "Some spice it with German herbs, but I added some garlic and ginger.",
  "art_16_s012": "A kid would probably have thought it was weird, but he liked it.",
  "art_16_s013": "My neighbor did not seem to be infected by any cold, because he had a good appetite.",
  "art_16_s014": "He explained in detail why it was the best meal in a long time.",
  "art_16_s015": "As a consequence, I had to cook even more!",
  "art_16_s016": "For the main course I offered a dish that was a cabbage roll filled with rice and meat.",
  "art_16_s017": "We also had diced tomato and raw onion.",
  "art_16_s018": "As a side dish I served oven-baked salmon with a dollop of cream sauce.",
  "art_16_s019": "For dessert we ate saffron pancake made from a fine batter with saffron and egg white.",
  "art_16_s020": "It was served with dewberry and whipped cream, as well as some raisins.",
  "art_16_s021": "It was a calorie-rich but wonderful dessert.",
  "art_16_s022": "Above all he loved a little grated peach on top, and some confectionery to melt in the mouth.",
  "art_16_s023": "We drank hot chocolate and caffè latte.",
  "art_16_s024": "A large amount of chocolate was included.",
  "art_16_s025": "I put a small flake of chocolate in the coffee.",
  "art_16_s026": "He also took a sandwich with giblets from a goose - usually you eat that on Martin of Tours' Eve, but why cross out a good thing just because it is the wrong season?",
  "art_16_s027": "The food could also contain a little cognac for the flavor.",
  "art_17_s001": "\"What did I do yesterday?\" I asked in a short letter.",
  "art_17_s002": "\"Do you know what I did yesterday...?\"",
  "art_17_s003": "Yesterday I decided to explore our beautiful nature.",
  "art_17_s004": "I left my villa garden and my regular garden behind me.",
  "art_17_s005": "There was a beautiful rose with red rose petals that smelled wonderful, but I wanted to go out.",
  "art_17_s006": "I am very interested in our environment and a popular outdoor life.",
  "art_17_s007": "\"What particular event made you go away?\" my friend wondered.",
  "art_17_s008": "Well, I felt dissatisfied with just sitting at home.",
  "art_17_s009": "To get new energy, I started to walk the dog.",
  "art_17_s010": "I bought a flashy jacket and we went north.",
  "art_17_s011": "We walked a long distance up a mountain, where there was still some snow.",
  "art_17_s012": "In nature you can experience a lot.",
  "art_17_s013": "A cat or a dog is a good companion animal and pet, but seeing wild animals in a forest is better than in a zoo.",
  "art_17_s014": "There were hundreds of small animals there, among others a small deer and a singing bird.",
  "art_17_s015": "I also saw a large butterfly, more beautiful than any in an old butterfly collection.",
  "art_17_s016": "I had to stand by a large tree, which was an old birch, and saw yellow resin.",
  "art_17_s017": "Unfortunately, you often have to sublet a space in an ugly parking lot, sometimes built by order of a politician.",
  "art_17_s018": "Nature is no longer as free.",
  "art_17_s019": "Our beautiful lake next to a large sea is almost completely emptied of fish due to all the pollution.",
  "art_17_s020": "It is a difficult situation that sometimes feels as if it began in the Middle Ages, and the next generation must succeed us and do it better.",
  "art_17_s021": "At the end of the day I saw a magical sunset and thought about space and a bright moon.",
  "art_17_s022": "It was as dramatic as a character in a classic Strindberg play.",
  "art_17_s023": "A homemade juice warmed me.",
  "art_17_s024": "\"Don't miss the next sunrise,\" I said to myself.",
  "art_17_s025": "It is important that children get to grow up in a healthy world without a large pit of garbage.",
  "art_18_s001": "\"Help me!\" shouted my friend when we were mountain biking.",
  "art_18_s002": "The track was curved and a bit tricky.",
  "art_18_s003": "\"Now I don't understand.\" she continued.",
  "art_18_s004": "We were in the north, in a large wilderness area.",
  "art_18_s005": "My friend works as a pedagogue and loves our wonderful nature.",
  "art_18_s006": "We had gone here to experience everything from Bergmanesque drama to a quiet birch forest.",
  "art_18_s007": "I wanted to reconstruct a scene from the movie \"The Seventh Seal\".",
  "art_18_s008": "My friend laughed and thought it was better to get something to eat or drink.",
  "art_18_s009": "It was a good time as a warm sun was shining.",
  "art_18_s010": "We sat down by a beautiful flower which was also our local provincial flower.",
  "art_18_s011": "She started teaching me every plant name and explained that you can plant them to get a natural and ecological decoration around your wooden house.",
  "art_18_s012": "\"Did you know that two thirds of Sweden's surface is forest?\" she asked.",
  "art_18_s013": "It used to arouse interest in every climate debate.",
  "art_18_s014": "In a large river, our country's second largest, one could swim and fish.",
  "art_18_s015": "Sweden's third largest lake is also popular.",
  "art_18_s016": "Along the west coast the environment is more rocky.",
  "art_18_s017": "There we usually visit the outermost archipelago and build small windbreaks.",
  "art_18_s018": "There are nice sea baths where the children usually fish for crabs and look for fun shellfish.",
  "art_18_s019": "Once we went on a seal safari and got to see a living seal.",
  "art_18_s020": "It was almost as big as in life-size at the museum.",
  "art_18_s021": "Some seals felt almost as fearless as a tame dog.",
  "art_18_s022": "My friend's best tip was to hike in the mountains.",
  "art_18_s023": "You walk slowly over stone after stone and pick cloudberries or wild strawberries.",
  "art_18_s024": "You can also come across a beautiful provincial animal.",
  "art_18_s025": "In the evening, strange things can happen.",
  "art_18_s026": "Before the sun goes down you have to make camp.",
  "art_18_s027": "It is beautiful to see how the colors in the air end in red.",
  "art_18_s028": "But if you are at the very top of the country you get to see a midnight sun and a bright star.",
  "art_18_s029": "Due to a lack of communication, the area is quiet.",
  "art_18_s030": "Some build an ultra-modern cabin, but the old always wins.",
  "art19_s001": "\"-Hi! It's been a long time!\" I said when I met my old friend in the forest.",
  "art19_s002": "\"What?\" she said. Then she recognized me.",
  "art19_s003": "\"I have to tell you a thing/a thing...\" she began. \"Have you heard what XX did?\" she asked and smiled.",
  "art19_s004": "\"No, I have no opinion on celebrities,\" I answered firmly.",
  "art19_s005": "\"Have you/you heard that?\" she joked, \"he supposedly has plans to abdicate from his job as a personal trainer!\" Her story felt like a fun abdication from seriousness, but it was nice to be out in nature.",
  "art19_s006": "\"Have you heard of...?\" she asked and pointed to an old flat rock. \"There is a petroglyph from an early century. There was a Catholic who was known for having traveled here pulled by six horses.\"",
  "art19_s007": "She had a red- and white-striped jacket and a mint green hat. We sat down among the trees. \"There is a misconception about the forest. Some believe that animals will attack, but they are often innocent,\" she said. We bought some pick-and-mix candy and put a dollop of jam on a piece of bread. She asked about my vegan sausage made of oats.",
  "art19_s008": "\"Have you ever eaten it?\" I asked.",
  "art19_s009": "\"No, I have never done that!\" she laughed. She couldn't help but taste it. The taste was really strong and made her eyes sting.",
  "art19_s010": "Then we talked about our nature. \"In the 70s during a boom, the green wave started to break through. People wanted a natural cycle for everything from rain to sewage,\" she said. Today, a modern environmental movement is important in every environmental and climate debate. The word climate appears in every tag cloud online.",
  "art19_s011": "Many young people want to get involved in the environment. Even my little goldfish seems to want clean water! \"It is hard to have time to build a strong protection against pollution, but we must motivate more people to accept the facts and not exaggerate the fear,\" she said. Sometimes it feels like we are speaking in Greenlandic, no one understands each other. A name for the problem is ignorance. It felt good to name the problems and hopefully get hope back. Before we left we threw a snowball at a small orange tree in a greenhouse. We risk getting problems if we don't act, but we keep fighting!"
}
with open("translations_1.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
