import json

data = {
  "art_50_s001": "Hello Maria!",
  "art_50_s002": "Guess what?",
  "art_50_s003": "It is true that times really change fast.",
  "art_50_s004": "Early this morning I drank coffee in my warm bathrobe.",
  "art_50_s005": "My boyfriend then said that he wanted to get married next year.",
  "art_50_s006": "We have a strong relationship and a very good connection, but we also talk about how common divorce unfortunately is.",
  "art_50_s007": "People want to socialize, but a lot is still not like before.",
  "art_50_s008": "There was suddenly a lot of talk about his large extended family and all their children.",
  "art_50_s009": "Every parent always wants the best, of course.",
  "art_50_s010": "I hope that we get to be happy.",
  "art_50_s011": "He was married before, and his ex-wife apparently got mad as a hornet when she thought he had met a new lover.",
  "art_50_s012": "You can sometimes get angry and need to get used to the situation, because it takes time to get used to new things.",
  "art_50_s013": "During our last long weekend we all went up to the country.",
  "art_50_s014": "We had hired a young babysitter for some small schoolchildren from another family with children.",
  "art_50_s015": "The children loved old fairy tales.",
  "art_50_s016": "We used to often remind them of stories like Little Red Riding Hood and the Wolf and also Peter and the Wolf.",
  "art_50_s017": "Maybe one of you also remembers how exciting it was?",
  "art_50_s018": "A real wolf can of course look dangerous and even lethal, with an impressively large height at the withers.",
  "art_50_s019": "If you meet one, you might need to turn the car around quickly or turn around in the forest.",
  "art_50_s020": "Luckily, they are quite rarely seen in general.",
  "art_50_s021": "The wolf is, as you know, the dog's famous ancestor.",
  "art_50_s022": "Then we visited a local moose farm together.",
  "art_50_s023": "Their absolute best selling point was that visitors got to pet the moose at regular times.",
  "art_50_s024": "It is apparently an expanding tourism industry with rapidly increasing popularity.",
  "art_50_s025": "There were twelve people there at the same time.",
  "art_50_s026": "No one felt afraid, with one single exception.",
  "art_50_s027": "There was an unofficial rule there that said you must have an approved zookeeper with you to be able to control everything.",
  "art_50_s028": "Then you could suddenly remember that their old motto was that the animals must still be treated with full respect.",
  "art_50_s029": "At the end... of the whole day we were all extremely tired and satisfied.",
  "art_50_s030": "Keep in touch!",
  "art_50_s031": "Hugs and kisses ...",
  "art_51_s001": "\"How does it look?\" asked my happy single friend.",
  "art_51_s002": "We stood in the middle of the room and looked out over an enormous arrangement.",
  "art_51_s003": "It had been quite a long time since we last met.",
  "art_51_s004": "He was my bestie, an incredibly handsome buddy and a very close friend ever since my youth.",
  "art_51_s005": "He was often a real exercise addict and sometimes even a stressed workaholic.",
  "art_51_s006": "I myself was more like a normal, calm person.",
  "art_51_s007": "I was nervous about this day.",
  "art_51_s008": "We were invited to an exclusive party to celebrate my grandfather and grandmother.",
  "art_51_s009": "They had invited over a hundred guests in total.",
  "art_51_s010": "Both my paternal and maternal grandparents really liked gathering all the small grandchildren, some nice villagers, local school staff, and also my older sister.",
  "art_51_s011": "It felt like a genuine, warm childhood memory.",
  "art_51_s012": "The family was very well known in our small area, they were almost like a rich old noble family.",
  "art_51_s013": "\"I especially remember when your grandfather told his long, fascinating family chronicle,\" he said.",
  "art_51_s014": "\"The story could be quite cruel, often with some mean person in the center, but the fairy tale always had a happy ending.",
  "art_51_s015": "It is a type of story you really love.\"",
  "art_51_s016": "During the long party we ate delicious cake with almonds and listened to happy music from a slightly scratched CD.",
  "art_51_s017": "An invited member of parliament and a very proud Sami gave beautiful speeches to our entire country, much like a tribute to Mother Svea.",
  "art_51_s018": "The whole thing had a very important and serious function in this exact context.",
  "art_51_s019": "\"Do you think it's okay if I try to mix up these guests a bit?\" my friend asked jokingly, and I saw that he was obviously in love with someone new at the party.",
  "art_51_s020": "He wanted to show up in exactly the right place at the right time.",
  "art_51_s021": "\"Yes absolutely, enjoy and laugh as much as you can,\" I replied.",
  "art_51_s022": "I didn't want to hate love at all, of course.",
  "art_51_s023": "\"I think romance is wonderful.",
  "art_51_s024": "One must not be uncomprehending of it.\"",
  "art_51_s025": "\"Rumor has it that our neighbor wants to remarry,\" he then joked happily.",
  "art_51_s026": "\"Do you think my old story from the previous year could be true?\" Grandpa suddenly said out of nowhere.",
  "art_51_s027": "It was a very unexpected question from him.",
  "art_51_s028": "\"Who doesn't want to hug and kiss someone they really like?\" Grandpa smiled.",
  "art_51_s029": "He had recently received an interesting proposal.",
  "art_51_s030": "He wanted to sign an important paper about the old farm that was beautifully located by a large intersection.",
  "art_51_s031": "He really loved the farm.",
  "art_51_s032": "\"Here you can sometimes lie down on the soft grass, look up and feel completely invisible in the world.",
  "art_51_s033": "I really like this kind of... quiet and peaceful place.\"",
  "art_51_s034": "\"Hope to see you soon!\" shouted all the happy guests when they then had to return home in the dark, starry night.",
  "art_52_s001": "\"What are you doing there?\" my dad shouted when he came into the room.",
  "art_52_s002": "I was in my own thoughts, sitting and trying to philosophize about my secret dream of the future.",
  "art_52_s003": "There was a strong belief in the future inside me.",
  "art_52_s004": "\"I am trying to look for an old package that I lost,\" I answered.",
  "art_52_s005": "\"You won't believe your ears!\" Dad continued with great surprise in his voice.",
  "art_52_s006": "A chairman from an international association had just called.",
  "art_52_s007": "My old uncle, who actually worked in graphic design and often traveled to make contacts, had sent a strange letter.",
  "art_52_s008": "Uncle was a very calm northerner, more specifically a proud Norwegian.",
  "art_52_s009": "In his youth he had sometimes worked as a test subject in various studies, and was often a central protagonist in the family's most dramatic stories.",
  "art_52_s010": "We started talking about our large language family and the joy of preserving our mother tongue.",
  "art_52_s011": "I tried to remember when my father and mother always said that a deep interest in languages must run in the family.",
  "art_52_s012": "But my uncle had a completely different reason to get in touch now.",
  "art_52_s013": "Furthermore, my niece and another daughter of my brother had come to listen.",
  "art_52_s014": "Uncle had apparently entered into an important agreement with a famous Japanese person to give away a unique friendship gift, a rare carnation, but he had told a little white lie about its true origin.",
  "art_52_s015": "Uncle was usually very careful never to shift his gaze when he spoke, but quite the contrary, he always wanted to meet one's gaze confidently.",
  "art_52_s016": "He used to proudly say, \"You must always be able to trust me.\"",
  "art_52_s017": "However, he now felt a deep shame over the lie and he had begun to feel guilt.",
  "art_52_s018": "\"It is a shame for... well, for our entire family,\" my dad said, although he was probably exaggerating a bit.",
  "art_52_s019": "He said it felt like a very cowardly lie.",
  "art_52_s020": "It was of course not a terrible crime, absolutely not hate speech, but still wrong.",
  "art_52_s021": "Dad absolutely did not want to fight with Uncle, but there was a clear reason why I was a bit disappointed in him.",
  "art_52_s022": "My dad asked us to help serve coffee and try to agree on how we would describe this to Uncle once he returned.",
  "art_52_s023": "\"We have to try to make the best of a bad situation,\" I said.",
  "art_52_s024": "Our main question was how we could get him to let go of his heavy anxiety.",
  "art_52_s025": "We wanted him to feel loved despite his mistake.",
  "art_52_s026": "Even if you feel like you have a knife to your throat, you shouldn't judge too quickly, thought our wise speaker of a mother.",
  "art_53_s001": "Hi ... Anna!",
  "art_53_s002": "How's it going?",
  "art_53_s003": "Now we have arrived in... our beautiful old city, and I feel great.",
  "art_53_s004": "I have to tell you something... something incredible that just happened.",
  "art_53_s005": "Oh my god, you won't believe it!",
  "art_53_s006": "An old Nordic relative of mine suddenly showed up here.",
  "art_53_s007": "He is known to be very handy and reliable, a genuinely decent man.",
  "art_53_s008": "Many usually consider him to be enormously wealthy and rich.",
  "art_53_s009": "\"You're kidding!\" I said when he spontaneously came here.",
  "art_53_s010": "He proudly said that his latest development at work was a great success, much thanks to his stubbornness.",
  "art_53_s011": "He is usually extroverted and talkative, but seemed a bit worried.",
  "art_53_s012": "He secretly revealed that he thought I was too careless and maybe even quite lazy.",
  "art_53_s013": "It was a terrible and downright mean thing to say.",
  "art_53_s014": "He was impolite and actually made a really stupid comment.",
  "art_53_s015": "I really didn't want to be fake, so I got upset and not happy at all.",
  "art_53_s016": "One has to be able to concentrate to always be kind.",
  "art_53_s017": "He wanted to ask for more coffee, and also took the opportunity to ask for my help in applying for a big job on a large scale for a friend.",
  "art_53_s018": "He often used to make a habit of exploiting people's kindness.",
  "art_53_s019": "I thought his behavior was the same as being selfish.",
  "art_53_s020": "In the past, people often discussed clear gender roles and foreigners talked about \"The Swedish sin\", but in today's society, all true success requires having a good inner trait like great patience.",
  "art_53_s021": "It is important to be harmonious in order for one's dreams to become a reality.",
  "art_53_s022": "In the end, we were still able to come up with a good solution.",
  "art_53_s023": "He apologized and I promised to answer his questions to put an end to the conflict.",
  "art_53_s024": "We discussed his news and some small problems.",
  "art_53_s025": "I started telling him about my plans.",
  "art_53_s026": "It is usually said that the more... the better, and we talked for a long time.",
  "art_53_s027": "We waited until the storm was over.",
  "art_53_s028": "Then he took off quick as a flash.",
  "art_53_s029": "I am, after all, happy and very grateful that we have a much more meaningful relationship, you and I.",
  "art_53_s030": "I can recommend that you travel here soon.",
  "art_53_s031": "Warm greetings to you!",
  "art_53_s032": "Miss you!",
  "art_54_s001": "Hi ...\nDear ... Anna,\nAll well?",
  "art_54_s002": "Is everything good with you?",
  "art_54_s003": "Everything is great here on my new vacation.",
  "art_54_s004": "Have you heard what happened?",
  "art_54_s005": "Such a funny thing happened... last Saturday when I was going to give an old acquaintance a ring.",
  "art_54_s006": "Do you know who I met?",
  "art_54_s007": "I met Peter!",
  "art_54_s008": "Don't you know why...?",
  "art_54_s009": "He has actually moved back, even though he enjoyed it abroad.",
  "art_54_s010": "\"Is it true?\" I asked him.",
  "art_54_s011": "He was quick as a flash to greet me with a polite and pleasant bow.",
  "art_54_s012": "He said that nowadays he looks very trendy and adventurous.",
  "art_54_s013": "It was a real highlight of the day, a feeling of pure happiness to see him.",
  "art_54_s014": "I couldn't help but fantasize about old times, everything felt like history in a nutshell.",
  "art_54_s015": "We used to always support each other and he was a brave role model for me.",
  "art_54_s016": "He wanted to develop his ideas and was very loyal and extremely honest.",
  "art_54_s017": "\"Are you... planning to move here now?\" I asked.",
  "art_54_s018": "He said yes, but he had a tendency to quickly change his mind.",
  "art_54_s019": "You have to be careful not to completely lose yourself in a city.",
  "art_54_s020": "He thought the city had become very old-fashioned and that he had not found peace anywhere, neither here nor anywhere else.",
  "art_54_s021": "\"You can't live off others,\" I said.",
  "art_54_s022": "\"You have to be kind and not lousy.\"",
  "art_54_s023": "\"No, ugh.\" he said.",
  "art_54_s024": "\"I would never be impolite.",
  "art_54_s025": "That is not a good trait.\"",
  "art_54_s026": "He was not happy having to be without money.",
  "art_54_s027": "Suddenly a hysterical woman came up and threw a bag right in his lap!",
  "art_54_s028": "She wore a strange, pungent perfume.",
  "art_54_s029": "\"Stop it!\" he yelled.",
  "art_54_s030": "He explained that the woman thought he wanted to have an affair with her.",
  "art_54_s031": "It is sometimes difficult to get to know people properly and you don't have time to know someone well before problems arise.",
  "art_54_s032": "\"For how long?\" I asked him surprised.",
  "art_54_s033": "\"A good while,\" he sighed quietly.",
  "art_54_s034": "\"Don't pay attention to... her.",
  "art_54_s035": "She is an established but completely hopeless person, yes, imagine always having to argue.\"",
  "art_54_s036": "I felt compelled to sink down in my chair and think further.",
  "art_54_s037": "I hope we can meet soon and enjoy a cozy fika.",
  "art_54_s038": "\"Take care!\" and \"You too.\" is what we usually write.",
  "art_55_s001": "A new life with a friend\n\nIn my early childhood I knew a kind, old woman.",
  "art_55_s002": "Her life was very fascinating.",
  "art_55_s003": "She used to write a long entry in her diary every evening about her thoughts.",
  "art_55_s004": "Unfortunately, her husband was often away on trips, and his business sometimes went badly.",
  "art_55_s005": "He was quite unreliable and often unhappy about this.",
  "art_55_s006": "To avoid being alone, she chose to buy a dog.",
  "art_55_s007": "It was a traditional and loyal breed.",
  "art_55_s008": "The new dog gave her immense joy, a real boost of happiness in everyday life.",
  "art_55_s009": "The dog was faithful, sociable, and incredibly helpful at home.",
  "art_55_s010": "He was as calm as could be indoors and was never ever aggressive.",
  "art_55_s011": "She wanted everything in life to be as... as possible, almost perfect.",
  "art_55_s012": "The dog had a huge significance for her fellowship with other people.",
  "art_55_s013": "She used to nag the dog to always be obedient and sometimes graceful, but the dog was instead quite clumsy and very playful.",
  "art_55_s014": "He was mischievous and often ran off, only to quickly follow her home again shortly after.",
  "art_55_s015": "He was curious about everything new, but sometimes he seemed a bit stupid.",
  "art_55_s016": "All the old woman's friends, and also her loved ones, immediately thought the dog was cute.",
  "art_55_s017": "He was independent, but could also sometimes scare the neighbors when he suddenly went crazy and ran around in circles.",
  "art_55_s018": "Once they found an old, dirty hundred-krona bill that the dog happily pulled out of a bush with his wet nose.",
  "art_55_s019": "They then each got an ice cream.",
  "art_55_s020": "The old woman was always generous and she used to regularly pay out some money to charity.",
  "art_55_s021": "She might have been old but still very inventive.",
  "art_55_s022": "A really exciting breakthrough actually came when she suddenly became a very successful local dog trainer.",
  "art_55_s023": "That way she could double her small income, which created a continued stable and good economy for her.",
  "art_55_s024": "\"You never need to be afraid of a nice dog,\" she often said.",
  "art_55_s025": "The dog never got stressed or desperate, and she herself was never afraid in his safe company.",
  "art_55_s026": "\"Sometimes a normal day can feel boring,\" she often said.",
  "art_55_s027": "\"But then you simply have to accept the situation and try to look on the bright side of something nice that is still happening.",
  "art_55_s028": "A good dog is truly a true friend.",
  "art_55_s029": "Everything felt just like before when he was there.\"",
  "art_55_s030": "A nice memory I have is how she used to whisper quietly to the dog and smile broadly at him.",
  "art_55_s031": "\"We will always miss you when you go away,\" she told me, and I felt exactly the same about her.",
  "art_55_s032": "She was always very understanding and enormously positive.",
  "art_55_s033": "She always ended her nice little letters to me with the words kiss kiss.",
  "art_56_s001": "The man on our little island\n\nIt is said that... one can easily be bored in the countryside.",
  "art_56_s002": "I live on a lovely island, and I am proud to be a country person.",
  "art_56_s003": "There is a man here who usually invites people for dinner under his large, blue roof.",
  "art_56_s004": "He is known as the village's bald man.",
  "art_56_s005": "He was married to a nice woman, and their long marriage felt like a singing beautiful dream.",
  "art_56_s006": "She moved and since then he feels a great sorrow.",
  "art_56_s007": "Many neighbors felt sorry for him.",
  "art_56_s008": "He wanted to cook good food for everyone and try to attract guests to create a good atmosphere in the house.",
  "art_56_s009": "He said that the fact is he really wanted to be a man of honor and help with the village's development.",
  "art_56_s010": "You can call him a fantastic man of honor in many ways.",
  "art_56_s011": "His strong identity was built on always telling the truth.",
  "art_56_s012": "He often said: \"Do you understand?",
  "art_56_s013": "You must never gossip about your neighbors.\"",
  "art_56_s014": "He could give advice to exactly everyone who needed it.",
  "art_56_s015": "He even used to light a candle for those he thought of and wanted to admire.",
  "art_56_s016": "But a new man moved to the village.",
  "art_56_s017": "He was a real mythomaniac and a dangerous liar.",
  "art_56_s018": "He just wanted to trick and fight.",
  "art_56_s019": "He was very quick-thinking and seemed serious on the surface, but was quite unpleasant on the inside.",
  "art_56_s020": "He immediately started squirming when asked deep questions.",
  "art_56_s021": "His strange behavior was very annoying, but still you unfortunately became a little intrigued by his wild stories.",
  "art_56_s022": "\"How fast?\" we often asked when he proudly told an unlikely version of an event.",
  "art_56_s023": "He was a non-smoker, and he never wanted to keep his aggressive dog on a leash.",
  "art_56_s024": "He was not at all controlled.",
  "art_56_s025": "It soon turned out that his words were not an obvious truth at all.",
  "art_56_s026": "We completely stopped believing his stories.",
  "art_56_s027": "He liked to use English expressions and often spoke with words like \"one's\" to appear international.",
  "art_56_s028": "\"Is that an acceptable forecast for our village?\" said the chairman with a deep sigh.",
  "art_56_s029": "Everything was definitely not all peace and joy anymore.",
  "art_56_s030": "He often wanted to promise to be kind, but he only got sulky when we questioned him.",
  "art_56_s031": "\"Absolutely incredible!\" we said.",
  "art_56_s032": "He wanted to be like a good person, and we carried a little hope that he would change.",
  "art_56_s033": "But he didn't dare to stay, and therefore a mandatory move became the only choice."
}
with open("teacher_validated_5.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
