import json

data = {
  "art_00_s001": "Every morning we start a new day in a fantastic world full of technological solutions.",
  "art_00_s002": "It is incredible to see how much modern technology can affect our lives and our everyday lives.",
  "art_00_s003": "Many years ago, physical labor was very common in society, and people had to use a lot of energy from their own bodies to survive and manage their jobs.",
  "art_00_s004": "Today we don't really need to work as hard physically, because of our smart machines and systems that do the job for us.",
  "art_00_s005": "Nowadays, instead, many sit in front of a computer all day at the office.",
  "art_00_s006": "My good friend is a civil engineer and he has developed his very own method for working more efficiently.",
  "art_00_s007": "He uses advanced mathematics and various digital tools to solve complex problems in his project.",
  "art_00_s008": "His wife is a geologist and she examines nature.",
  "art_00_s009": "It is a fun hobby, so they both like geology and astronomy in their spare time.",
  "art_00_s010": "It would really be extremely difficult to function in society without electricity today.",
  "art_00_s011": "If, for example, we did not have fast broadband, we would be forced to wait a very long time for all kinds of information from the outside world.",
  "art_00_s012": "I guess that less than half of us regular people actually understand all the complicated technology we use.",
  "art_00_s013": "You can easily make a mistake when choosing a good tool for your work.",
  "art_00_s014": "Sometimes it feels like there is too much information everywhere.",
  "art_00_s015": "Last night I sat surfing, and I found a lot of information online.",
  "art_00_s016": "There was an exciting statistic that clearly showed that we spend on average about three hours every evening in front of a TV screen in the living room.",
  "art_00_s017": "Many people really like to watch TV in the evening to relax after work.",
  "art_00_s018": "A modern TV or a smart television set now has very many fantastic features, but you might wonder which one to buy to get the best picture.",
  "art_00_s019": "We also have a great opportunity to learn new exciting things via the internet, for example completely new languages or cultures.",
  "art_00_s020": "Early in the morning I often read an email from work.",
  "art_00_s021": "Then, when I walk to the bus, I can quickly send a text message to my family or make an important phone call to a colleague.",
  "art_00_s022": "In the midst of all this technology, it is very important not to forget your body.",
  "art_00_s023": "You can benefit from participating in various sports on the weekends, since regular physical activity is crucial for our health.",
  "art_00_s024": "Naturally, not all people have the same strength and not everyone has the energy to exercise absolutely every day of the week.",
  "art_00_s025": "You simply have to find the right balance in life to feel good in the long term.",
  "art_00_s026": "Of course, how you feel can vary a lot from day to day.",
  "art_00_s027": "But by being able to use technology at a high level and at the same time moving around, we get more time left over for each other.",
  "art_01_s001": "When you go to work, it is surely a common routine to turn on the computer as the very first thing you do.",
  "art_01_s002": "But have you ever wondered how everything inside the machine actually works?",
  "art_01_s003": "Before I chose to take a practical computer course, I knew almost nothing about the details of modern technology.",
  "art_01_s004": "Now I understand that it is about more than just a simple screen; it is an entire system of information.",
  "art_01_s005": "Every year thousands of experts try to invent new equipment that will make our lives easier.",
  "art_01_s006": "A very famous scientist worked many hundreds of years ago on observing and systematizing new knowledge.",
  "art_01_s007": "By using a special and careful method, he could quickly calculate distances in space and measure exact temperatures.",
  "art_01_s008": "He often studied the light of the stars carefully through a large telescope.",
  "art_01_s009": "He was a really good astronomer who stood every evening and looked up at a beautiful starry sky.",
  "art_01_s010": "In the middle of the dark room stood his fine working tool.",
  "art_01_s011": "Research is not always an easy process.",
  "art_01_s012": "Often there is an invisible power struggle between different new ideas, where an untested theory must stand against another.",
  "art_01_s013": "Researchers always build their hard work on real facts, not on fantasies.",
  "art_01_s014": "Most are deeply interested in solving difficult problems to help each other in the best way.",
  "art_01_s015": "According to Swedish statistics, the result is one hundred percent certain.",
  "art_01_s016": "The fact is that about twenty percent of the attempts might fail, but you learn an incredible amount from them as well.",
  "art_01_s017": "Today we live in a world where we are constantly connected to the internet.",
  "art_01_s018": "There is some type of small electric motor in almost all our machines at home.",
  "art_01_s019": "Today we can simulate very complicated processes directly on the screen, long before we build them in reality.",
  "art_01_s020": "This modern work sometimes requires high intelligence and a fantastic intellectual ability.",
  "art_01_s021": "You can now sit comfortably and look through information from all over the world, completely without leaving your chair.",
  "art_01_s022": "On average, modern people spend a lot of time online.",
  "art_01_s023": "A fairly common question is whether we are developing too fast, or if on the contrary we are too slow.",
  "art_01_s024": "Regardless of what we might think about the matter, technology continues to move forward.",
  "art_01_s025": "You can measure an object's length, weight and width, but the future is harder to measure.",
  "art_01_s026": "We can see, among other things, that our popular technology, including our phones, is the most useful thing we have.",
  "art_01_s027": "You can calmly finish your day by watching funny movies, then you are ready for the next exciting day.",
  "art_02_s001": "My friend Anna is a librarian and normally likes to read books in peace.",
  "art_02_s002": "But last week she decided to go away on a long trip abroad during her time off.",
  "art_02_s003": "\"It is time to go on a real vacation,\" she happily told me.",
  "art_02_s004": "She had very heavy luggage because she planned to hike in the mountains.",
  "art_02_s005": "Before she was to walk to the station, she carefully packed a map and a compass in her bag.",
  "art_02_s006": "\"Prices have gone up,\" she thought, so she chose a cheap hostel in a small town instead of an expensive luxury hotel.",
  "art_02_s007": "She had also planned to take the train, since it is a good way to see a long railway line.",
  "art_02_s008": "But unfortunately the train was cancelled, so she had to take the bus.",
  "art_02_s009": "A kind bus driver helped her with her bag when she got on the bus.",
  "art_02_s010": "Soon she had arrived.",
  "art_02_s011": "When you are on your way to a new place, everything is very exciting.",
  "art_02_s012": "She quickly decided to go down to a sunny beach to rest.",
  "art_02_s013": "That way she could enjoy the fresh nature.",
  "art_02_s014": "Then she wanted to go to a big city to visit museums and see historical exhibitions.",
  "art_02_s015": "After four days in nature she felt completely done.",
  "art_02_s016": "\"I have to know what is in the city,\" she thought and rented a practical room in the center.",
  "art_02_s017": "Her new room was actually no smaller than the first one.",
  "art_02_s018": "In the morning she went downtown to visit a famous market.",
  "art_02_s019": "She was so happy that she wanted to run down the entire street.",
  "art_02_s020": "She then chose to go out with her camera on a long street.",
  "art_02_s021": "There she saw someone riding a horse past a large car.",
  "art_02_s022": "It was a perfect experience, and she finally began to understand how fun it really is to travel.",
  "art_02_s023": "She tried to save all the memories.",
  "art_02_s024": "Later that week she sent a message: \"You should come and visit me.\"",
  "art_02_s025": "So I decided to go and visit her for a short visit.",
  "art_02_s026": "\"Take the same route you came,\" she said when I asked for directions.",
  "art_02_s027": "I could see that her great joy would fill my entire day.",
  "art_02_s028": "When my time began to run out, it was unfortunately time to go home.",
  "art_02_s029": "We will keep in touch and I will contact her directly the next time I want to travel.",
  "art_02_s030": "I could see their interesting culture and it was best to keep our eyes open and just walk past all the beautiful old houses along every road.",
  "art_03_s001": "\"What happened yesterday?\" asked my friend, who was very eager to travel.",
  "art_03_s002": "\"Do you know what happened yesterday?\" she then asked quickly.",
  "art_03_s003": "I replied that it was a long story.",
  "art_03_s004": "We had decided to take a road trip in a big, nice and fast sports car that was going to be inherited from my uncle.",
  "art_03_s005": "Our plan was to camp all year round and see the whole country.",
  "art_03_s006": "The Swedish tourism industry is strong, and every tourist can get help at a local tourist information center.",
  "art_03_s007": "We started our trip with a long walk in a beautiful archipelago.",
  "art_03_s008": "There were many small islands there that could form the foundation for a fantastic experience.",
  "art_03_s009": "Between the islands there was water, and we had to use a rowboat to get around in a small harbor.",
  "art_03_s010": "There was a good and stable pier there.",
  "art_03_s011": "Two men spoke to us and wanted to take us on a guided tour.",
  "art_03_s012": "They said that the mountains began to rise out of the sea.",
  "art_03_s013": "It could get dark, but everything was very beautiful.",
  "art_03_s014": "But suddenly a bear came out of the forest and seemed to attack, although it was really just scared.",
  "art_03_s015": "\"Bears usually hibernate in winter,\" the guide said and calmed us down.",
  "art_03_s016": "On Sunday we took a quiet Sunday walk on an old path.",
  "art_03_s017": "There we received a flyer from a young street vendor.",
  "art_03_s018": "The text on the flyer was about a big sailing race and about how to form teams with other people.",
  "art_03_s019": "\"Do you know when the buses leave?\" my friend asked, because we were tired of walking and wanted to ride on the next bike path to see the town of Tain in Scotland.",
  "art_03_s020": "I know it is far, but dreams are free.",
  "art_03_s021": "Our luggage was starting to weigh a lot.",
  "art_03_s022": "We wanted to get out of the forest, so we decided that we would go there another time.",
  "art_03_s023": "Now it is winter and there is road salt on every winter road, which is a must according to our constitution for safety.",
  "art_03_s024": "It can be a scary experience to drive when it is slippery.",
  "art_03_s025": "Both my friends are home now, and we are ready to set out on new adventures during our next time off.",
  "art_03_s026": "Moving around is always good.",
  "art_03_s027": "Who knows where we will go next time?",
  "art_04_s001": "My friend, who is originally from a small village up north, likes to travel.",
  "art_04_s002": "She wanted to get away from her usual city, because she felt a big change rapidly approaching.",
  "art_04_s003": "She had been away several times and now it was time for a new long stay.",
  "art_04_s004": "As a newcomer in a new city, she often felt lonely, so travelling gave her support.",
  "art_04_s005": "\"I want to experience a view stretching for miles and visit an old fortress,\" she started saying.",
  "art_04_s006": "\"Oh, really!",
  "art_04_s007": "Do you really want to?\" I asked.",
  "art_04_s008": "She nodded.",
  "art_04_s009": "First she would take a flight, have a layover, and then take a passenger ferry.",
  "art_04_s010": "After her arrival she would rent a vehicle to travel many miles to the coast.",
  "art_04_s011": "\"Close your eyes,\" she said when we listened to a local radio broadcast about travel.",
  "art_04_s012": "When she finally arrived at the water, she decided to rent a kayak.",
  "art_04_s013": "\"You must have good balance in a kayak so as not to drown,\" a nice hotel owner said.",
  "art_04_s014": "There were all sorts of boats there, even an old longboat and a large ship.",
  "art_04_s015": "She let the kayak glide forward across the water.",
  "art_04_s016": "She chose to just go with the flow and gradually relax.",
  "art_04_s017": "She could see children running around on the beach and a dog running loose.",
  "art_04_s018": "In the evening she ate prunes and thought about her departure from her old life.",
  "art_04_s019": "An older man, dressed like a cardinal, told stories about men who used to carve names into stones and found new cities all over the world.",
  "art_04_s020": "\"Search within yourself,\" he said.",
  "art_04_s021": "Everything seemed to flow very well and it never felt like a disaster.",
  "art_04_s022": "She didn't want a half vacation, but an absolutely wonderful time.",
  "art_04_s023": "An unusual traveler always wants to go a little further away.",
  "art_04_s024": "In that way it never gets boring in the long run.",
  "art_04_s025": "I hope she wants to come back and make a return visit to me.",
  "art_04_s026": "It would be a shame to replace a certain part of life when it is not a bad thing, but I understood that she was happy when she went down to the sea.",
  "art_05_s001": "When talking about working life, many think of a good career.",
  "art_05_s002": "At first I planned to become a bank manager and work in the large financial world.",
  "art_05_s003": "But my career plan changed gradually.",
  "art_05_s004": "\"What does she do for a living?\" a friend asked.",
  "art_05_s005": "I told them that I had gotten a new job in a dark basement factory.",
  "art_05_s006": "It was a very unusual thing to choose an industry over sitting in an office.",
  "art_05_s007": "A regular workday is often long and tough.",
  "art_05_s008": "Sometimes I feel that it is a bad environment to work in such a tough working environment.",
  "art_05_s009": "But I like to change tasks and I always have the company of every colleague.",
  "art_05_s010": "You can also make new friends through colleagues.",
  "art_05_s011": "We are all part of the same trade union, which is important.",
  "art_05_s012": "They help us finance courses and ensure reasonable working hours.",
  "art_05_s013": "We do not want an extreme workweek.",
  "art_05_s014": "We also have a boss who sometimes wants to show who is in charge.",
  "art_05_s015": "A product manager often visits us and tells us what to do.",
  "art_05_s016": "But we are a hardworking group and try to create balance.",
  "art_05_s017": "Being high-paid is not easy in this industry.",
  "art_05_s018": "I am low-paid compared to the forest industry or the heavy mining industry.",
  "art_05_s019": "We also pay a certain tax on everything we can earn.",
  "art_05_s020": "Our salary is usually enough, but sometimes I have to work extra.",
  "art_05_s021": "We have several machines and we talked to our coworker and asked about a machine: \"What did you have to pay for that?\"",
  "art_05_s022": "The machines have to work well to avoid unemployment.",
  "art_05_s023": "When we are finally off, we try to enjoy a completely work-free weekend.",
  "art_05_s024": "It is nice to get away from work.",
  "art_05_s025": "After half a day of rest, it is time for household chores.",
  "art_05_s026": "It is exhausting to come home from work.",
  "art_05_s027": "But I am happy with my profession and hope to get a good internship in the future.",
  "art_05_s028": "My whole family thinks it is fun, as long as I do not get bogged down in stress.",
  "art_05_s029": "I heard my friend say that you should love your work.",
  "art_06_s001": "For many, a working life begins when they look for a job for the first time.",
  "art_06_s002": "\"What did she want to be?\" my boss asked.",
  "art_06_s003": "My friend was from a regular working-class family outside the city, whose parents were workers.",
  "art_06_s004": "She didn't want to become a priest, but wanted to work at a factory.",
  "art_06_s005": "She started as a summer worker.",
  "art_06_s006": "It was possible that they would hire her permanently immediately after the summer.",
  "art_06_s007": "\"How many years has she worked here?\" I asked.",
  "art_06_s008": "She was newly hired.",
  "art_06_s009": "The factory was a large food company.",
  "art_06_s010": "They had a good collaboration with a large television company.",
  "art_06_s011": "There was no other employer who could compete with their results.",
  "art_06_s012": "The company was perhaps a third as large as the largest in the world, but they were successful nonetheless.",
  "art_06_s013": "They planned to enter a partnership with a foreign partner, even though they needed a good tactic.",
  "art_06_s014": "In order to perform at the highest level, they had to set a clear goal.",
  "art_06_s015": "But it was not until a new boss took over that problems began to hit them.",
  "art_06_s016": "Some rules lacked logical sense.",
  "art_06_s017": "They had mail that always arrived late and they forgot to order office supplies.",
  "art_06_s018": "It was important that unions and staff got good working conditions and equal pay for equal work.",
  "art_06_s019": "Otherwise they could fire people.",
  "art_06_s020": "A boss said: \"I have a dream.\"",
  "art_06_s021": "He talked about freedom of movement and that one should refer to French methods.",
  "art_06_s022": "\"That fits well,\" a colleague said.",
  "art_06_s023": "\"We have to report everything we do.",
  "art_06_s024": "We will create new rules during my term of office and send them out.\"",
  "art_06_s025": "He took a lot of responsibility for his new role.",
  "art_06_s026": "He also told the employees: \"Please follow every instruction carefully.\"",
  "art_06_s027": "He asked us to be more creative and said that we must return everything we borrow.",
  "art_06_s028": "I wrote an email to him: \"I would be grateful if you could give me more time.",
  "art_06_s029": "Could you send more information after the meeting?",
  "art_06_s030": "Best regards, someone trying to be a professional at the back of the room.\"",
  "art_07_s001": "An exciting week at the office. \"I am writing to you to...\" my secretary began reading from a letter.",
  "art_07_s002": "The reason was that a PR consultant wanted to present a new project.",
  "art_07_s003": "It was a large construction project next to a new shopping center.",
  "art_07_s004": "\"It will be an exciting destiny for the city,\" our CEO said.",
  "art_07_s005": "He planned to invest in a new product.",
  "art_07_s006": "The factory would manufacture an expensive luxury item and hoped that it would become a bestseller.",
  "art_07_s007": "To launch it well, he needed good sales and trade.",
  "art_07_s008": "\"You have to contact someone who can help,\" he said.",
  "art_07_s009": "\"You could try.\"",
  "art_07_s010": "I am service-minded and good at my task.",
  "art_07_s011": "It was an important meeting.",
  "art_07_s012": "I was careful not to arrive late, but arrived exactly on time.",
  "art_07_s013": "To prepare, he had written some keywords on a board below the screen.",
  "art_07_s014": "A good trick is to use exactly the right title.",
  "art_07_s015": "\"We are going to decide on the future,\" he said.",
  "art_07_s016": "He wanted to demand that our staff collaborate more.",
  "art_07_s017": "Nowadays we also have to introduce new rules related to safety at every construction site.",
  "art_07_s018": "\"We need a lawyer and an accountant to sign contracts,\" he said.",
  "art_07_s019": "\"It can be a tough and stressful time.",
  "art_07_s020": "We cannot hide that the work can take a good month.\"",
  "art_07_s021": "\"I do not think so either,\" said an inspector who was there for security issues.",
  "art_07_s022": "We also talked about hiring a part-time pharmacist and a waitress for the canteen.",
  "art_07_s023": "\"I do not think that we should hire either of them right now,\" the CEO said.",
  "art_07_s024": "\"On another occasion they might get a chance.\"",
  "art_07_s025": "Everyone who wanted to become a member of the club got a paid place, and every member was satisfied.",
  "art_08_s001": "Starting a new education to learn a new language is always interesting.",
  "art_08_s002": "My course mate and I decided to take a course.",
  "art_08_s003": "Before we started at a university we planned to try a private tutor.",
  "art_08_s004": "We had read a survey from the 18th century about how different groups of people could get an education.",
  "art_08_s005": "It stated that children from the upper class used to be raised with their own tutor, while the working class and other social classes did not get the same chance.",
  "art_08_s006": "\"Why didn't she get any...?\" my friend wondered when she read about a poor girl.",
  "art_08_s007": "Today you can educate yourself to be whatever you want.",
  "art_08_s008": "The first day we had to turn the page in the book and read a sentence.",
  "art_08_s009": "\"You must pronounce every phrase correctly,\" the teacher said.",
  "art_08_s010": "She used to explain grammar, like word order and every word class.",
  "art_08_s011": "We learned the difference between nouns, adjectives and pronouns.",
  "art_08_s012": "We also talked about a gender-neutral word like hen.",
  "art_08_s013": "In class we had to write and answer questions.",
  "art_08_s014": "The teacher wanted to urge us to write down all the answer alternatives and note the correct answer.",
  "art_08_s015": "\"Check the answer key,\" she said, \"but try to formulate your own thoughts first.\"",
  "art_08_s016": "We often got the assignment to write a diary or write emails.",
  "art_08_s017": "\"What do you think?\" the teacher asked.",
  "art_08_s018": "\"Is it difficult?\"",
  "art_08_s019": "I answered that it was of course a little difficult, but good for testing one's limits.",
  "art_08_s020": "It could almost make your head hurt from all the new rules and you sometimes felt like gritting your teeth.",
  "art_08_s021": "Sometimes we also had a physical activity like a dance class after school.",
  "art_08_s022": "Then you could see a crowd of people.",
  "art_08_s023": "Afterwards you got to go home and blow-dry your hair.",
  "art_08_s024": "\"Watch out!\" my friend said, \"Here comes the last bus.\"",
  "art_08_s025": "When we went home she said: \"Who asked for you?\"",
  "art_08_s026": "I was so tired that I felt stone dead, but I had the energy to listen to her anyway.",
  "art_08_s027": "The past week was of the best kind.",
  "art_09_s001": "Studying has become more and more important for many, since you often want to get a degree.",
  "art_09_s002": "A school student in a regular school gets good teaching in subjects like math.",
  "art_09_s003": "To avoid problems, they often have to focus on calculating a lot.",
  "art_09_s004": "A good teacher can help with the aid of a good book.",
  "art_09_s005": "Sometimes the students get to translate an old proverb.",
  "art_09_s006": "A classic exercise is to circle or mark an underlined sentence in the text and read with the right emphasis.",
  "art_09_s007": "I decided to try a crash course in pedagogy.",
  "art_09_s008": "I wanted to do an internship at a preschool to see how a preschool teacher works.",
  "art_09_s009": "The one who was youngest in our class was only twenty years old, but still felt seen.",
  "art_09_s010": "He did not need to ask for permission to get a good lesson.",
  "art_09_s011": "Later he chose to study at a university to become a high school teacher.",
  "art_09_s012": "You can classify him as a future academic.",
  "art_09_s013": "At a university you can learn a lot, even about happiness research and other academic research.",
  "art_09_s014": "I know someone who wants to research how stress can reduce joy.",
  "art_09_s015": "Our principal told us that they were going to take over a course in Swedish for immigrants.",
  "art_09_s016": "My classmate wanted to protest against the fact that we were to have a big test by Friday at the latest.",
  "art_09_s017": "He felt almost as lost as a bear that has to lumber into a cage or stand pantless in front of everyone.",
  "art_09_s018": "But you have to prioritize and to a certain degree do your best.",
  "art_09_s019": "Most things have to happen on time, after all.",
  "art_09_s020": "Before the test, we were supposed to add up the points within each area and answer a brief question.",
  "art_09_s021": "At least one person a year usually gets the highest grade.",
  "art_09_s022": "Last of all, I hope that I am better than ever at writing, and maybe celebrate with a locally produced meal."
}
with open("teacher_validated_0.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
