import json

data = {
  "art_40_s001": "\"What kind of... person are you really?\" asked my friend, who is a famous architect.",
  "art_40_s002": "He is also a very fashion-conscious man, just like his sister.",
  "art_40_s003": "\"It doesn't matter,\" I answered calmly and poured some water into a beautiful glass.",
  "art_40_s004": "\"I am just a happy person who likes to have fun and enjoy myself every day.\"",
  "art_40_s005": "Our little gang was quite a motley crew.",
  "art_40_s006": "We consisted of a famous author, a smart philosopher, an agile acrobat and a fantastic musician with extremely great musical talent, who often played the saxophone and was a skilled troubadour.",
  "art_40_s007": "One of us used to collect a unique vinyl record from each new decade.",
  "art_40_s008": "We came from Sweden and from other countries, somewhat like an autonomous little family.",
  "art_40_s009": "We often used to camp, but our old car was always overloaded.",
  "art_40_s010": "Sometimes packing felt like hell.",
  "art_40_s011": "Our large tent was at the bottom under all the packing, but we wanted to see the world before the days got lighter and warmer.",
  "art_40_s012": "Sometimes we went to a large outdoor LARP where we got to compete for a shiny golden key.",
  "art_40_s013": "One of the participants was a funny guy who looked like a naked sumo wrestler.",
  "art_40_s014": "He had a lot of natural comedy in him.",
  "art_40_s015": "He was almost like a popular comedian and often created a comical atmosphere.",
  "art_40_s016": "I wrote about it in my diary.",
  "art_40_s017": "It was almost like an exciting fairy tale.",
  "art_40_s018": "We also loved nature.",
  "art_40_s019": "We used to cycle in the forest in the summer, or ski in the winter.",
  "art_40_s020": "My friend wanted to play golf and constantly looked for his best golf club.",
  "art_40_s021": "One day we saw a quiet hunter who was going out to hunt in the forest to kill wild animals.",
  "art_40_s022": "A small animal had a broken wing.",
  "art_40_s023": "\"Watch out for viper bites in front of the cabin,\" the hunter warned and pointed to a specific spot in the grass.",
  "art_40_s024": "Despite the dangers, we intended to stay.",
  "art_40_s025": "\"We will celebrate Christmas in this forest,\" I said happily.",
  "art_40_s026": "My friend was an extremely culture-interested person.",
  "art_40_s027": "He liked beautiful art with nature-inspired motifs to complement his collection.",
  "art_40_s028": "In his bag he had a small jar of good paint and wanted to paint.",
  "art_40_s029": "He used to say an old proverb: \"You should never burn your bridges.\"",
  "art_40_s030": "He also wanted to watch the old Swedish movie \"Summer with Monika\" with his big idol.",
  "art_40_s031": "He thought every beautiful movement in the movie was deeply romantic.",
  "art_40_s032": "Another person in the group just wanted to scratch a small lottery ticket or jump from a high diving tower by the lake.",
  "art_40_s033": "There was always something nice to do, whether you wanted to swim or just cycle around on the roads.",
  "art_41_s001": "On an ordinary Saturday evening we sat watching an exciting TV series and began to think about life.",
  "art_41_s002": "I was dressed in a black beret, just like a classic painter, but unfortunately it was too small.",
  "art_41_s003": "\"What are you going to do when...?\" my friend asked suddenly, without finishing the sentence.",
  "art_41_s004": "He was a skilled detective, although he also liked to blog about architecture and old crafts.",
  "art_41_s005": "\"I don't know.",
  "art_41_s006": "I would like to know how... you build a gigantic memorial building,\" I said honestly.",
  "art_41_s007": "We were very interested in culture, so we decided to pass a famous attraction in the city, a beautiful castle.",
  "art_41_s008": "There was a statue of solid bronze, a fantastic bronze statue.",
  "art_41_s009": "Suddenly we saw an old gossip magazine on the ground.",
  "art_41_s010": "\"What has happened?\" he said and picked it up to find clues.",
  "art_41_s011": "The magazine had a plot that seemed to be about an old folktale about a scary monster.",
  "art_41_s012": "\"Maybe a real monster can jump up out of the water!\" he said.",
  "art_41_s013": "\"You're exaggerating!\" I screamed.",
  "art_41_s014": "\"You are always so strict and intense.\"",
  "art_41_s015": "Later we heard music from a stage.",
  "art_41_s016": "It was a famous pop group that was going to play the violin, and it looked like a colorful circus.",
  "art_41_s017": "On the ground lay a loose cannonball.",
  "art_41_s018": "\"We have to make sure to hide it.",
  "art_41_s019": "It can cause harm,\" I said, but my friend just wanted to let it be.",
  "art_41_s020": "Instead, he wanted to take me to a large discotheque where a disco ball was spinning.",
  "art_41_s021": "We danced a whole lot, but I chose to skip a Tango course that was held there.",
  "art_41_s022": "Afterwards we felt like an adventure and chose to take a dip in the lake.",
  "art_41_s023": "Then I began to realize that it was much more fun than boring skiing or fast rallying.",
  "art_41_s024": "We talked about the old movie \"Fanny and Alexander\", a documentary we had seen half of, and about the ideas of the seventies regarding free sex.",
  "art_41_s025": "All this inspired me to write a beautiful poem the following morning, where my friend was a true hero.",
  "art_42_s001": "Sweden is a parliamentary democracy with a long history.",
  "art_42_s002": "Previously, there was a strong royal power.",
  "art_42_s003": "Today the monarchy has no political power.",
  "art_42_s004": "Our head of state is a king or a queen, but it is a prime minister and our parliament that decides on every law and governs our state.",
  "art_42_s005": "A future crown princess, a prince or a princess has a welcoming smile but makes no laws.",
  "art_42_s006": "\"Should we...?\" a friend asked suddenly, as we stood at a large railway station to catch a train.",
  "art_42_s007": "\"Talk about current politics, I mean.\"",
  "art_42_s008": "He was an ambitious climber within a large bourgeois organization.",
  "art_42_s009": "He wanted to get hold of a role as an important leader and famous politician.",
  "art_42_s010": "\"Okay, From where?\" I asked.",
  "art_42_s011": "\"Where should we begin?\"",
  "art_42_s012": "\"Well, we can retell a sudden scandal,\" he suggested.",
  "art_42_s013": "\"Someone wanted to lend a lot of state currency to a rich businessman so he became rich as a troll.",
  "art_42_s014": "It caused an economic crisis, a bad result of incorrect valuation.\"",
  "art_42_s015": "We also talked about darker events in our society.",
  "art_42_s016": "In the past, an elite could carry out a demonstration of power.",
  "art_42_s017": "Then terrible things could happen, even a murder.",
  "art_42_s018": "Someone could murder their competitor.",
  "art_42_s019": "Today we have a good police force that is to stand for security.",
  "art_42_s020": "It is important that every Jewish, Muslim or Christian group should feel safe.",
  "art_42_s021": "In a modern church, you should be able to celebrate a religious service in peace.",
  "art_42_s022": "A legal right and a fair rule create opportunities of various kinds, which provides a better quality of life for everyone.",
  "art_42_s023": "While we were talking, a cute little puppy sat on the ground and whined.",
  "art_42_s024": "A girl tried to comfort the dog because it had been frightened by a loud hairdryer from inside a hair salon.",
  "art_42_s025": "I started clapping my hands to attract the dog.",
  "art_42_s026": "It is funny how you can sometimes tire of social problems and instead talk about Swedish grammar.",
  "art_42_s027": "\"In Swedish there is something called phrasal verbs,\" my friend said.",
  "art_42_s028": "\"You combine a verb with a particle.",
  "art_42_s029": "You can also use a present participle.\"",
  "art_42_s030": "I sighed.",
  "art_42_s031": "We needed to find a good closing phrase to end the conversation before the train rolled in.",
  "art_43_s001": "A country can have different forms of government.",
  "art_43_s002": "Some countries are a republic with a president and sometimes a prime minister, while others have a king and a crown prince who must belong to a large royal family.",
  "art_43_s003": "Unfortunately, there are also countries where a power-mad dictator manages to take control through a brutal coup d'état.",
  "art_43_s004": "Then an interim government is often forced to resign, and political leaders can even be shot in the open street.",
  "art_43_s005": "In a democracy, on the other hand, you must be elected by the people to be in power.",
  "art_43_s006": "A democratic country is often governed by a parliament.",
  "art_43_s007": "A Member of Parliament represents a political party, and every vote from a general referendum counts.",
  "art_43_s008": "Some voters like a large, traditional party, but others choose to place their vote on a small single-issue party.",
  "art_43_s009": "What kind of promises do they have?",
  "art_43_s010": "Well, in their election manifesto, a party leader can promise a whole lot, for example changes concerning energy like nuclear power or public finances.",
  "art_43_s011": "Our famous government consists of many ministers.",
  "art_43_s012": "There is a Minister of Finance, a Minister for Foreign Affairs, a Minister for Education, a Minister for Culture and other important cabinet ministers.",
  "art_43_s013": "Their task is to keep order and cooperate with every government agency.",
  "art_43_s014": "Sixty years ago, society was much more unequal, a typical class society.",
  "art_43_s015": "But then a famous welfare state developed.",
  "art_43_s016": "A well-known social democratic movement wanted to build better welfare for every citizen in the country.",
  "art_43_s017": "Everyone who had children received a child allowance, and the elderly received a supplementary pension plus other various benefits.",
  "art_43_s018": "Even though we have a relatively high tax burden in Sweden today, that kind of system provides a great basic security.",
  "art_43_s019": "Politics must constantly develop in connection with the times.",
  "art_43_s020": "It is important to support a same-sex family, protect the environment on our beautiful coast, etc.",
  "art_43_s021": "I often associate politics with responsibility, because political decisions can easily end very badly if they are unprepared.",
  "art_43_s022": "One should not just stand with legs apart and make a grandiose entrance as if one were king for a day.",
  "art_43_s023": "By the way, did you know that a republican movement can often have its roots in old historical traditions?",
  "art_44_s001": "My daughter-in-law came for a visit at the end of the summer.",
  "art_44_s002": "She was politically active in her home country, an old peasant republic, but she wanted to move here.",
  "art_44_s003": "She thought about emigrating to get more modern freedom and a better life.",
  "art_44_s004": "She asked many questions about what it was like to govern our country.",
  "art_44_s005": "\"Sweden is divided into many areas,\" I began.",
  "art_44_s006": "\"Each municipality and county council has responsibility for its population.",
  "art_44_s007": "They take care of, for example, local public transport and all municipal services.",
  "art_44_s008": "If an adult resident needs help, there is an efficient social service that can provide a good social allowance.\"",
  "art_44_s009": "She had a deep gaze and immediately began to take notes.",
  "art_44_s010": "\"Who rules over the kingdom?\" she asked.",
  "art_44_s011": "\"There is a county administrative board regionally, but in the capital sits our prime minister and decides a lot.",
  "art_44_s012": "An important minister of defense and a green minister of environment work at their respective ministries.",
  "art_44_s013": "Every ministerial post is important.",
  "art_44_s014": "The people get to vote in general elections, since universal suffrage is a self-evident right.",
  "art_44_s015": "We protect the citizens against unfair discrimination through our fundamental laws, such as the Instrument of Government, the Freedom of the Press Act, and the Fundamental Law on Freedom of Expression.\"",
  "art_44_s016": "She was quiet for a while, like a silent prisoner inside her own bubble of thoughts.",
  "art_44_s017": "\"It sounds like a pretty safe country.",
  "art_44_s018": "It's possible.\" she said.",
  "art_44_s019": "\"Yes, and if a politician breaks the law, the people can fire him with immediate effect at the next election,\" I said and laughed.",
  "art_44_s020": "\"But is everything just difficult politics?\" she asked.",
  "art_44_s021": "\"Is there any peaceful and restful place to visit here in the country?\"",
  "art_44_s022": "\"Of course,\" I said.",
  "art_44_s023": "\"Here far away from all politics there is beautiful nature.",
  "art_44_s024": "You can find peace and quiet in a warm and sunny national park.",
  "art_44_s025": "Maybe see a famous royal or a famous world artist at some popular tourist resort.",
  "art_44_s026": "The town of Vimmerby, for example, is a very good travel destination where children can meet Pippi Longstocking.",
  "art_44_s027": "In the country there are even old statues of a historical national poet.\"",
  "art_44_s028": "\"Sounds nice,\" she said.",
  "art_44_s029": "\"Could one... instead just sit and eat good traditional home cooking at a restaurant?",
  "art_44_s030": "I feel quite rested now after the trip.\"",
  "art_44_s031": "\"Absolutely,\" I said and gave a small warning.",
  "art_44_s032": "\"But remember that we have had right-hand traffic since 1967 when you drive here.\"",
  "art_44_s033": "Every little factor plays a role when you change countries, and we really hoped that she would return sometime.",
  "art_44_s034": "She now first wanted to calm down with a good bite to eat and ordered her favorite from the café.",
  "art_45_s001": "My friend and I had cooked dinner together.",
  "art_45_s002": "While we were busy with our cooking in a shocking pink kitchen, we started discussing how our society has changed.",
  "art_45_s003": "We were of course a little tired, but also happy about a nice reception from the guests earlier.",
  "art_45_s004": "\"What are you thinking about?\" asked my friend, who is always very open-minded in her opinions.",
  "art_45_s005": "\"I am thinking about how it was historically,\" I said.",
  "art_45_s006": "\"During the Age of Liberty and earlier, every woman and innocent person suffered when the country's army was forced out to fight and defend a large empire.\"",
  "art_45_s007": "\"It is true.",
  "art_45_s008": "A conscious majority of the people, or rather a large part of our population, often suffered when old kings were to draw lines on the map and decide on the country's succession to the throne.",
  "art_45_s009": "But it was even worse for a foreign minority,\" she said.",
  "art_45_s010": "\"Are we happier today?\"",
  "art_45_s011": "\"It depends.\" I said.",
  "art_45_s012": "\"Many think that it has gotten much better.",
  "art_45_s013": "After a long historical process and rapid industrialization, we saw industrial growth emerge.",
  "art_45_s014": "We had a European development that gave more and more people stability.\"",
  "art_45_s015": "We also talked about law and justice.",
  "art_45_s016": "Today we have a modern institute for law and a fair judge who can pass sentence if someone were to commit a crime.",
  "art_45_s017": "In the past, people were often completely unaware of their rights, and a punishment was quickly handed out, while a reward only went to the power elite.",
  "art_45_s018": "\"Oh, well let's see...\" my friend said ironically.",
  "art_45_s019": "\"Today's people in power at least try to publish their decisions.\"",
  "art_45_s020": "\"Speaking of obligations, have you submitted your tax return?\" I asked.",
  "art_45_s021": "\"No, I have to declare tomorrow,\" she answered.",
  "art_45_s022": "\"But I must warn against talking more about the state.",
  "art_45_s023": "I feel like I've had one... too many of the wine.\"",
  "art_45_s024": "We changed the subject.",
  "art_45_s025": "\"What did you get?\" I asked suddenly, referring to a competition.",
  "art_45_s026": "She had gotten nine points.",
  "art_45_s027": "We also talked about a previous trip.",
  "art_45_s028": "\"A kind Swiss offered us a ride when we were traveling south near the Norwegian border,\" she recounted.",
  "art_45_s029": "\"Later we lived in a cabin in the countryside.\"",
  "art_45_s030": "We then discussed what happens after life.",
  "art_45_s031": "\"Do you believe in reincarnation?\" she asked.",
  "art_45_s032": "\"That you are born again afterwards?\"",
  "art_45_s033": "\"I was a bit frightened by the thought,\" I said, \"but finally I realized that it is fascinating.",
  "art_45_s034": "More than half of the earth's population believes in something like that, while the rest of them prefer to claim something else.",
  "art_45_s035": "There is however no evidence right now.\"",
  "art_45_s036": "When two rowdy cats suddenly started fighting in the hallway, I had to step in and hand out some food to calm them down.",
  "art_45_s037": "My friend immediately wanted to follow me out and help.",
  "art_46_s001": "\"How about...?",
  "art_46_s002": "Maybe we should read a new book,\" I suggested to a Swedish friend.",
  "art_46_s003": "He was already holding a thick book in his hand.",
  "art_46_s004": "\"What is it about?\" he wondered.",
  "art_46_s005": "\"It is a famous factoid about power and politics in the twenties and early 1930s,\" I explained.",
  "art_46_s006": "The book was about a dishonest financier who was recently divorced and chose to move here from abroad.",
  "art_46_s007": "He wanted to introduce a completely new type of fund and an expensive stock.",
  "art_46_s008": "The man was extremely impudent and used unfair corruption.",
  "art_46_s009": "He managed to persuade several wealthy investors, even an Italian count and a very rich Norwegian entrepreneur.",
  "art_46_s010": "Many of these were closely related to the power elite of that time.",
  "art_46_s011": "\"How much do you earn?\" they often asked him, and he always promised to increase the amount in their bank account.",
  "art_46_s012": "Most of them could only see a future enormous wealth.",
  "art_46_s013": "The financier wanted out of his old poverty and unfortunately chose to steal from the people instead of working honestly.",
  "art_46_s014": "Soon a national economic crisis arose.",
  "art_46_s015": "It was hard to know who would speak for the people when the state wanted to raise every little price.",
  "art_46_s016": "An ordinary worker almost never had any savings, and few people could afford to even live tolerably.",
  "art_46_s017": "If you couldn't state a steady income, food could cost more than you had ever earned.",
  "art_46_s018": "In every country there was also a moral truth that those in power turned a blind eye to.",
  "art_46_s019": "There existed a harsh oppression.",
  "art_46_s020": "For example, during large parts of the 40s homosexuality was still strictly forbidden in Sweden.",
  "art_46_s021": "To be yourself meant that you would risk ending up in prison.",
  "art_46_s022": "You could easily get lost in the law book and suddenly be guilty of a serious crime.",
  "art_46_s023": "It was truly a shameful period in history.",
  "art_46_s024": "A contemporary politician tried to give a sensible counterargument in the parliament, but unfortunately it took a while before the people got real freedom.",
  "art_46_s025": "\"I don't really know.\" my friend said quietly and started petting his tired dog.",
  "art_46_s026": "\"It sounds very heavy.",
  "art_46_s027": "But it is good that the state stopped reporting people for love.",
  "art_46_s028": "Today you can at least live openly, be a proud member of an ordinary sports club or donate a million to charity without it necessarily having to appear in the press.\"",
  "art_47_s001": "I met my friend Sami at a large square in the city.",
  "art_47_s002": "He was thirty-three years old and had just moved to Sweden to settle here.",
  "art_47_s003": "\"Can you speak a little slower?\" he asked kindly.",
  "art_47_s004": "\"I want to understand better and learn more.\"",
  "art_47_s005": "We discussed the country's future and history.",
  "art_47_s006": "Sami said: \"During the 19th century and the beginning of the 20th century, many Europeans lived in a strong monarchy or in a powerful empire that was ruled by a cruel emperor.",
  "art_47_s007": "Some residents were forced to convert to a specific faith, for example become Lutheran Christian, otherwise threats and great insecurity quickly arose.\"",
  "art_47_s008": "\"Yes, indeed,\" I said.",
  "art_47_s009": "\"And in a pure dictatorship there was a lot of violence.",
  "art_47_s010": "If a radical socialist or nationalist leader wanted to change the country too fast, a dangerous war could start.",
  "art_47_s011": "Even in our peaceful country, power is regulated in a law called the Act of Succession.",
  "art_47_s012": "Many young people today get involved in a youth league to fight for equality and regional self-government.\"",
  "art_47_s013": "Sami nodded understandingly.",
  "art_47_s014": "\"What do you prefer to do?\" he asked curiously.",
  "art_47_s015": "\"I think it is nice to sometimes be by myself out on a quiet jetty, but I also like a good political debate,\" I answered.",
  "art_47_s016": "\"A lot of politics right now is about an increased global import and how we can export safely to the USA, find a German alliance, or investigate a Thai market.",
  "art_47_s017": "This requires enormously good societal planning.",
  "art_47_s018": "As they say in English, it is about the economy.\"",
  "art_47_s019": "\"What?!",
  "art_47_s020": "You're joking!\" exclaimed Sami and laughed.",
  "art_47_s021": "\"It sounds very complicated.",
  "art_47_s022": "I thought only expensive food would be on the menu today.\"",
  "art_47_s023": "Suddenly we heard a scream.",
  "art_47_s024": "A criminal thief had tried to rob a store nearby and then tried to escape.",
  "art_47_s025": "In the panic, chaos arose in all local traffic.",
  "art_47_s026": "Two cars, of which one vehicle belonged to the Swedish military, happened to crash, which caused a serious traffic accident.",
  "art_47_s027": "We saw a shocking accident happen before our eyes.",
  "art_47_s028": "A high-ranking police superintendent came there to try to handle the situation.",
  "art_47_s029": "It was hard to know who is who among all the screaming witnesses.",
  "art_47_s030": "Someone claimed that a man had been murdered by a known murderer and then been shot, and that there had been great enmity between them.",
  "art_47_s031": "This turned out to be a pure untruth, however.",
  "art_47_s032": "The police arrested three suspicious persons at the scene, and chose to immediately invite all involved to the police station for interrogation.",
  "art_48_s001": "One Friday my teacher, a nice Englishman, talked a lot about Swedish politics and history, about past and present.",
  "art_48_s002": "\"Are you following along?\" he asked and looked at us.",
  "art_48_s003": "\"Already as young I often heard a story about how old countries functioned,\" he began.",
  "art_48_s004": "\"Some countries had for a long time a powerful rule under a specific empress.",
  "art_48_s005": "At that time you would crown a ruler with pomp and circumstance so that they would sit on a throne.",
  "art_48_s006": "Sometimes there was also a religious leader, like a Catholic pope, or a representative for a Lutheran denomination within our early Christianity.\"",
  "art_48_s007": "He recounted that it was often dangerous to meddle in power at that time.",
  "art_48_s008": "An unknown foreigner or a political opponent could quickly end up on a gallows hill for a bloody execution.",
  "art_48_s009": "You could also be forced to curl up into a fetal position if someone threatened to shoot a heavy iron ball at you during a war.",
  "art_48_s010": "\"How stupid can you be?\" a classmate said and began staring at a terrible picture in a magazine about old weapons.",
  "art_48_s011": "\"A two-kilo ball is super heavy and life-threatening.\"",
  "art_48_s012": "Then society changed drastically.",
  "art_48_s013": "We went from manual labor to industrial mass production and an increased consumption in itself, much thanks to early globalization.",
  "art_48_s014": "Our own country got a new political system.",
  "art_48_s015": "A local association from each county gathered to create a democratic state.",
  "art_48_s016": "Today much legislation is governed by a member of parliament in Stockholm and every local member in our various committees.",
  "art_48_s017": "An important representative for the people should have a modern view of everyone's equality, completely regardless of gender or sexual orientation.",
  "art_48_s018": "At the same time, a large referendum or a more ordinary vote can be about very difficult issues.",
  "art_48_s019": "Even twelve years later you might remember a historic decision about for example a national liquor prohibition and how hard it was to keep track of all the different political opinions.",
  "art_48_s020": "Today we discuss modern dangers like racism and right-wing extremism.",
  "art_48_s021": "Sometimes a famous female party leader goes out on a major news program to remind of the importance of a political consensus between two major political blocs.",
  "art_48_s022": "Then a strong coalition is often required.",
  "art_48_s023": "You try to jointly fight dangerous ideas like extreme communism.",
  "art_48_s024": "If the people want to complain, they often choose to demonstrate in a peaceful demonstration.",
  "art_48_s025": "The main square is usually down in town, and it serves as a very good gathering place.",
  "art_48_s026": "Recently I heard a Swiss politician who was stubborn as a mule facing a new bill about the families of the future.",
  "art_48_s027": "He discussed among other things the right to adopt small children from an exposed orphanage.",
  "art_48_s028": "It clearly showed that politics always is and remains important for our everyday life.",
  "art_49_s001": "I said thanks in advance to my best friend because he wanted to come.",
  "art_49_s002": "We had decided to meet and talk about relationships and how we usually feel.",
  "art_49_s003": "He said that he would of course be there.",
  "art_49_s004": "He was my best friend, a person that I could always chat with.",
  "art_49_s005": "We started discussing what we thought was important.",
  "art_49_s006": "\"What do you usually like best in a family?\" I asked.",
  "art_49_s007": "\"And what do you usually like least?\"",
  "art_49_s008": "\"You should like honesty,\" he answered and looked happy.",
  "art_49_s009": "\"A pleasant conversation is always good, whether it's deep talk or just a little sports talk.\"",
  "art_49_s010": "\"I agree.\" I answered quickly.",
  "art_49_s011": "\"And that you can forgive another friend.",
  "art_49_s012": "A strong friendship is extremely important to feel good and feel happy.\"",
  "art_49_s013": "We then talked about why people sometimes choose to divorce and suddenly can become like an enemy to each other.",
  "art_49_s014": "It is always sad when a long relationship ends.",
  "art_49_s015": "Memories from a beautiful wedding or a nice wedding anniversary can feel far away.",
  "art_49_s016": "People can unfortunately separate over time.",
  "art_49_s017": "Some then choose to live separately, and conflicts can occur.",
  "art_49_s018": "\"Then you sometimes have to hand over the responsibility and let the other person go free from criticism,\" he said.",
  "art_49_s019": "\"You shouldn't have to walk around feeling anger.\"",
  "art_49_s020": "He then told me about his own girlfriend.",
  "art_49_s021": "\"She is an enormous animal lover, and we try to inform others about a new campaign for vulnerable animals, both big and small.\"",
  "art_49_s022": "\"Are you really in love with her?\" I asked.",
  "art_49_s023": "\"Yes, I can really love our quiet family life.",
  "art_49_s024": "But sometimes I can still feel lonely when she travels a lot.\"",
  "art_49_s025": "\"It is roughly like that for me too sometimes,\" I said to agree.",
  "art_49_s026": "\"I guess we'll see.\" he said calmly.",
  "art_49_s027": "\"It will work out.\"",
  "art_49_s028": "And after that we were both tired.",
  "art_49_s029": "It was late, it was a super late evening, and young people outside the window shouted words with the prefix jätte- in front of everything.",
  "art_49_s030": "I tried to be as quiet as a mouse and started to sneak towards the door.",
  "art_49_s031": "\"You're lucky to be able to fall asleep fast,\" he smiled.",
  "art_49_s032": "\"Love will go a long way, if you just dare to want it.\""
}
with open("translations_4.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
