import json

data = {
  "art_30_s001": "Hope you are all doing well!",
  "art_30_s002": "My everyday life probably looks like something completely different from yours.",
  "art_30_s003": "I work from home in an old accommodation that used to be a hostel.",
  "art_30_s004": "The building is as big as a small palace, or maybe more like a large country house.",
  "art_30_s005": "In a cozy room near a lock, I sit in my sweatpants.",
  "art_30_s006": "I usually daydream and take a break with coffee and a hard rusk in my living room.",
  "art_30_s007": "Sometimes I use snus.",
  "art_30_s008": "In the winter, for example a cold February, I usually stay home.",
  "art_30_s009": "I am a bit like a cleaner and try to keep the environment clean everywhere.",
  "art_30_s010": "I do not like dragging heavy bags from a furniture store or shopping in a stressful shopping center downtown.",
  "art_30_s011": "In a Swedish welfare state, there was always a tradition of staying home with the family.",
  "art_30_s012": "A cozy evening (\"en sån\" = colloquial for such a cozy evening) is what I usually live for.",
  "art_30_s013": "People in my neighboring country might have a different view of a fun nightlife.",
  "art_30_s014": "Eight out of ten want to go out and have fun.",
  "art_30_s015": "They want to visit a nice society house during a warm summer month and dance late into the nights.",
  "art_30_s016": "They like to advertise their parties.",
  "art_30_s017": "There is something for everyone there, but sometimes someone can be slippery as an eel and deceive.",
  "art_30_s018": "Silence can be better.",
  "art_30_s019": "I myself sometimes feel like an old knight who must prevent the chaos.",
  "art_30_s020": "Once an exotic scorpion came into my summer house.",
  "art_30_s021": "It was three years in a row that I lived there during the holidays.",
  "art_30_s022": "I was completely half-asleep and had to wave it away when it ran around on the floor.",
  "art_30_s023": "Now it is finally Sunday.",
  "art_30_s024": "Tonight I intend to use up some energy.",
  "art_30_s025": "Maybe I will debut as an author.",
  "art_30_s026": "I just learned a new clause about grammar and how to use the future tense.",
  "art_30_s027": "I usually always hold the door open for new opportunities in life.",
  "art_31_s001": "When my neighbor asked how I was doing, I said: \"-Well, just fine.\"",
  "art_31_s002": "But the truth is that this week has been quite stressful.",
  "art_31_s003": "Last Monday, I decided on a new lifestyle.",
  "art_31_s004": "Last week, I decided to change every everyday routine I had.",
  "art_31_s005": "I actually had severe sleep problems.",
  "art_31_s006": "My doctor gave me a choice: either... or.",
  "art_31_s007": "He thought I should be outdoors more.",
  "art_31_s008": "A few days ago, I started walking.",
  "art_31_s009": "I went to a clothing store that had a big sale all day.",
  "art_31_s010": "Instead of looking in an old catalog, I bought a new white swimsuit and a pair of extra thick socks.",
  "art_31_s011": "But suddenly I noticed that my wallet was gone.",
  "art_31_s012": "I didn't want to accidentally do something stupid or seem like I was trying to shoplift.",
  "art_31_s013": "I thought about asking someone in the staff who could act.",
  "art_31_s014": "They didn't find it.",
  "art_31_s015": "I don't usually skimp, but an expensive watch I had in my bag was also gone.",
  "art_31_s016": "Had I put it somewhere?",
  "art_31_s017": "The next morning it was freezing cold and the ground was icy.",
  "art_31_s018": "I took an ugly jacket and an umbrella.",
  "art_31_s019": "I was not used to the cold and started freezing right to my soul.",
  "art_31_s020": "I thought about daydreaming away.",
  "art_31_s021": "My current apartment is not as big as the house I lived in when I was 10 years old, but every detail is important.",
  "art_31_s022": "I went into my bedroom to rest for a quarter of an hour.",
  "art_31_s023": "\"Prepare yourself for the day after tomorrow!\" said a singing voice on the radio.",
  "art_31_s024": "It was a program about a capable housewife.",
  "art_31_s025": "One tip was to clean out your fridge, another was to take a sauna in your little bathroom to relax.",
  "art_31_s026": "Taking a sauna is a useful method for relaxation.",
  "art_31_s027": "I actually haven't taken a sauna at all, at least not for several months.",
  "art_31_s028": "Before, I bathed several times a week.",
  "art_31_s029": "After a couple of days, I felt better.",
  "art_31_s030": "I stopped giving up and decided to let out all the stress.",
  "art_31_s031": "If something breaks, what will it mean in a hundred years?",
  "art_31_s032": "You have to sleep eight hours a day, at least some time for yourself.",
  "art_31_s033": "My favorite team came in seventh place in the league, but what does it matter?",
  "art_31_s034": "Life goes on!",
  "art_32_s001": "\"Do you know who asked for you?\" my friend said.",
  "art_32_s002": "It was a lady companion from the past.",
  "art_32_s003": "She was very poor at first, but now she worked at an exclusive dog daycare here in our little suburb.",
  "art_32_s004": "I was tired and thought it was nice to laze around and be a real couch potato.",
  "art_32_s005": "But this morning was a flying start.",
  "art_32_s006": "It is so easy to oversleep when you are tired, and I woke up super late.",
  "art_32_s007": "\"I would like to...\" I thought, \"just stay in bed under the duvet\".",
  "art_32_s008": "I had to hurry.",
  "art_32_s009": "I had to quickly put on my clothes and really hurry to make it in time.",
  "art_32_s010": "Actually, I like interior design.",
  "art_32_s011": "I wanted to stay home and build a balcony to arrange a nice place to sit.",
  "art_32_s012": "But now I was in a hurry.",
  "art_32_s013": "I put my equipment in a big bag.",
  "art_32_s014": "I brought swimming trunks and swimming goggles.",
  "art_32_s015": "Despite my age, I felt strong as an ox.",
  "art_32_s016": "I did not want to stay inside and soak up negative energy, so I decided to head out into town.",
  "art_32_s017": "It was really a hectic day.",
  "art_32_s018": "A lot of people were out.",
  "art_32_s019": "I went to the swimming hall which had a communal sauna.",
  "art_32_s020": "The swimming hall was divided into different sections that were huge.",
  "art_32_s021": "I wanted to climb up the high diving tower.",
  "art_32_s022": "After the bath, you had to dry yourself carefully.",
  "art_32_s023": "I thought about calling the hairdresser for a haircut in a nice salon, so I wouldn't have to look boring.",
  "art_32_s024": "I also discovered that I had a small hole in my sweater.",
  "art_32_s025": "I thought about booking a traditional housewife's vacation, but there was high demand for all the tickets.",
  "art_32_s026": "Every number on the price list was incredibly high, and I felt a tiny bit worried.",
  "art_32_s027": "\"What do you want to do?\" my friend asked, who was just like me.",
  "art_32_s028": "We seemed to belong together through strong cultural ties.",
  "art_32_s029": "It is important to get in touch with old friends.",
  "art_32_s030": "Suddenly some kind of wild dog, which might have been pregnant, tried to attack a trash can on the street.",
  "art_32_s031": "I thought I had had an interesting experience today.",
  "art_32_s032": "At four o'clock it was time to go home and go to bed.",
  "art_33_s001": "Did you know that...?",
  "art_33_s002": "Spring is my favorite season, especially during a major holiday like Easter.",
  "art_33_s003": "Yes, it's true!",
  "art_33_s004": "During the later part of... well, spring, I usually chill out a lot.",
  "art_33_s005": "\"Do you usually have a cozy time?\" my sibling asked me recently.",
  "art_33_s006": "I answered yes, I love coziness, and I love to get cozy.",
  "art_33_s007": "I like to stay in my soft pajamas on my big couch, or in a comfortable armchair, with an interesting women's magazine next to me.",
  "art_33_s008": "But in many places in town, people like to go out on a pub crawl.",
  "art_33_s009": "It is a fun kind of entertainment.",
  "art_33_s010": "Someone might want to move out just outside the center to get some peace, while others want to be right in town.",
  "art_33_s011": "\"I don't have a penny.\" my friend said the other day.",
  "art_33_s012": "He was completely broke.",
  "art_33_s013": "He said he had to recycle every empty bottle and gather every little thing from his cupboard to get by.",
  "art_33_s014": "His weekly allowance was completely gone.",
  "art_33_s015": "I didn't want to keep my own finances a secret, so I said that I have to think about every thing I buy.",
  "art_33_s016": "To save money, I made a wise decision: I will not renovate my old kitchen now.",
  "art_33_s017": "It's only important to cover my basic needs, everything else doesn't count right now.",
  "art_33_s018": "I am not as hardworking as an ant anymore.",
  "art_33_s019": "Instead, I want to take care of myself.",
  "art_33_s020": "You must also learn to take care of yourself.",
  "art_33_s021": "You have to be prepared for change in life.",
  "art_33_s022": "When I got to my local kiosk, I felt that it started smelling good from candy and coffee.",
  "art_33_s023": "I bought a paper cone with hard candies and some chewing gum and then went to a checkout.",
  "art_33_s024": "I paid and put the goods in my bag.",
  "art_33_s025": "Then I stood in line to wait for the bus.",
  "art_33_s026": "\"That was awfully nice.\" I said to the driver when I got on.",
  "art_33_s027": "When I got home, I wanted to change the interior design a little.",
  "art_33_s028": "I wanted to throw open the windows and let fresh spring air stream into the room.",
  "art_33_s029": "I could point to a beautiful shade on the wall and compare the colors with my new rug.",
  "art_33_s030": "My home is a holy place to me.",
  "art_33_s031": "Next week a good friend might drop by.",
  "art_34_s001": "A necessary break from the city is important when you work a lot.",
  "art_34_s002": "Therefore, I decided to rent a rustic cottage at an old farm over a weekend.",
  "art_34_s003": "I wanted to log out and not stress.",
  "art_34_s004": "Before I left, I received an invitation to a fun night out with a couple of friends.",
  "art_34_s005": "But I declined.",
  "art_34_s006": "A guest in my house in the city was a kind old widow who liked to put a silver lining on existence.",
  "art_34_s007": "We used to have a silver lining on Saturday evenings with a luxurious box of chocolates.",
  "art_34_s008": "It could certainly replace the night out for a while, but now I needed to rest.",
  "art_34_s009": "In the cottage, above a dark cellar, there was a small hatch in the floor.",
  "art_34_s010": "I didn't want to open it at all, nor go down there.",
  "art_34_s011": "Have you heard of the story about the rat in the pizza?",
  "art_34_s012": "Urban legends usually fascinate me, and the cellar felt like a scary place.",
  "art_34_s013": "Instead, I stayed upstairs and read a daily newspaper for a long time.",
  "art_34_s014": "For real relaxation, the cottage had an old color TV and a microwave, but no other modern gadget.",
  "art_34_s015": "In the yard, I met a customer of the farmer, a woman with a nice hairstyle and a big hat.",
  "art_34_s016": "We actually had the same last name.",
  "art_34_s017": "We stood at the edge of the field and talked.",
  "art_34_s018": "I noticed that she had a bad habit of biting her nails.",
  "art_34_s019": "She had an ugly bite mark on her finger.",
  "art_34_s020": "She also used to smack her lips when she ate and sometimes swear.",
  "art_34_s021": "Some people also tend to pick their noses, which is another unpleasant thing.",
  "art_34_s022": "In comparison to the city, there was no limit to nature.",
  "art_34_s023": "I found a heavy axe to chop wood.",
  "art_34_s024": "You could spend many more hours on this work.",
  "art_34_s025": "Being of age means that you get to decide for yourself, but I just wanted to be here and cook a nice dinner for a cheap penny, if you could afford to cook cheaply.",
  "art_34_s026": "Maybe there was a communal women's and men's bath in the village that you could visit?",
  "art_34_s027": "But the cottage was clearly the best.",
  "art_34_s028": "Before we were going to close for the evening, I had to flush a little spider down the toilet.",
  "art_34_s029": "Then I slept soundly.",
  "art_35_s001": "When you travel north in the country, you can visit a famous cultural attraction that has survived more than a decade.",
  "art_35_s002": "Culture is important to many, and when it comes to entertainment, this place is more or less fantastic.",
  "art_35_s003": "The old house was once tied to local agriculture, but now they want to contribute to letting us experience a lot of fun.",
  "art_35_s004": "Some people are an absolute zero at singing and dancing, but here you can still join a large choir.",
  "art_35_s005": "Sometimes beautiful music is played and people are invited to a traditional dance or even an exciting masquerade ball.",
  "art_35_s006": "A famous cultural personality often seeks contact with young artists here.",
  "art_35_s007": "Others like art.",
  "art_35_s008": "In a large hall there is an impressive art collection.",
  "art_35_s009": "You can get an exhibition catalog to learn more about each exhibition.",
  "art_35_s010": "A famous Danish artist has his best painting here.",
  "art_35_s011": "Painting a beautiful picture or just drawing with pencil is a quiet and nice experience.",
  "art_35_s012": "Sometimes you can also look at a nice photo or an old historical document.",
  "art_35_s013": "\"You can really wonder who made this one?\", visitors usually say.",
  "art_35_s014": "But there is another part too.",
  "art_35_s015": "Maybe you want to join in?",
  "art_35_s016": "Some go to a chess club to play chess together.",
  "art_35_s017": "Board games are also played, and people usually play cards on Friday evenings.",
  "art_35_s018": "Others like to play video games all night.",
  "art_35_s019": "Some would rather play theater and dream of becoming a good actor one day.",
  "art_35_s020": "Even if there is a view of art as something strict, it is important to know that all interests are given space.",
  "art_35_s021": "Culture should not die out.",
  "art_35_s022": "Maybe you like sports?",
  "art_35_s023": "At the house's own sports bar you can watch an important match on TV.",
  "art_35_s024": "One person eats a tasty protein bar while the other has drunk a lot and almost broken his stick in half.",
  "art_35_s025": "You don't need to have any good ball sense to cheer, and you don't even need a ball to have fun.",
  "art_35_s026": "Sometimes martial arts are also shown, and it doesn't seem to matter what you like.",
  "art_35_s027": "There is a cultural mix for everyone, and all of this is a small expense for a lot of joy.",
  "art_35_s028": "It is thus a club and place where poetry meets wild partying.",
  "art_35_s029": "I walked away with a smile, full of inspiration and an unconditional love for culture.",
  "art_36_s001": "I love art.",
  "art_36_s002": "I have always been a person who wants to explore art history.",
  "art_36_s003": "Therefore I decided to take an art course.",
  "art_36_s004": "At first it was hard to remember every letter in the theoretical book, but I liked sitting in my studio and drawing in my exercise book.",
  "art_36_s005": "I also tried to make a drawing and some nude painting.",
  "art_36_s006": "Every visitor in my little gallery often used to mention how much they loved my beautiful landscape.",
  "art_36_s007": "They could discover exciting details.",
  "art_36_s008": "\"Doesn't it sound fun?\" I asked my friend.",
  "art_36_s009": "\"It was very fun to work with it.\"",
  "art_36_s010": "But to earn money I sometimes had to offer to decorate houses with my paintings.",
  "art_36_s011": "Life was not just about art.",
  "art_36_s012": "I was also a director.",
  "art_36_s013": "I tried to shoot a music video with my brother.",
  "art_36_s014": "He often used to play actor and always wanted to play actor in front of the camera.",
  "art_36_s015": "We wrote a movie script that was a mix of a mysterious myth, an action movie, and a romance movie.",
  "art_36_s016": "It was filmed in black and white color, which was a strange but nice detail.",
  "art_36_s017": "In one scene he had to string beads on a hairy thread.",
  "art_36_s018": "Probably the movie would turn out well.",
  "art_36_s019": "Later I also wrote a theatrical play.",
  "art_36_s020": "A famous actress, who by the way is single, wanted the lead role in my play.",
  "art_36_s021": "She had great respect for the country's theater tradition, and her performance would meet all expectations.",
  "art_36_s022": "But unfortunately she got sick.",
  "art_36_s023": "She had to take antibiotics for several weeks so as not to die from the infection.",
  "art_36_s024": "She was forced to leave the project and we had to change the name of the production.",
  "art_36_s025": "Such is the industry.",
  "art_36_s026": "It usually is like this sometimes.",
  "art_36_s027": "When I'm not working, I love Friday coziness.",
  "art_36_s028": "Instead of going to the cinema, I like to play a game of chess.",
  "art_36_s029": "I have also written a good novel.",
  "art_36_s030": "A colleague asked: \"What do you think about constitutional law, or the Olympics being held every four years?\"",
  "art_36_s031": "I answered: \"Well... I just want to think about culture.",
  "art_36_s032": "By the way, will you remember our fun Christmas party even ten years from now?",
  "art_36_s033": "What about you?\"",
  "art_36_s034": "I smiled and thought that it was a wonderful piece of my life.",
  "art_37_s001": "When summer was approaching, I wanted to celebrate and party every weekend.",
  "art_37_s002": "After many lazy days, I was extremely eager to party and wanted to start my vacation at a big music festival.",
  "art_37_s003": "First I had to book accommodation in good time.",
  "art_37_s004": "I found a spot behind a large department store nearby, and my plan was to park a wagon there in case it started to rain.",
  "art_37_s005": "\"Do you like festivals?\" asked my friend, who was a famous Swedish-speaking Finnish singer and artist.",
  "art_37_s006": "\"Well, it's totally okay.\" I said and smiled broadly.",
  "art_37_s007": "\"In what way?\" he then asked.",
  "art_37_s008": "\"Festivals are a part of my identity, and youth culture is important to me in many different ways,\" I answered.",
  "art_37_s009": "This festival was like a mighty art and industry exhibition, and here there was also exciting food culture.",
  "art_37_s010": "You could eat a big feast with local meat and fresh bread.",
  "art_37_s011": "Fees for the food could often be added, but it was worth its weight in gold anyway.",
  "art_37_s012": "At the end of the evening, a famous musician named Stry would play loud punk music.",
  "art_37_s013": "His voice was crystal clear and the energy was enormous.",
  "art_37_s014": "\"That sounds awful!\" my other friend shouted with some skepticism.",
  "art_37_s015": "He absolutely did not like loud music.",
  "art_37_s016": "Instead of listening, he preferred going to a silent cinema.",
  "art_37_s017": "He did a super fast search on his smartphone, looked at a digital map and showed us the way.",
  "art_37_s018": "We had traveled through large parts of northern Sweden.",
  "art_37_s019": "\"I saw a fantastic detective film recently.",
  "art_37_s020": "It was my favorite movie,\" he said enthusiastically.",
  "art_37_s021": "\"The film takes place in the coldest part of Norrland.",
  "art_37_s022": "The film is about... a serious crime.",
  "art_37_s023": "The film is based on a book by... a famous author.",
  "art_37_s024": "The film is based on a true story.\"",
  "art_37_s025": "\"Exciting!\" I said.",
  "art_37_s026": "\"I myself like comedies and scary horror movies.\"",
  "art_37_s027": "\"It was hilarious,\" my friend said.",
  "art_37_s028": "The day after we participated in a traditional dock dance.",
  "art_37_s029": "All this festivity could act as a positive change in our lives.",
  "art_37_s030": "Upon contact with so much joy, I felt that the joy could really take off.",
  "art_37_s031": "I even started rewriting an old poem, and thought about Swedish grammar and what a past participle is.",
  "art_37_s032": "If I was financially independent, I would live like this forever.",
  "art_38_s001": "\"Do you know what I have read?\" I asked my friend over the phone.",
  "art_38_s002": "\"It was an exciting newspaper article about a tall tale that usually spreads on the internet every two years.",
  "art_38_s003": "It is a funny urban legend about a Swedish charter traveler who called a foreign ministry just for fun.",
  "art_38_s004": "He said he was a close relative of the king.\"",
  "art_38_s005": "\"That was entertaining, but what happened then?\" she wondered.",
  "art_38_s006": "\"Well, it was really just a funny joke, kind of a big April Fool's joke\", I said to drag out the story.",
  "art_38_s007": "Then I asked her if she wanted to come along to a big amusement park in the city to see a new attraction.",
  "art_38_s008": "\"Unfortunately I can't today.\" she answered quickly.",
  "art_38_s009": "\"What did she want?\" I thought quietly to myself.",
  "art_38_s010": "\"How do you manage?\" I asked instead.",
  "art_38_s011": "\"What do you do all day long?\"",
  "art_38_s012": "She explained that she didn't like just lying around and lazing.",
  "art_38_s013": "Instead she wanted to do sports and have an active leisure time.",
  "art_38_s014": "She had a surprisingly large collection of training equipment.",
  "art_38_s015": "Her absolutely best leisure activity was downhill skiing during a cold winter.",
  "art_38_s016": "Every hour on the mountain was important.",
  "art_38_s017": "Sometimes she could take out an old ski boot and a ski pole from the garage and dream of the slope.",
  "art_38_s018": "\"It feels like a completely impossible task to live without the snow\", she said.",
  "art_38_s019": "Inside her there was also a great deal of imagination.",
  "art_38_s020": "\"But when the snow is missing, surely you like another sport where you can win a big competition?",
  "art_38_s021": "Maybe horseback riding or fast horse polo?",
  "art_38_s022": "Or playing floorball with friends?\"",
  "art_38_s023": "\"Yes, furthermore I love ice skating.",
  "art_38_s024": "I put on my skates and glide on the ice\", she answered.",
  "art_38_s025": "\"But I don't like all motorsports.",
  "art_38_s026": "I would never drive a sports car fast or be one of those so-called quiet golfers who walk around.\"",
  "art_38_s027": "There was a clear opinion in her choices.",
  "art_38_s028": "It seemed that her passions would belong in an active camp.",
  "art_38_s029": "Long transport to such a camp was sometimes hard, especially when clothes were covered in dirt.",
  "art_38_s030": "Not until she got home did she feel tired.",
  "art_38_s031": "She said an old quote about health.",
  "art_38_s032": "\"But don't you want to go to the theater every now and then?\" I asked her.",
  "art_38_s033": "\"Maybe\", she said with a laugh, \"but I actually think they should abolish all sedentary behavior in the world!\"",
  "art_39_s001": "Having a fun interest can show itself in different ways.",
  "art_39_s002": "Some love literature, which is a beautiful expression for thoughts.",
  "art_39_s003": "They might want to exhibit a nice picture at a museum.",
  "art_39_s004": "Others want to take off and look for an unusual stamp.",
  "art_39_s005": "Maybe they want to create a dialogue about culture.",
  "art_39_s006": "But for me, sports is the most important thing in my world.",
  "art_39_s007": "\"I love running. -What about you?\" a friend asked me a cold autumn.",
  "art_39_s008": "\"What kind of activity do you like?\"",
  "art_39_s009": "I like running and light jogging.",
  "art_39_s010": "Sometimes I usually run a long race, like for example an ultramarathon.",
  "art_39_s011": "But there are other things I do.",
  "art_39_s012": "I like cycling and orienteering in the forest, where my sharp sense of smell gets to enjoy fresh air.",
  "art_39_s013": "When I was at a summer camp last year, I got to try fun sailing and tough surfing.",
  "art_39_s014": "We also got to swim and practice swimming a lot in the lake.",
  "art_39_s015": "Sometimes we played volleyball by the beach, and handball or football on the grass.",
  "art_39_s016": "We even tested basketball.",
  "art_39_s017": "All this has a positive effect on me, and no sport is harmful if you are careful.",
  "art_39_s018": "You simply have to welcome all chances for play.",
  "art_39_s019": "During wintertime I switch sports.",
  "art_39_s020": "I do a lot of cross-country skiing and take out my best skis.",
  "art_39_s021": "It is also fun with snowboarding, but you always have to have a helmet to protect your head.",
  "art_39_s022": "I also like ice hockey.",
  "art_39_s023": "You hit the puck into a net with a stick to score points and win.",
  "art_39_s024": "\"It would be better to... not attack each other so hard on the ice,\" I usually joke.",
  "art_39_s025": "People have played sports since 1 AD, and I am happy with my choice of lifestyle.",
  "art_39_s026": "I can manage my own training and halve my stress level.",
  "art_39_s027": "Sometimes I lift a barbell at the gym, or do some intensive gymnastics with a good sense of rhythm.",
  "art_39_s028": "It also works really well to play table tennis or go out for a long walk with Nordic walking.",
  "art_39_s029": "Even e-sports or an exciting LARP can attract me, if I want to stay indoors.",
  "art_39_s030": "Sometimes I have to book and take time for rest, but I do it all in one and the same life!"
}
with open("translations_3.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
