import json

data = {
  "art_20_s001": "I do not mind being out in nature, especially when a month ago we visited a new eco-certified park.",
  "art_20_s002": "It is located a thousand meters above sea level, with a wonderful view of a clear sky.",
  "art_20_s003": "We stayed in a large treehouse built of solid wood.",
  "art_20_s004": "The atmosphere was informal and they take sustainability seriously.",
  "art_20_s005": "\"This seems to be a fantastic place,\" I said.",
  "art_20_s006": "\"I think so too,\" my friend replied.",
  "art_20_s007": "My friend is a famous sports star who wants to be environmentally conscious.",
  "art_20_s008": "\"Nature here is a real roller coaster,\" he laughed, because the landscape goes up and down a lot.",
  "art_20_s009": "We had a discussion about the environment.",
  "art_20_s010": "There is an important difference between old and new research on animal behavior.",
  "art_20_s011": "On the other hand, everyone agrees that our original nature is best.",
  "art_20_s012": "Within the park, they try to run a large treatment plant at full speed to reduce all emissions that cause our river to become polluted.",
  "art_20_s013": "Rarely do you see such a clean water surface as here, and it often comes in first place in the country.",
  "art_20_s014": "Many want to be an environmentally friendly visitor, which is a wise opinion.",
  "art_20_s015": "Last summer we could see the forest grow during a warm summer.",
  "art_20_s016": "Now, from cold dawn to dark dusk, the forest itself is absolutely fantastic.",
  "art_20_s017": "There they usually have plenty of wild animals.",
  "art_20_s018": "I can reveal that we saw an injured hen that was rescued.",
  "art_20_s019": "A wild rabbit stood up on its hind legs and next to it sat a little mouse and a rat near a rock.",
  "art_20_s020": "They have chosen to introduce certain animals to save the local fauna.",
  "art_20_s021": "A local moose population is thriving and we saw a proud cow moose.",
  "art_20_s022": "In addition, there was a badger, a small weasel and even a diligent beaver.",
  "art_20_s023": "We were warned about a venomous viper, but we still picked blueberries while a buzzing bee flew by.",
  "art_20_s024": "My friend jokingly said that he wanted to bring a donkey next time to carry everything.",
  "art_20_s025": "It was a fantastic experience.",
  "art_20_s026": "Find out more!",
  "art_21_s001": "We were in a beautiful and almost untouched part of the Nordic region.",
  "art_21_s002": "It was an evocative environment.",
  "art_21_s003": "We started the day by a beautiful water lily pond in a green valley.",
  "art_21_s004": "It was an evocative environment, and we could breathe fresh air.",
  "art_21_s005": "On a small blade of grass crawled an ant.",
  "art_21_s006": "On the south side of the mountain the sun was shining.",
  "art_21_s007": "\"Oh my,\" said our guide, \"look there!\"",
  "art_21_s008": "A large bear, more specifically a brown bear, was moving in the forest.",
  "art_21_s009": "Next to it lay a carcass that it was going to eat.",
  "art_21_s010": "\"It is basically impossible to see them like this,\" said our zoologist.",
  "art_21_s011": "He liked both... and when it came to plants and animals.",
  "art_21_s012": "We also saw a reindeer and a small sheep.",
  "art_21_s013": "A majestic moose and a small moose calf stood at the edge of the forest.",
  "art_21_s014": "A wolf, or 'ulv' as they used to say, howled in the distance.",
  "art_21_s015": "The forest was so dense that you had to ask for help to find your way out.",
  "art_21_s016": "I felt like walking closer to the edge, but I stopped just before a steep cliff.",
  "art_21_s017": "There was ice on the ground there.",
  "art_21_s018": "Our botanist showed us a rare plant, a beautiful honeysuckle.",
  "art_21_s019": "He told us how you could protect it.",
  "art_21_s020": "\"We must practice taking care of nature without destroying it.\"",
  "art_21_s021": "He drew a pattern on a piece of paper.",
  "art_21_s022": "He explained the difference between a male and a female in some flowers.",
  "art_21_s023": "In the water below swam an eel, but luckily no crocodile!",
  "art_21_s024": "In the sea far away we could see a dolphin.",
  "art_21_s025": "We had a dog with us, a happy poodle, and saw a colorful peacock at a farm.",
  "art_21_s026": "We also discovered a spider, a tick and a buzzing wasp.",
  "art_21_s027": "Suddenly we saw a snake and a large ox in the field.",
  "art_21_s028": "\"A large number of the animals we have seen are mammals,\" the guide said.",
  "art_21_s029": "They wanted to keep the right temperature in the cabin, but outside it began to drop already in the afternoon.",
  "art_21_s030": "We got to see a large portion of this area of twenty square kilometers.",
  "art_21_s031": "A Spanish tourist was with us.",
  "art_21_s032": "He was a teetotaler and only drank water, a fantastic local raw material.",
  "art_21_s033": "When the day was over he asked us to give feedback on his Swedish.",
  "art_21_s034": "This was my fifth trip here, and I will come here again!",
  "art_22_s001": "A few years ago I felt very bad.",
  "art_22_s002": "I had problems with my weight and I continued to gain weight.",
  "art_22_s003": "I was tired all the time, sometimes completely dead tired.",
  "art_22_s004": "I had trouble sleeping and it felt like a parasite in my body.",
  "art_22_s005": "A doctor even forced me to admit myself to a mental hospital because of the risk of suicide after an accidental overdose of medicine.",
  "art_22_s006": "It was a terrible time.",
  "art_22_s007": "I sometimes received advice by letter, but nothing seemed to suit me.",
  "art_22_s008": "But one day I read a tip on a wall next to the hospital: \"Listen to your heart.\"",
  "art_22_s009": "I decided to get well and that it is important to care about one's health.",
  "art_22_s010": "I didn't want to just sit and laze around.",
  "art_22_s011": "It was in connection with this I signed up for an exotic fitness trip.",
  "art_22_s012": "The event was to take place in Spain.",
  "art_22_s013": "I packed my workout clothes and running shoes.",
  "art_22_s014": "There began a close collaboration with a sporty gym instructor.",
  "art_22_s015": "He explained that all exercise is useful.",
  "art_22_s016": "He said that \"exercising\" provides a healthy lifestyle.",
  "art_22_s017": "We trained in a series of short sessions.",
  "art_22_s018": "It was a form of exercise that was based on intensive strength training.",
  "art_22_s019": "At first I got a very bad pain in a knee and in every muscle in my legs.",
  "art_22_s020": "Sometimes I became partially deaf from exertion, but I learned to stretch after every workout.",
  "art_22_s021": "Even though I got extreme muscle soreness, it still felt good to sweat and improve my fitness.",
  "art_22_s022": "It's not all just about training really hard, you also have to relax.",
  "art_22_s023": "Resting is not a half-truth - it is very important!",
  "art_22_s024": "My form improved much faster than I had ever seen.",
  "art_22_s025": "The heart rate was at its lowest when we meditated.",
  "art_22_s026": "We learned to listen to the body, which works a bit... on its own, in a fantastic way.",
  "art_22_s027": "If someone had said that I would train in a fine tailcoat I would have laughed.",
  "art_22_s028": "Everyone wanted to tag along.",
  "art_22_s029": "When I finally asked to get an answer to what health is called, my trainer said: \"It is life.\"",
  "art_23_s001": "Two weeks ago I started working in a new department.",
  "art_23_s002": "I am a nurse and I enjoy it very much.",
  "art_23_s003": "It is my third job in my 30s.",
  "art_23_s004": "I help a physician, also called a doctor in everyday speech.",
  "art_23_s005": "He has great wisdom.",
  "art_23_s006": "We must take care of patients who are sick without interruption.",
  "art_23_s007": "A patient, an old sailor, had serious problems with his heart.",
  "art_23_s008": "He was also mentally ill and had a severe gambling addiction as well as an old drug addiction.",
  "art_23_s009": "He often said that he was a former drug addict.",
  "art_23_s010": "It is unfortunately an addiction that can indirectly affect the whole body negatively.",
  "art_23_s011": "Before that he had also been craving a smoke and used to smoke three packs of cigarettes a day.",
  "art_23_s012": "His dental health was extremely bad with a lot of cavities in every tooth.",
  "art_23_s013": "You have to decide to change your life.",
  "art_23_s014": "A major health debate in society is about how to protect people from getting too close to drugs.",
  "art_23_s015": "But regardless of the cause, we must be patient and take care of everyone equally well.",
  "art_23_s016": "In another room lay a woman with a serious viral disease and an extremely high body temperature.",
  "art_23_s017": "It was perhaps a tick-borne disease because she had had biting insects on her.",
  "art_23_s018": "Such insects like regular animal blood, but also human blood.",
  "art_23_s019": "An insect had bitten her straight in a vein, which gave her a severe ache.",
  "art_23_s020": "It felt as if the pain would explode.",
  "art_23_s021": "Her disease was still mysterious.",
  "art_23_s022": "Some days I feel uninterested, but usually I love my job at this hospital.",
  "art_23_s023": "Even when there is a lot of talking with patients, I become happy.",
  "art_23_s024": "You can sometimes get tired of the system, like sick pay only being paid out if you draw a line on a piece of paper.",
  "art_23_s025": "And every eighth year we have to update licenses, which we immediately forget.",
  "art_23_s026": "We usually put on a good song and apply a nice skin cream when the shift is over.",
  "art_23_s027": "When I walked home my boss said: \"Take care of yourself!\"",
  "art_23_s028": "I smiled and answered: \"Say hello to...! yes, say hello to your family for me!\"",
  "art_23_s029": "See the entire glossary below.",
  "art_24_s001": "\"In the beginning of... well, in the 20th century, our healthcare looked completely different than today,\" said my old grandmother.",
  "art_24_s002": "\"Some medical knowledge has indeed existed since 500 BC, but society has changed.\"",
  "art_24_s003": "We had gathered in a beautiful pavilion to celebrate her birthday.",
  "art_24_s004": "It became a touching storytelling about her long life.",
  "art_24_s005": "\"Yes, I promise!\" she continued eagerly.",
  "art_24_s006": "\"In the past, everything was anything but easy.\"",
  "art_24_s007": "She had worked in Swedish healthcare for many years.",
  "art_24_s008": "The buildings used to be located close to each other on the hospital grounds.",
  "art_24_s009": "In a small room with a huge smell of smoke and strong medicine, they took care of the patients.",
  "art_24_s010": "Sometimes they had to give birth control pills or a painkiller tablet to the women.",
  "art_24_s011": "If a woman was pregnant and felt anxiety, she was allowed to rest a little more.",
  "art_24_s012": "You often had to check with an experienced doctor before anyone could switch to a new treatment.",
  "art_24_s013": "\"In a Sami village in the north there was a woman with a severe disability,\" she remembered.",
  "art_24_s014": "\"She often had to walk on foot down the mountain.\"",
  "art_24_s015": "It became a reason why the state wanted to expand society.",
  "art_24_s016": "The politicians wrote an important draft law, which later became a government bill, about everyone's right to dental care, childcare and elderly care.",
  "art_24_s017": "Every citizen would have the right to good care, which was a huge investment for our country.",
  "art_24_s018": "The goal was for the people's needs to be met.",
  "art_24_s019": "\"When I was young we had just enough food,\" she laughed when we ate together.",
  "art_24_s020": "We often ate traditional blood bread with various side dishes.",
  "art_24_s021": "An important ingredient was often salted ham.",
  "art_24_s022": "But when I got a pain in my stomach, my regular food was taken away.",
  "art_24_s023": "We rarely ate sweets, maybe a little good vanilla sauce if we were lucky.",
  "art_24_s024": "My grandmother's physical condition was bad about five years after the war.",
  "art_24_s025": "Then the plates were rarely filled with fresh food, but sometimes only filled with warm soup.",
  "art_24_s026": "Once she accidentally got shampoo in her eyes when she was washing, and almost fell off her stool!",
  "art_24_s027": "\"My bowl was at least completely filled,\" she remembered.",
  "art_24_s028": "Despite all the lack of money, year after year they tried to help the sick from beginning to end.",
  "art_24_s029": "A warm heart can sometimes cure a lot.",
  "art_24_s030": "If someone was stricken, they tried to bury the worry and talk openly.",
  "art_24_s031": "After the right care, they could often go back to normal.",
  "art_25_s001": "My little brother and I lived in a small, peaceful village.",
  "art_25_s002": "On a shining green hill you could look out over the whole community.",
  "art_25_s003": "But our starting point was not easy.",
  "art_25_s004": "We had to experience a terrible time.",
  "art_25_s005": "It was a contrast to the surface, where everything seemed fine.",
  "art_25_s006": "Up until the year... yes, up until the year 1986, when a famous nuclear accident happened, there was no worry.",
  "art_25_s007": "\"How come...?\" my brother often asked when he heard the news.",
  "art_25_s008": "A popular mass medium reported about the dangers.",
  "art_25_s009": "This disaster could lead to many getting sick.",
  "art_25_s010": "A doctor in our village was unfortunately stabbed to death and another woman was threatened when someone tried to shoot her to death on a wide hill.",
  "art_25_s011": "It was totally sick!",
  "art_25_s012": "The perpetrator was a heartless psychopath with a complex syndrome in his brain.",
  "art_25_s013": "He felt no sympathy and could even lie and resort to a lie in court.",
  "art_25_s014": "We were taught to always be together to secure our future.",
  "art_25_s015": "There could be dangers, and the National Board of Health and Welfare warned that a new infectious disease was on its way.",
  "art_25_s016": "A nurse who was trained in emergency care said: \"Ask questions if you feel stomach cramps or get a strange pupil in your eye, and stay home if you are about to faint.\"",
  "art_25_s017": "The medicine she gave could taste bad, but it was precise, and one was well taken care of.",
  "art_25_s018": "They wanted to reduce the risks of getting worse.",
  "art_25_s019": "Getting care on time was important.",
  "art_25_s020": "I also remember that you could do whatever you wanted when it came to contraceptives.",
  "art_25_s021": "But people were sometimes unsure and believed in incorrect information.",
  "art_25_s022": "Right, we had to send in a form to get help.",
  "art_25_s023": "If someone had a handicap and was disabled, an ambulance could roll in to pick them up.",
  "art_25_s024": "Many times we had to keep a positive body language to help them call for doctors.",
  "art_25_s025": "Now when I usually think back on those ten years, I want to advise everyone to value their health.",
  "art_26_s001": "A cold January I met a typical fitness fanatic.",
  "art_26_s002": "He seemed born to move.",
  "art_26_s003": "Every morning, constantly and completely without pause, he used to jog in the forest.",
  "art_26_s004": "His motto was: \"The ... the!\" which for him meant: the faster, the healthier.",
  "art_26_s005": "He had decided to set a big goal and run a marathon.",
  "art_26_s006": "He loved being active and wanted to get out to build up his endurance, his strength and his speed.",
  "art_26_s007": "He could be good at doing thirty push-ups in a row.",
  "art_26_s008": "Even though he was thin he was very strong and always alert.",
  "art_26_s009": "He never thought he would be admitted to a hospital.",
  "art_26_s010": "He was registered at a private gym that surely earned a billion, since the industry was enormous.",
  "art_26_s011": "He managed his eating habits perfectly and drank absolutely no alcohol, so he was never intoxicated.",
  "art_26_s012": "He liked to interview his friends and give them training advice.",
  "art_26_s013": "He knew how to save a bad back with the right protection, and how a quick freshening up could positively surprise the body.",
  "art_26_s014": "He loved to feel fresh and refused to smell bad even if he was sweaty.",
  "art_26_s015": "But one day something happened that made him understand that health is fragile.",
  "art_26_s016": "He would unfortunately be forced to rest.",
  "art_26_s017": "He was suddenly bitten by a dog that was infected with rabies!",
  "art_26_s018": "He quickly became infected and got a serious infection.",
  "art_26_s019": "It was not like a normal allergy, but the body reacted like a severe allergic shock with a severe cough.",
  "art_26_s020": "The pain spread in every nerve.",
  "art_26_s021": "He began to suffer enormously.",
  "art_26_s022": "His suffering was terrible and he even got a partial facial paralysis.",
  "art_26_s023": "He had to undergo a long treatment and was often stressed about lost income after his first waiting day.",
  "art_26_s024": "He could not activate himself as usual.",
  "art_26_s025": "After what felt like an entire century in bed, he could finally cross an invisible line back to health.",
  "art_26_s026": "He now believes that the ability to stop sometimes symbolizes true wisdom.",
  "art_27_s001": "There was a poster in our waiting hall that showed the dream of good health.",
  "art_27_s002": "On the poster it said: \"Why not?",
  "art_27_s003": "You can feel top class!\"",
  "art_27_s004": "But in reality it is often difficult.",
  "art_27_s005": "My patient Per used to come from a tough environment.",
  "art_27_s006": "He was, as he himself said, an alcoholic and used to abuse a dangerous drug over time.",
  "art_27_s007": "After an accident with a horse, where he almost managed to break his neck, he stayed a long time at our hospital.",
  "art_27_s008": "He had deep wounds on his neck, and a broken joint, especially his left ankle.",
  "art_27_s009": "He had to replace several broken teeth with false teeth.",
  "art_27_s010": "\"What are you going to do now?\" I asked him once.",
  "art_27_s011": "\"Weeeell... I don't really know,\" he answered, and started to clear his throat.",
  "art_27_s012": "He said that the accident was a drunken mistake or something like that.",
  "art_27_s013": "He also suffered from an extreme fatigue.",
  "art_27_s014": "He was actually an allergy sufferer and was very allergic to certain unhealthy foods, which ironically led to overweight.",
  "art_27_s015": "His stomach and his mouth could sometimes swell up and his tongue became very swollen.",
  "art_27_s016": "Sometimes it started to itch all over his head and he got a severe headache.",
  "art_27_s017": "He often felt depressed, and it was a serious time.",
  "art_27_s018": "He said it felt as if he had gotten the plague or a very dangerous pneumonia.",
  "art_27_s019": "He had a high fever and could barely breathe.",
  "art_27_s020": "Contrary to what he had thought, there was no quick medicine to cure everything immediately.",
  "art_27_s021": "We set up a schedule to be able to carry out his treatment, and he had to stay under safe supervision.",
  "art_27_s022": "\"It is good to get vaccinated against the seasonal flu,\" I said.",
  "art_27_s023": "\"We will vaccinate you tomorrow.\"",
  "art_27_s024": "It is important because it helps us not to transmit infection to other patients.",
  "art_27_s025": "In the past there was a lot of garbage and untruths in healthcare, and old myths have been able to live on for fifty years, for example rumors about dangerous abortion.",
  "art_27_s026": "But now we can plan better in advance and maybe one can imagine a much brighter future.",
  "art_27_s027": "Towards the end of the year Per was finally eager for life again, after about nine months at the clinic.",
  "art_28_s001": "A long time ago I had a pretty bad habit.",
  "art_28_s002": "I used to clean my home and wash the dishes in the middle of the night.",
  "art_28_s003": "I was awake every night.",
  "art_28_s004": "It was a completely incomprehensible phenomenon.",
  "art_28_s005": "\"How often?\" a friend asked me yesterday.",
  "art_28_s006": "Often, I answered.",
  "art_28_s007": "I wanted to have a quiet sound in my house.",
  "art_28_s008": "But I decided to change my life and build up a new routine.",
  "art_28_s009": "I wanted to wake up much better and have more energy.",
  "art_28_s010": "Nowadays I sleep well at night, and thus I feel great.",
  "art_28_s011": "I wake up early every day.",
  "art_28_s012": "Sometimes my morning routine only takes a minute.",
  "art_28_s013": "I usually take a shower immediately.",
  "art_28_s014": "Standing in a warm shower is relaxing.",
  "art_28_s015": "Then I put on suitable clothes, or even swimwear if I am going swimming, and fix my hair.",
  "art_28_s016": "\"I don't have time,\" I used to say.",
  "art_28_s017": "All the time I felt stressed and chose to exclude important things.",
  "art_28_s018": "But I never want to go through that period again.",
  "art_28_s019": "I sometimes drank liquor, which was bad.",
  "art_28_s020": "Now I want to relax in the right way instead.",
  "art_28_s021": "My old period is today completely forgotten.",
  "art_28_s022": "In my spare time I have started running outdoors.",
  "art_28_s023": "I recently bought a pair of expensive running shoes.",
  "art_28_s024": "Despite an incredibly high price level, it was a good option on our market.",
  "art_28_s025": "I don't run every time I am off, but at least once every week.",
  "art_28_s026": "Actually, my goal is to run exactly once a week according to my training schedule.",
  "art_28_s027": "\"I have no idea about...\" I said to myself when I started.",
  "art_28_s028": "I didn't know if I could run for a long time, but I accept the time it takes.",
  "art_28_s029": "It can take the time it needs.",
  "art_28_s030": "Eventually I want to run closer to ten kilometers.",
  "art_28_s031": "Maybe in a month I can manage five kilometers, or in half a year.",
  "art_28_s032": "Next year maybe I'll manage the whole way.",
  "art_28_s033": "I hope to be able to keep this fantastic routine always.",
  "art_28_s034": "In the evening course in Swedish we learn which time preposition to use when talking about time.",
  "art_28_s035": "We also learn to conjugate verbs.",
  "art_28_s036": "When a friend usually rings my doorbell nowadays, I have already run and am full of energy!",
  "art_29_s001": "For a long period I lived in an old apartment.",
  "art_29_s002": "At that time I often felt unfresh and dirty because we didn't have a good bathroom.",
  "art_29_s003": "I used to lie awake at night.",
  "art_29_s004": "I felt almost like a tired skeleton and thought the room tried to hold my energy in captivity.",
  "art_29_s005": "But I have always been interested in... well, interior design and real estate.",
  "art_29_s006": "So recently I started looking for a new home.",
  "art_29_s007": "It became the beginning of an exciting time.",
  "art_29_s008": "A good house purchase usually always takes time and house prices can be extreme.",
  "art_29_s009": "Every other evening I used to follow the market and write a list of interesting properties.",
  "art_29_s010": "An important aspect was that the home should fit my personality.",
  "art_29_s011": "\"I can't quite keep up!\" my friend said, because I had been to a showing a lot of times.",
  "art_29_s012": "In the end I decided to negotiate a small luxury villa and buy it with my saved money.",
  "art_29_s013": "My old apartment I would of course sell.",
  "art_29_s014": "The house I bought had a beautiful brown door.",
  "art_29_s015": "I also bought a painting with a beautiful night motif that would take center stage in my new living room.",
  "art_29_s016": "Today I can truly say: We have it really good here in... our small village.",
  "art_29_s017": "My new household works much better.",
  "art_29_s018": "To this day I enjoy my new home.",
  "art_29_s019": "I usually get up at eight o'clock every morning.",
  "art_29_s020": "I press a button on the coffee machine.",
  "art_29_s021": "It is important to wash, shave and comb your hair before you go out.",
  "art_29_s022": "Sometimes you also have to get a haircut to remain nice.",
  "art_29_s023": "Then I put on a comfortable shoe and am ready.",
  "art_29_s024": "\"Dwelling\" is by the way a good collective name for a place where you can live.",
  "art_29_s025": "What happens tomorrow?",
  "art_29_s026": "Well, in my free time I will visit a beautiful opera house and then a large public bath.",
  "art_29_s027": "I got it as a birthday present from a friend.",
  "art_29_s028": "Next time I hope we can get into a quiet moment and have a fun game night.",
  "art_29_s029": "Maybe some artistic critic will come visit who has a similar taste to me.",
  "art_29_s030": "At this time I am just enjoying life."
}
with open("translations_2.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
